<!--
{{DataProcessingName}}数据导入导出组件
企业级数据导入导出管理，支持多格式文件、批量处理、错误处理
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="data-import-export">
    <!-- 数据处理头部 -->
    <div class="data-processing-header">
      <div class="header-info">
        <h2>{{ config.title }}</h2>
        <div class="process-stats">
          <div class="stat-item">
            <span class="stat-label">待处理</span>
            <span class="stat-value">{{ statistics.pending }}</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">处理中</span>
            <span class="stat-value">{{ statistics.processing }}</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">已完成</span>
            <span class="stat-value">{{ statistics.completed }}</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">成功率</span>
            <span class="stat-value">{{ statistics.successRate }}%</span>
          </div>
        </div>
      </div>
      
      <div class="header-actions">
        <el-button-group>
          <el-button 
            type="primary" 
            icon="el-icon-upload"
            @click="showImportDialog = true"
          >
            数据导入
          </el-button>
          <el-button 
            type="success" 
            icon="el-icon-download"
            @click="showExportDialog = true"
          >
            数据导出
          </el-button>
          <el-button 
            icon="el-icon-s-operation"
            @click="showTemplateManager = true"
          >
            模板管理
          </el-button>
          <el-button 
            icon="el-icon-view"
            @click="showProcessMonitor = true"
          >
            进程监控
          </el-button>
        </el-button-group>
      </div>
    </div>

    <!-- 主要内容区域 -->
    <el-tabs v-model="activeTab" type="card" class="processing-tabs">
      <!-- 导入管理 -->
      <el-tab-pane label="数据导入" name="import">
        <div class="import-section">
          <!-- 导入任务列表 -->
          <div class="task-list">
            <div class="list-header">
              <h3>导入任务</h3>
              <div class="list-controls">
                <el-select 
                  v-model="importFilters.status" 
                  placeholder="状态筛选" 
                  clearable
                  style="width: 120px"
                  @change="loadImportTasks"
                >
                  <el-option label="待处理" value="pending" />
                  <el-option label="处理中" value="processing" />
                  <el-option label="已完成" value="completed" />
                  <el-option label="失败" value="failed" />
                </el-select>
                <el-button 
                  icon="el-icon-refresh" 
                  @click="loadImportTasks"
                >
                  刷新
                </el-button>
              </div>
            </div>
            
            <el-table 
              :data="importTasks" 
              :loading="importLoading"
              stripe
              style="margin-top: 16px"
            >
              <el-table-column prop="fileName" label="文件名" min-width="200" show-overflow-tooltip />
              <el-table-column prop="fileType" label="文件类型" width="100">
                <template #default="{ row }">
                  <el-tag :type="getFileTypeTag(row.fileType)" size="small">
                    {{ row.fileType.toUpperCase() }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column prop="totalRecords" label="总记录数" width="100" align="center" />
              <el-table-column prop="processedRecords" label="已处理" width="100" align="center" />
              <el-table-column prop="successRecords" label="成功" width="80" align="center" />
              <el-table-column prop="errorRecords" label="错误" width="80" align="center" />
              <el-table-column prop="status" label="状态" width="100">
                <template #default="{ row }">
                  <el-tag :type="getStatusTagType(row.status)" size="small">
                    {{ getStatusText(row.status) }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column prop="progress" label="进度" width="150">
                <template #default="{ row }">
                  <el-progress 
                    v-if="row.status === 'processing'"
                    :percentage="row.progress"
                    :stroke-width="6"
                    :show-text="true"
                  />
                  <span v-else>{{ row.progress }}%</span>
                </template>
              </el-table-column>
              <el-table-column prop="createdAt" label="创建时间" width="180">
                <template #default="{ row }">
                  {{ formatDateTime(row.createdAt) }}
                </template>
              </el-table-column>
              <el-table-column label="操作" width="180" fixed="right">
                <template #default="{ row }">
                  <el-button-group size="small">
                    <el-button @click="viewTaskDetail(row)">详情</el-button>
                    <el-button 
                      v-if="row.status === 'failed'" 
                      type="warning" 
                      @click="retryTask(row)"
                    >
                      重试
                    </el-button>
                    <el-button 
                      v-if="row.errorRecords > 0" 
                      type="danger" 
                      @click="downloadErrors(row)"
                    >
                      错误
                    </el-button>
                    <el-button 
                      v-if="['completed', 'failed'].includes(row.status)" 
                      @click="deleteTask(row)"
                    >
                      删除
                    </el-button>
                  </el-button-group>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>

      <!-- 导出管理 -->
      <el-tab-pane label="数据导出" name="export">
        <div class="export-section">
          <!-- 导出任务列表 -->
          <div class="task-list">
            <div class="list-header">
              <h3>导出任务</h3>
              <div class="list-controls">
                <el-select 
                  v-model="exportFilters.status" 
                  placeholder="状态筛选" 
                  clearable
                  style="width: 120px"
                  @change="loadExportTasks"
                >
                  <el-option label="待处理" value="pending" />
                  <el-option label="处理中" value="processing" />
                  <el-option label="已完成" value="completed" />
                  <el-option label="失败" value="failed" />
                </el-select>
                <el-button 
                  icon="el-icon-refresh" 
                  @click="loadExportTasks"
                >
                  刷新
                </el-button>
              </div>
            </div>
            
            <el-table 
              :data="exportTasks" 
              :loading="exportLoading"
              stripe
              style="margin-top: 16px"
            >
              <el-table-column prop="taskName" label="任务名称" min-width="200" />
              <el-table-column prop="exportType" label="导出类型" width="100">
                <template #default="{ row }">
                  <el-tag :type="getExportTypeTag(row.exportType)" size="small">
                    {{ getExportTypeText(row.exportType) }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column prop="recordCount" label="记录数" width="100" align="center" />
              <el-table-column prop="fileSize" label="文件大小" width="100">
                <template #default="{ row }">
                  {{ formatFileSize(row.fileSize) }}
                </template>
              </el-table-column>
              <el-table-column prop="status" label="状态" width="100">
                <template #default="{ row }">
                  <el-tag :type="getStatusTagType(row.status)" size="small">
                    {{ getStatusText(row.status) }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column prop="progress" label="进度" width="150">
                <template #default="{ row }">
                  <el-progress 
                    v-if="row.status === 'processing'"
                    :percentage="row.progress"
                    :stroke-width="6"
                  />
                  <span v-else>{{ row.progress }}%</span>
                </template>
              </el-table-column>
              <el-table-column prop="createdAt" label="创建时间" width="180">
                <template #default="{ row }">
                  {{ formatDateTime(row.createdAt) }}
                </template>
              </el-table-column>
              <el-table-column label="操作" width="180" fixed="right">
                <template #default="{ row }">
                  <el-button-group size="small">
                    <el-button @click="viewExportDetail(row)">详情</el-button>
                    <el-button 
                      v-if="row.status === 'completed'" 
                      type="success" 
                      @click="downloadExportFile(row)"
                    >
                      下载
                    </el-button>
                    <el-button 
                      v-if="row.status === 'failed'" 
                      type="warning" 
                      @click="retryExportTask(row)"
                    >
                      重试
                    </el-button>
                    <el-button @click="deleteExportTask(row)">删除</el-button>
                  </el-button-group>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>

      <!-- 模板管理 -->
      <el-tab-pane label="模板管理" name="templates">
        <DataTemplateManager 
          :templates="dataTemplates"
          @template-created="handleTemplateCreated"
          @template-updated="handleTemplateUpdated"
          @template-deleted="handleTemplateDeleted"
        />
      </el-tab-pane>

      <!-- 处理日志 -->
      <el-tab-pane label="处理日志" name="logs">
        <DataProcessingLogs 
          :logs="processingLogs"
          @log-cleared="loadProcessingLogs"
        />
      </el-tab-pane>
    </el-tabs>

    <!-- 数据导入对话框 -->
    <el-dialog
      v-model="showImportDialog"
      title="数据导入"
      width="800px"
      :close-on-click-modal="false"
    >
      <DataImportWizard
        :templates="dataTemplates"
        @import-started="handleImportStarted"
        @dialog-close="showImportDialog = false"
      />
    </el-dialog>

    <!-- 数据导出对话框 -->
    <el-dialog
      v-model="showExportDialog"
      title="数据导出"
      width="800px"
      :close-on-click-modal="false"
    >
      <DataExportWizard
        :templates="dataTemplates"
        @export-started="handleExportStarted"
        @dialog-close="showExportDialog = false"
      />
    </el-dialog>

    <!-- 模板管理对话框 -->
    <el-dialog
      v-model="showTemplateManager"
      title="数据模板管理"
      width="900px"
    >
      <DataTemplateEditor
        :templates="dataTemplates"
        @template-saved="handleTemplateSaved"
      />
    </el-dialog>

    <!-- 进程监控对话框 -->
    <el-dialog
      v-model="showProcessMonitor"
      title="数据处理监控"
      width="1000px"
      top="5vh"
    >
      <DataProcessMonitor
        :import-tasks="importTasks"
        :export-tasks="exportTasks"
        @task-action="handleTaskAction"
      />
    </el-dialog>

    <!-- 任务详情对话框 -->
    <el-dialog
      v-model="showTaskDetail"
      :title="selectedTask ? `任务详情 - ${selectedTask.fileName || selectedTask.taskName}` : '任务详情'"
      width="700px"
    >
      <TaskDetailView
        v-if="selectedTask"
        :task="selectedTask"
        @task-updated="loadTasks"
      />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import DataImportWizard from './components/DataImportWizard.vue'
import DataExportWizard from './components/DataExportWizard.vue'
import DataTemplateManager from './components/DataTemplateManager.vue'
import DataTemplateEditor from './components/DataTemplateEditor.vue'
import DataProcessMonitor from './components/DataProcessMonitor.vue'
import DataProcessingLogs from './components/DataProcessingLogs.vue'
import TaskDetailView from './components/TaskDetailView.vue'

// 接口定义
interface ImportTask {
  id: string
  fileName: string
  fileType: string
  fileSize: number
  totalRecords: number
  processedRecords: number
  successRecords: number
  errorRecords: number
  status: 'pending' | 'processing' | 'completed' | 'failed'
  progress: number
  createdAt: Date
  completedAt?: Date
  errorMessage?: string
}

interface ExportTask {
  id: string
  taskName: string
  exportType: string
  recordCount: number
  fileSize: number
  status: 'pending' | 'processing' | 'completed' | 'failed'
  progress: number
  downloadUrl?: string
  createdAt: Date
  completedAt?: Date
}

interface DataTemplate {
  id: string
  name: string
  type: 'import' | 'export'
  fileFormat: string
  fieldMappings: any[]
  validationRules: any[]
  transformRules: any[]
}

// 组件属性
interface Props {
  config?: any
  autoRefresh?: boolean
  refreshInterval?: number
}

const props = withDefaults(defineProps<Props>(), {
  autoRefresh: true,
  refreshInterval: 5000
})

// 组件事件
const emit = defineEmits<{
  taskCompleted: [task: ImportTask | ExportTask]
  taskFailed: [task: ImportTask | ExportTask]
  configChanged: [config: any]
}>()

// 响应式数据
const config = ref({
  title: '{{DataProcessingName}}',
  maxConcurrentTasks: 5,
  chunkSize: 1000,
  timeoutSeconds: 300
})

const activeTab = ref('import')
const importLoading = ref(false)
const exportLoading = ref(false)

// 对话框状态
const showImportDialog = ref(false)
const showExportDialog = ref(false)
const showTemplateManager = ref(false)
const showProcessMonitor = ref(false)
const showTaskDetail = ref(false)

// 筛选条件
const importFilters = ref({ status: '' })
const exportFilters = ref({ status: '' })

// 数据列表
const importTasks = ref<ImportTask[]>([
  {
    id: '1',
    fileName: 'users_data_2025_09_23.xlsx',
    fileType: 'xlsx',
    fileSize: 2048576, // 2MB
    totalRecords: 10000,
    processedRecords: 8500,
    successRecords: 8200,
    errorRecords: 300,
    status: 'processing',
    progress: 85,
    createdAt: new Date(Date.now() - 30 * 60000) // 30分钟前
  },
  {
    id: '2',
    fileName: 'products_catalog.csv',
    fileType: 'csv',
    fileSize: 1048576, // 1MB
    totalRecords: 5000,
    processedRecords: 5000,
    successRecords: 4950,
    errorRecords: 50,
    status: 'completed',
    progress: 100,
    createdAt: new Date(Date.now() - 2 * 60 * 60000), // 2小时前
    completedAt: new Date(Date.now() - 90 * 60000) // 90分钟前
  }
])

const exportTasks = ref<ExportTask[]>([
  {
    id: '1',
    taskName: '用户数据导出',
    exportType: 'xlsx',
    recordCount: 15000,
    fileSize: 3145728, // 3MB
    status: 'completed',
    progress: 100,
    downloadUrl: '/api/exports/download/1',
    createdAt: new Date(Date.now() - 4 * 60 * 60000), // 4小时前
    completedAt: new Date(Date.now() - 3.5 * 60 * 60000) // 3.5小时前
  }
])

const dataTemplates = ref<DataTemplate[]>([])
const processingLogs = ref([])
const selectedTask = ref<ImportTask | ExportTask | null>(null)

// 统计数据
const statistics = computed(() => {
  const allTasks = [...importTasks.value, ...exportTasks.value]
  const pending = allTasks.filter(t => t.status === 'pending').length
  const processing = allTasks.filter(t => t.status === 'processing').length
  const completed = allTasks.filter(t => t.status === 'completed').length
  const total = allTasks.length
  
  return {
    pending,
    processing,
    completed,
    successRate: total > 0 ? Math.round((completed / total) * 100) : 0
  }
})

// 自动刷新定时器
const refreshTimer = ref<number | null>(null)

// 方法
const formatDateTime = (date: Date) => {
  return date.toLocaleString('zh-CN')
}

const formatFileSize = (bytes: number) => {
  const sizes = ['B', 'KB', 'MB', 'GB']
  if (bytes === 0) return '0B'
  const i = Math.floor(Math.log(bytes) / Math.log(1024))
  return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + sizes[i]
}

const getFileTypeTag = (fileType: string) => {
  const tags: Record<string, string> = {
    'xlsx': 'success',
    'csv': 'primary',
    'json': 'warning',
    'xml': 'info'
  }
  return tags[fileType.toLowerCase()] || 'default'
}

const getStatusTagType = (status: string) => {
  const types: Record<string, string> = {
    'pending': 'info',
    'processing': 'warning',
    'completed': 'success',
    'failed': 'danger'
  }
  return types[status] || 'default'
}

const getStatusText = (status: string) => {
  const texts: Record<string, string> = {
    'pending': '待处理',
    'processing': '处理中',
    'completed': '已完成',
    'failed': '失败'
  }
  return texts[status] || status
}

const getExportTypeTag = (exportType: string) => {
  return getFileTypeTag(exportType)
}

const getExportTypeText = (exportType: string) => {
  const texts: Record<string, string> = {
    'xlsx': 'Excel',
    'csv': 'CSV',
    'json': 'JSON',
    'xml': 'XML',
    'pdf': 'PDF'
  }
  return texts[exportType.toLowerCase()] || exportType.toUpperCase()
}

const loadImportTasks = async () => {
  importLoading.value = true
  try {
    // 模拟API调用
    await new Promise(resolve => setTimeout(resolve, 800))
    // 应用筛选
    if (importFilters.value.status) {
      // 筛选逻辑
    }
  } catch (error) {
    ElMessage.error('加载导入任务失败')
  } finally {
    importLoading.value = false
  }
}

const loadExportTasks = async () => {
  exportLoading.value = true
  try {
    // 模拟API调用
    await new Promise(resolve => setTimeout(resolve, 800))
    // 应用筛选
    if (exportFilters.value.status) {
      // 筛选逻辑
    }
  } catch (error) {
    ElMessage.error('加载导出任务失败')
  } finally {
    exportLoading.value = false
  }
}

const loadTasks = () => {
  loadImportTasks()
  loadExportTasks()
}

const loadProcessingLogs = async () => {
  // 模拟加载处理日志
  processingLogs.value = []
}

const viewTaskDetail = (task: ImportTask | ExportTask) => {
  selectedTask.value = task
  showTaskDetail.value = true
}

const viewExportDetail = (task: ExportTask) => {
  selectedTask.value = task
  showTaskDetail.value = true
}

const retryTask = async (task: ImportTask) => {
  try {
    await ElMessageBox.confirm('确认重试此导入任务？', '重试确认', {
      type: 'warning'
    })
    
    // 调用重试API
    await retryImportTask(task.id)
    
    ElMessage.success('任务重试成功')
    loadImportTasks()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('任务重试失败')
    }
  }
}

const retryExportTask = async (task: ExportTask) => {
  try {
    await ElMessageBox.confirm('确认重试此导出任务？', '重试确认', {
      type: 'warning'
    })
    
    // 调用重试API
    await retryExportTaskApi(task.id)
    
    ElMessage.success('任务重试成功')
    loadExportTasks()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('任务重试失败')
    }
  }
}

const downloadErrors = (task: ImportTask) => {
  // 下载错误记录
  const url = `/api/import/tasks/${task.id}/errors`
  window.open(url, '_blank')
}

const downloadExportFile = (task: ExportTask) => {
  if (task.downloadUrl) {
    window.open(task.downloadUrl, '_blank')
  }
}

const deleteTask = async (task: ImportTask) => {
  try {
    await ElMessageBox.confirm('确认删除此任务？删除后无法恢复。', '删除确认', {
      type: 'danger'
    })
    
    // 调用删除API
    await deleteImportTask(task.id)
    
    ElMessage.success('任务删除成功')
    loadImportTasks()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('任务删除失败')
    }
  }
}

const deleteExportTask = async (task: ExportTask) => {
  try {
    await ElMessageBox.confirm('确认删除此任务？删除后无法恢复。', '删除确认', {
      type: 'danger'
    })
    
    // 调用删除API
    await deleteExportTaskApi(task.id)
    
    ElMessage.success('任务删除成功')
    loadExportTasks()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('任务删除失败')
    }
  }
}

const handleImportStarted = (task: ImportTask) => {
  showImportDialog.value = false
  importTasks.value.unshift(task)
  ElMessage.success('导入任务已创建')
}

const handleExportStarted = (task: ExportTask) => {
  showExportDialog.value = false
  exportTasks.value.unshift(task)
  ElMessage.success('导出任务已创建')
}

const handleTemplateCreated = (template: DataTemplate) => {
  dataTemplates.value.push(template)
  ElMessage.success('模板创建成功')
}

const handleTemplateUpdated = (template: DataTemplate) => {
  const index = dataTemplates.value.findIndex(t => t.id === template.id)
  if (index > -1) {
    dataTemplates.value[index] = template
  }
  ElMessage.success('模板更新成功')
}

const handleTemplateDeleted = (templateId: string) => {
  const index = dataTemplates.value.findIndex(t => t.id === templateId)
  if (index > -1) {
    dataTemplates.value.splice(index, 1)
  }
  ElMessage.success('模板删除成功')
}

const handleTemplateSaved = (template: DataTemplate) => {
  const index = dataTemplates.value.findIndex(t => t.id === template.id)
  if (index > -1) {
    dataTemplates.value[index] = template
  } else {
    dataTemplates.value.push(template)
  }
}

const handleTaskAction = (action: string, task: any) => {
  switch (action) {
    case 'retry':
      if (task.fileName) {
        retryTask(task)
      } else {
        retryExportTask(task)
      }
      break
    case 'delete':
      if (task.fileName) {
        deleteTask(task)
      } else {
        deleteExportTask(task)
      }
      break
    case 'download':
      if (task.downloadUrl) {
        downloadExportFile(task)
      }
      break
  }
}

const startAutoRefresh = () => {
  if (props.autoRefresh) {
    refreshTimer.value = window.setInterval(() => {
      loadTasks()
    }, props.refreshInterval)
  }
}

const stopAutoRefresh = () => {
  if (refreshTimer.value) {
    clearInterval(refreshTimer.value)
    refreshTimer.value = null
  }
}

// API调用模拟函数
const retryImportTask = async (taskId: string) => {
  return new Promise(resolve => setTimeout(resolve, 1000))
}

const retryExportTaskApi = async (taskId: string) => {
  return new Promise(resolve => setTimeout(resolve, 1000))
}

const deleteImportTask = async (taskId: string) => {
  return new Promise(resolve => setTimeout(resolve, 500))
}

const deleteExportTaskApi = async (taskId: string) => {
  return new Promise(resolve => setTimeout(resolve, 500))
}

// 生命周期
onMounted(() => {
  loadTasks()
  loadProcessingLogs()
  startAutoRefresh()
})

onBeforeUnmount(() => {
  stopAutoRefresh()
})
</script>

<style scoped>
.data-import-export {
  padding: 20px;
  background: #f5f5f5;
  min-height: 100vh;
}

.data-processing-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
  padding: 24px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.header-info h2 {
  margin: 0 0 16px 0;
  font-size: 24px;
  color: #303133;
}

.process-stats {
  display: flex;
  gap: 32px;
}

.stat-item {
  text-align: center;
}

.stat-label {
  display: block;
  font-size: 12px;
  color: #909399;
  margin-bottom: 4px;
}

.stat-value {
  display: block;
  font-size: 20px;
  font-weight: 600;
  color: #303133;
}

.processing-tabs {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.import-section,
.export-section {
  padding: 20px;
}

.task-list {
  margin-bottom: 20px;
}

.list-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.list-header h3 {
  margin: 0;
  font-size: 18px;
  color: #303133;
}

.list-controls {
  display: flex;
  align-items: center;
  gap: 12px;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .data-import-export {
    padding: 12px;
  }
  
  .data-processing-header {
    flex-direction: column;
    gap: 16px;
    padding: 20px;
  }
  
  .process-stats {
    gap: 20px;
    flex-wrap: wrap;
  }
  
  .list-header {
    flex-direction: column;
    align-items: stretch;
    gap: 12px;
  }
}
</style>
