<!--
{{RolePermissionName}}角色权限管理
企业级角色权限管理组件，支持层级权限、批量授权、权限继承
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="role-permission-manager">
    <!-- 头部信息 -->
    <div class="manager-header">
      <h2>{{ config.title }}</h2>
      <el-button-group>
        <el-button type="primary" icon="el-icon-plus" @click="showCreateRole = true">
          新建角色
        </el-button>
        <el-button icon="el-icon-s-grid" @click="showBatchAssign = true">
          批量授权
        </el-button>
        <el-button icon="el-icon-download" @click="exportPermissions">
          导出权限
        </el-button>
      </el-button-group>
    </div>

    <el-row :gutter="20">
      <!-- 角色列表 -->
      <el-col :span="8">
        <el-card title="角色管理" class="role-card">
          <el-tree
            :data="roleTree"
            :props="{ label: 'name', children: 'children' }"
            node-key="id"
            :highlight-current="true"
            @node-click="selectRole"
          >
            <template #default="{ data }">
              <div class="role-node">
                <span>{{ data.name }}</span>
                <el-tag size="small" type="info">{{ data.userCount }}</el-tag>
              </div>
            </template>
          </el-tree>
        </el-card>
      </el-col>

      <!-- 权限分配 -->
      <el-col :span="16">
        <el-card v-if="selectedRole" :title="`权限分配 - ${selectedRole.name}`" class="permission-card">
          <el-tree
            ref="permissionTree"
            :data="permissionTree"
            :props="{ label: 'name', children: 'children' }"
            node-key="id"
            show-checkbox
            :default-checked-keys="selectedRole.permissions"
            @check="handlePermissionChange"
          >
            <template #default="{ data }">
              <div class="permission-node">
                <i :class="data.icon" />
                <span>{{ data.name }}</span>
                <el-tag v-if="data.type" size="small">{{ data.type }}</el-tag>
              </div>
            </template>
          </el-tree>
          
          <div class="permission-actions">
            <el-button type="success" @click="savePermissions">保存权限</el-button>
            <el-button @click="resetPermissions">重置</el-button>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 创建角色对话框 -->
    <el-dialog v-model="showCreateRole" title="创建角色" width="500px">
      <RoleEditor @role-created="handleRoleCreated" />
    </el-dialog>

    <!-- 批量授权对话框 -->
    <el-dialog v-model="showBatchAssign" title="批量授权" width="700px">
      <BatchPermissionAssign @batch-assigned="handleBatchAssigned" />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import RoleEditor from './components/RoleEditor.vue'
import BatchPermissionAssign from './components/BatchPermissionAssign.vue'

// 响应式数据
const config = ref({ title: '{{RolePermissionName}}' })
const showCreateRole = ref(false)
const showBatchAssign = ref(false)
const selectedRole = ref<any>(null)

const roleTree = ref([
  { id: 1, name: '超级管理员', userCount: 2, permissions: [1, 2, 3, 4, 5] },
  { id: 2, name: '管理员', userCount: 8, permissions: [2, 3, 4] },
  { id: 3, name: '普通用户', userCount: 156, permissions: [4] }
])

const permissionTree = ref([
  {
    id: 1,
    name: '系统管理',
    icon: 'el-icon-setting',
    children: [
      { id: 2, name: '用户管理', icon: 'el-icon-user', type: 'menu' },
      { id: 3, name: '角色管理', icon: 'el-icon-s-custom', type: 'menu' }
    ]
  },
  {
    id: 4,
    name: '业务模块',
    icon: 'el-icon-s-cooperation',
    children: [
      { id: 5, name: '订单管理', icon: 'el-icon-s-order', type: 'menu' }
    ]
  }
])

// 方法
const selectRole = (role: any) => {
  selectedRole.value = role
}

const handlePermissionChange = () => {
  // 处理权限变更
}

const savePermissions = () => {
  ElMessage.success('权限保存成功')
}

const resetPermissions = () => {
  // 重置权限
}

const exportPermissions = () => {
  ElMessage.success('权限导出成功')
}

const handleRoleCreated = () => {
  showCreateRole.value = false
  // 刷新角色列表
}

const handleBatchAssigned = () => {
  showBatchAssign.value = false
  // 刷新权限
}

onMounted(() => {
  // 初始化数据
})
</script>

<style scoped>
.role-permission-manager {
  padding: 20px;
}

.manager-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.role-node,
.permission-node {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  justify-content: space-between;
}

.permission-actions {
  margin-top: 20px;
  text-align: center;
}

.role-card,
.permission-card {
  height: 600px;
}
</style>
