// <auto-generated />
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using TenantManagement.SmartTenant.Dtos;

namespace TenantManagement.SmartTenant.Services
{
    public interface ISmartTenantAppService : IApplicationService
    {
        Task<List<SmartTenantDto>> GetListAsync();
    }

    public class SmartTenantAppService : ApplicationService, ISmartTenantAppService
    {
        public async Task<List<SmartTenantDto>> GetListAsync()
        {
            // TODO: Implement service logic
            return new List<SmartTenantDto>();
        }
    }
}