// <auto-generated />
using Volo.Abp;
using Volo.Abp.Modularity;

namespace TenantManagement.SmartTenant
{
    [DependsOn]
    public class SmartTenantModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            // TODO: Configure module services
        }
    }
}