<!--
{{NotificationName}}通知中心
企业级消息通知管理中心，支持多渠道消息推送、消息模板、批量发送
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="notification-center">
    <!-- 通知中心头部 -->
    <div class="notification-header">
      <div class="header-info">
        <h2>{{ notificationConfig.title }}</h2>
        <div class="header-stats">
          <div class="stat-item">
            <span class="stat-label">待发送</span>
            <span class="stat-value">{{ statistics.pending }}</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">已发送</span>
            <span class="stat-value">{{ statistics.sent }}</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">发送成功率</span>
            <span class="stat-value">{{ statistics.successRate }}%</span>
          </div>
        </div>
      </div>
      
      <div class="header-actions">
        <el-button 
          type="primary" 
          icon="el-icon-plus"
          @click="showCreateNotification = true"
        >
          创建通知
        </el-button>
        <el-button 
          icon="el-icon-s-operation"
          @click="showBatchSend = true"
        >
          批量发送
        </el-button>
        <el-button 
          icon="el-icon-setting"
          @click="showSettings = true"
        >
          设置
        </el-button>
      </div>
    </div>

    <!-- 通知管理选项卡 -->
    <el-tabs v-model="activeTab" type="card" class="notification-tabs">
      <!-- 通知列表 -->
      <el-tab-pane label="通知列表" name="list">
        <div class="notification-list-section">
          <!-- 筛选和搜索 -->
          <div class="list-controls">
            <div class="filters">
              <el-select 
                v-model="filters.status" 
                placeholder="状态" 
                clearable
                style="width: 120px"
                @change="handleFilterChange"
              >
                <el-option label="草稿" value="draft" />
                <el-option label="待发送" value="pending" />
                <el-option label="发送中" value="sending" />
                <el-option label="已发送" value="sent" />
                <el-option label="发送失败" value="failed" />
              </el-select>
              
              <el-select 
                v-model="filters.type" 
                placeholder="类型" 
                clearable
                style="width: 120px; margin-left: 8px"
                @change="handleFilterChange"
              >
                <el-option label="系统通知" value="system" />
                <el-option label="邮件" value="email" />
                <el-option label="短信" value="sms" />
                <el-option label="推送" value="push" />
                <el-option label="微信" value="wechat" />
              </el-select>
              
              <el-date-picker
                v-model="filters.dateRange"
                type="datetimerange"
                range-separator="至"
                start-placeholder="开始时间"
                end-placeholder="结束时间"
                style="margin-left: 8px"
                @change="handleFilterChange"
              />
            </div>
            
            <div class="search-box">
              <el-input
                v-model="searchKeyword"
                placeholder="搜索通知标题或内容..."
                style="width: 300px"
                @input="handleSearch"
              >
                <template #prefix>
                  <el-icon><Search /></el-icon>
                </template>
              </el-input>
            </div>
          </div>

          <!-- 通知表格 -->
          <div class="notification-table">
            <el-table
              :data="notificationList"
              :loading="loading"
              stripe
              @selection-change="handleSelectionChange"
              @sort-change="handleSort"
            >
              <el-table-column type="selection" width="55" />
              
              <el-table-column prop="title" label="标题" min-width="200" show-overflow-tooltip>
                <template #default="{ row }">
                  <div class="notification-title">
                    <i :class="getNotificationIcon(row.type)" />
                    <span>{{ row.title }}</span>
                    <el-tag 
                      v-if="row.priority === 'high'" 
                      type="danger" 
                      size="small"
                    >
                      紧急
                    </el-tag>
                  </div>
                </template>
              </el-table-column>
              
              <el-table-column prop="type" label="类型" width="100">
                <template #default="{ row }">
                  <el-tag :type="getTypeTagType(row.type)" size="small">
                    {{ getTypeText(row.type) }}
                  </el-tag>
                </template>
              </el-table-column>
              
              <el-table-column prop="targetCount" label="目标用户" width="100" align="center">
                <template #default="{ row }">
                  <span class="target-count">{{ row.targetCount }}</span>
                </template>
              </el-table-column>
              
              <el-table-column prop="status" label="状态" width="100">
                <template #default="{ row }">
                  <el-tag :type="getStatusTagType(row.status)" size="small">
                    {{ getStatusText(row.status) }}
                  </el-tag>
                </template>
              </el-table-column>
              
              <el-table-column prop="sentCount" label="已发送" width="80" align="center">
                <template #default="{ row }">
                  <span v-if="row.status !== 'draft'">{{ row.sentCount }}</span>
                  <span v-else>-</span>
                </template>
              </el-table-column>
              
              <el-table-column prop="successRate" label="成功率" width="80" align="center">
                <template #default="{ row }">
                  <span 
                    v-if="row.status === 'sent'" 
                    :class="{ 'success-rate-low': row.successRate < 90 }"
                  >
                    {{ row.successRate }}%
                  </span>
                  <span v-else>-</span>
                </template>
              </el-table-column>
              
              <el-table-column prop="scheduledAt" label="发送时间" width="180" sortable>
                <template #default="{ row }">
                  <span>{{ formatDateTime(row.scheduledAt) }}</span>
                </template>
              </el-table-column>
              
              <el-table-column label="操作" width="200" fixed="right">
                <template #default="{ row }">
                  <el-button-group size="small">
                    <el-button @click="handleView(row)">查看</el-button>
                    <el-button 
                      v-if="row.status === 'draft'" 
                      type="primary" 
                      @click="handleEdit(row)"
                    >
                      编辑
                    </el-button>
                    <el-button 
                      v-if="canSend(row)" 
                      type="success" 
                      @click="handleSend(row)"
                    >
                      发送
                    </el-button>
                    <el-button 
                      v-if="canCancel(row)" 
                      type="warning" 
                      @click="handleCancel(row)"
                    >
                      取消
                    </el-button>
                    <el-button 
                      v-if="row.status !== 'sending'" 
                      type="danger" 
                      @click="handleDelete(row)"
                    >
                      删除
                    </el-button>
                  </el-button-group>
                </template>
              </el-table-column>
            </el-table>
          </div>
          
          <!-- 分页 -->
          <div class="pagination-container">
            <el-pagination
              v-model:current-page="pagination.page"
              v-model:page-size="pagination.size"
              :total="pagination.total"
              :page-sizes="[10, 20, 50, 100]"
              layout="total, sizes, prev, pager, next, jumper"
              @current-change="handlePageChange"
              @size-change="handleSizeChange"
            />
          </div>
        </div>
      </el-tab-pane>

      <!-- 消息模板 -->
      <el-tab-pane label="消息模板" name="templates">
        <NotificationTemplateManager 
          :templates="templates"
          @template-created="handleTemplateCreated"
          @template-updated="handleTemplateUpdated"
          @template-deleted="handleTemplateDeleted"
        />
      </el-tab-pane>

      <!-- 发送统计 -->
      <el-tab-pane label="发送统计" name="statistics">
        <NotificationStatistics 
          :stats-data="statisticsData"
          @date-range-change="handleStatsDateChange"
        />
      </el-tab-pane>

      <!-- 用户群组 -->
      <el-tab-pane label="用户群组" name="groups">
        <UserGroupManager 
          :groups="userGroups"
          @group-created="handleGroupCreated"
          @group-updated="handleGroupUpdated"
          @group-deleted="handleGroupDeleted"
        />
      </el-tab-pane>
    </el-tabs>

    <!-- 创建通知对话框 -->
    <el-dialog
      v-model="showCreateNotification"
      title="创建通知"
      width="800px"
      :close-on-click-modal="false"
    >
      <NotificationEditor
        ref="notificationEditor"
        :templates="templates"
        :user-groups="userGroups"
        @notification-created="handleNotificationCreated"
      />
    </el-dialog>

    <!-- 批量发送对话框 -->
    <el-dialog
      v-model="showBatchSend"
      title="批量发送"
      width="600px"
    >
      <div class="batch-send-container">
        <el-alert
          :title="`已选择 ${selectedNotifications.length} 条通知`"
          type="info"
          :closable="false"
          style="margin-bottom: 20px"
        />
        
        <el-form :model="batchSendForm" label-width="100px">
          <el-form-item label="发送时间">
            <el-radio-group v-model="batchSendForm.sendType">
              <el-radio label="now">立即发送</el-radio>
              <el-radio label="scheduled">定时发送</el-radio>
            </el-radio-group>
          </el-form-item>
          
          <el-form-item v-if="batchSendForm.sendType === 'scheduled'" label="发送时间">
            <el-date-picker
              v-model="batchSendForm.scheduledTime"
              type="datetime"
              placeholder="选择发送时间"
              :disabled-date="disablePastDates"
            />
          </el-form-item>
          
          <el-form-item label="发送顺序">
            <el-radio-group v-model="batchSendForm.order">
              <el-radio label="priority">按优先级</el-radio>
              <el-radio label="time">按创建时间</el-radio>
            </el-radio-group>
          </el-form-item>
        </el-form>
      </div>
      
      <template #footer>
        <el-button @click="showBatchSend = false">取消</el-button>
        <el-button 
          type="primary" 
          :loading="batchSending"
          @click="handleBatchSend"
        >
          确认发送
        </el-button>
      </template>
    </el-dialog>

    <!-- 通知详情对话框 -->
    <el-dialog
      v-model="showNotificationDetail"
      title="通知详情"
      width="800px"
    >
      <NotificationDetail
        v-if="selectedNotification"
        :notification="selectedNotification"
        @resend="handleResend"
      />
    </el-dialog>

    <!-- 通知设置对话框 -->
    <el-dialog
      v-model="showSettings"
      title="通知设置"
      width="700px"
    >
      <el-tabs>
        <el-tab-pane label="发送配置" name="send">
          <NotificationSendConfig v-model="notificationConfig.send" />
        </el-tab-pane>
        <el-tab-pane label="渠道配置" name="channels">
          <NotificationChannelConfig v-model="notificationConfig.channels" />
        </el-tab-pane>
        <el-tab-pane label="权限设置" name="permissions">
          <NotificationPermissionConfig v-model="notificationConfig.permissions" />
        </el-tab-pane>
      </el-tabs>
      <template #footer>
        <el-button @click="showSettings = false">取消</el-button>
        <el-button type="primary" @click="saveSettings">保存设置</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import NotificationEditor from './components/NotificationEditor.vue'
import NotificationDetail from './components/NotificationDetail.vue'
import NotificationTemplateManager from './components/NotificationTemplateManager.vue'
import NotificationStatistics from './components/NotificationStatistics.vue'
import UserGroupManager from './components/UserGroupManager.vue'
import NotificationSendConfig from './components/NotificationSendConfig.vue'
import NotificationChannelConfig from './components/NotificationChannelConfig.vue'
import NotificationPermissionConfig from './components/NotificationPermissionConfig.vue'

// 接口定义
interface Notification {
  id: string
  title: string
  content: string
  type: 'system' | 'email' | 'sms' | 'push' | 'wechat'
  status: 'draft' | 'pending' | 'sending' | 'sent' | 'failed'
  priority: 'low' | 'normal' | 'high'
  targetCount: number
  sentCount: number
  successRate: number
  scheduledAt: Date
  createdAt: Date
  createdBy: string
}

interface NotificationTemplate {
  id: string
  name: string
  type: string
  title: string
  content: string
  variables: string[]
}

interface UserGroup {
  id: string
  name: string
  description: string
  userCount: number
  conditions: any[]
}

// 组件属性
interface Props {
  config?: any
}

const props = withDefaults(defineProps<Props>(), {
  config: () => ({})
})

// 组件事件
const emit = defineEmits<{
  configChanged: [config: any]
  notificationSent: [notification: Notification]
}>()

// 响应式数据
const notificationConfig = ref({
  title: '{{NotificationName}}',
  send: {},
  channels: {},
  permissions: {}
})

const activeTab = ref('list')
const loading = ref(false)
const batchSending = ref(false)

// 对话框状态
const showCreateNotification = ref(false)
const showBatchSend = ref(false)
const showNotificationDetail = ref(false)
const showSettings = ref(false)

// 筛选和搜索
const filters = ref({
  status: '',
  type: '',
  dateRange: []
})
const searchKeyword = ref('')

// 通知列表数据
const notificationList = ref<Notification[]>([
  {
    id: '1',
    title: '系统维护通知',
    content: '系统将于今晚22:00-24:00进行维护升级...',
    type: 'system',
    status: 'sent',
    priority: 'high',
    targetCount: 1250,
    sentCount: 1248,
    successRate: 99.8,
    scheduledAt: new Date('2025-09-23 20:00:00'),
    createdAt: new Date('2025-09-23 18:30:00'),
    createdBy: '管理员'
  },
  {
    id: '2',
    title: '新功能发布提醒',
    content: '我们很高兴地宣布新功能正式发布...',
    type: 'email',
    status: 'pending',
    priority: 'normal',
    targetCount: 5600,
    sentCount: 0,
    successRate: 0,
    scheduledAt: new Date('2025-09-24 09:00:00'),
    createdAt: new Date('2025-09-23 16:45:00'),
    createdBy: '产品经理'
  }
])

const selectedNotifications = ref<Notification[]>([])
const selectedNotification = ref<Notification | null>(null)

// 分页
const pagination = ref({
  page: 1,
  size: 20,
  total: 0
})

// 统计数据
const statistics = ref({
  pending: 23,
  sent: 1567,
  successRate: 98.5
})

// 模板和用户组
const templates = ref<NotificationTemplate[]>([])
const userGroups = ref<UserGroup[]>([])
const statisticsData = ref({})

// 批量发送表单
const batchSendForm = ref({
  sendType: 'now',
  scheduledTime: null,
  order: 'priority'
})

// 计算属性
const canBatchSend = computed(() => {
  return selectedNotifications.value.length > 0 &&
         selectedNotifications.value.every(n => canSend(n))
})

// 方法
const formatDateTime = (date: Date | string) => {
  return new Date(date).toLocaleString('zh-CN')
}

const getNotificationIcon = (type: string) => {
  const icons: Record<string, string> = {
    'system': 'el-icon-bell',
    'email': 'el-icon-message',
    'sms': 'el-icon-chat-dot-round',
    'push': 'el-icon-notification',
    'wechat': 'el-icon-chat-line-round'
  }
  return icons[type] || 'el-icon-bell'
}

const getTypeTagType = (type: string) => {
  const types: Record<string, string> = {
    'system': 'info',
    'email': 'primary',
    'sms': 'warning',
    'push': 'success',
    'wechat': 'success'
  }
  return types[type] || 'info'
}

const getTypeText = (type: string) => {
  const texts: Record<string, string> = {
    'system': '系统',
    'email': '邮件',
    'sms': '短信',
    'push': '推送',
    'wechat': '微信'
  }
  return texts[type] || type
}

const getStatusTagType = (status: string) => {
  const types: Record<string, string> = {
    'draft': 'info',
    'pending': 'warning',
    'sending': 'primary',
    'sent': 'success',
    'failed': 'danger'
  }
  return types[status] || 'info'
}

const getStatusText = (status: string) => {
  const texts: Record<string, string> = {
    'draft': '草稿',
    'pending': '待发送',
    'sending': '发送中',
    'sent': '已发送',
    'failed': '发送失败'
  }
  return texts[status] || status
}

const canSend = (notification: Notification) => {
  return ['draft', 'failed'].includes(notification.status)
}

const canCancel = (notification: Notification) => {
  return notification.status === 'pending'
}

const disablePastDates = (date: Date) => {
  return date < new Date()
}

const handleFilterChange = () => {
  loadNotifications()
}

const handleSearch = () => {
  pagination.value.page = 1
  loadNotifications()
}

const handleSelectionChange = (selection: Notification[]) => {
  selectedNotifications.value = selection
}

const handleSort = (sort: any) => {
  // 实现排序逻辑
  console.log('排序:', sort)
}

const handlePageChange = (page: number) => {
  pagination.value.page = page
  loadNotifications()
}

const handleSizeChange = (size: number) => {
  pagination.value.size = size
  pagination.value.page = 1
  loadNotifications()
}

const handleView = (notification: Notification) => {
  selectedNotification.value = notification
  showNotificationDetail.value = true
}

const handleEdit = (notification: Notification) => {
  // 实现编辑逻辑
  console.log('编辑通知:', notification)
}

const handleSend = async (notification: Notification) => {
  try {
    await ElMessageBox.confirm('确认立即发送此通知？', '发送确认', {
      type: 'warning'
    })
    
    // 调用发送API
    await sendNotification(notification.id)
    
    ElMessage.success('通知发送成功')
    emit('notificationSent', notification)
    loadNotifications()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('通知发送失败')
    }
  }
}

const handleCancel = async (notification: Notification) => {
  try {
    await ElMessageBox.confirm('确认取消发送此通知？', '取消确认', {
      type: 'warning'
    })
    
    // 调用取消API
    await cancelNotification(notification.id)
    
    ElMessage.success('已取消发送')
    loadNotifications()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('取消失败')
    }
  }
}

const handleDelete = async (notification: Notification) => {
  try {
    await ElMessageBox.confirm('确认删除此通知？删除后无法恢复。', '删除确认', {
      type: 'danger'
    })
    
    // 调用删除API
    await deleteNotification(notification.id)
    
    ElMessage.success('通知已删除')
    loadNotifications()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('删除失败')
    }
  }
}

const handleBatchSend = async () => {
  batchSending.value = true
  
  try {
    const sendParams = {
      notifications: selectedNotifications.value.map(n => n.id),
      sendType: batchSendForm.value.sendType,
      scheduledTime: batchSendForm.value.scheduledTime,
      order: batchSendForm.value.order
    }
    
    // 调用批量发送API
    await batchSendNotifications(sendParams)
    
    ElMessage.success(`成功发送 ${selectedNotifications.value.length} 条通知`)
    showBatchSend.value = false
    selectedNotifications.value = []
    loadNotifications()
    
  } catch (error) {
    ElMessage.error('批量发送失败')
  } finally {
    batchSending.value = false
  }
}

const handleResend = (notification: Notification) => {
  handleSend(notification)
}

const handleNotificationCreated = (notification: Notification) => {
  showCreateNotification.value = false
  loadNotifications()
  ElMessage.success('通知创建成功')
}

const handleTemplateCreated = (template: NotificationTemplate) => {
  templates.value.push(template)
  ElMessage.success('模板创建成功')
}

const handleTemplateUpdated = (template: NotificationTemplate) => {
  const index = templates.value.findIndex(t => t.id === template.id)
  if (index > -1) {
    templates.value[index] = template
  }
  ElMessage.success('模板更新成功')
}

const handleTemplateDeleted = (templateId: string) => {
  const index = templates.value.findIndex(t => t.id === templateId)
  if (index > -1) {
    templates.value.splice(index, 1)
  }
  ElMessage.success('模板删除成功')
}

const handleGroupCreated = (group: UserGroup) => {
  userGroups.value.push(group)
  ElMessage.success('用户群组创建成功')
}

const handleGroupUpdated = (group: UserGroup) => {
  const index = userGroups.value.findIndex(g => g.id === group.id)
  if (index > -1) {
    userGroups.value[index] = group
  }
  ElMessage.success('用户群组更新成功')
}

const handleGroupDeleted = (groupId: string) => {
  const index = userGroups.value.findIndex(g => g.id === groupId)
  if (index > -1) {
    userGroups.value.splice(index, 1)
  }
  ElMessage.success('用户群组删除成功')
}

const handleStatsDateChange = (dateRange: [Date, Date]) => {
  // 处理统计数据日期范围变化
  loadStatistics(dateRange)
}

const saveSettings = () => {
  emit('configChanged', notificationConfig.value)
  showSettings.value = false
  ElMessage.success('设置保存成功')
}

// API调用模拟函数
const loadNotifications = async () => {
  loading.value = true
  try {
    // 模拟API调用
    await new Promise(resolve => setTimeout(resolve, 800))
    
    // 应用筛选和搜索
    let filteredList = [...notificationList.value]
    
    if (filters.value.status) {
      filteredList = filteredList.filter(n => n.status === filters.value.status)
    }
    
    if (filters.value.type) {
      filteredList = filteredList.filter(n => n.type === filters.value.type)
    }
    
    if (searchKeyword.value) {
      const keyword = searchKeyword.value.toLowerCase()
      filteredList = filteredList.filter(n => 
        n.title.toLowerCase().includes(keyword) ||
        n.content.toLowerCase().includes(keyword)
      )
    }
    
    pagination.value.total = filteredList.length
    
  } catch (error) {
    ElMessage.error('加载通知列表失败')
  } finally {
    loading.value = false
  }
}

const loadTemplates = async () => {
  // 模拟加载模板数据
  templates.value = [
    {
      id: '1',
      name: '系统维护通知模板',
      type: 'system',
      title: '系统维护通知',
      content: '尊敬的用户，系统将于{{date}}进行维护，预计耗时{{duration}}，给您带来不便敬请谅解。',
      variables: ['date', 'duration']
    }
  ]
}

const loadUserGroups = async () => {
  // 模拟加载用户组数据
  userGroups.value = [
    {
      id: '1',
      name: '全体用户',
      description: '系统中所有注册用户',
      userCount: 12456,
      conditions: []
    },
    {
      id: '2',
      name: 'VIP用户',
      description: 'VIP等级用户',
      userCount: 856,
      conditions: [{ field: 'userLevel', operator: 'eq', value: 'vip' }]
    }
  ]
}

const loadStatistics = async (dateRange?: [Date, Date]) => {
  // 模拟加载统计数据
  statisticsData.value = {
    totalSent: 15670,
    successRate: 98.5,
    failureReasons: {},
    channelStats: {},
    timeStats: {}
  }
}

const sendNotification = async (notificationId: string) => {
  // 模拟发送通知API
  return new Promise(resolve => setTimeout(resolve, 2000))
}

const cancelNotification = async (notificationId: string) => {
  // 模拟取消通知API
  return new Promise(resolve => setTimeout(resolve, 1000))
}

const deleteNotification = async (notificationId: string) => {
  // 模拟删除通知API
  return new Promise(resolve => setTimeout(resolve, 500))
}

const batchSendNotifications = async (params: any) => {
  // 模拟批量发送API
  return new Promise(resolve => setTimeout(resolve, 3000))
}

// 生命周期
onMounted(() => {
  loadNotifications()
  loadTemplates()
  loadUserGroups()
  loadStatistics()
})
</script>

<style scoped>
.notification-center {
  padding: 20px;
  background: #f5f5f5;
  min-height: 100vh;
}

.notification-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
  padding: 24px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.header-info h2 {
  margin: 0 0 16px 0;
  font-size: 24px;
  color: #303133;
}

.header-stats {
  display: flex;
  gap: 32px;
}

.stat-item {
  text-align: center;
}

.stat-label {
  display: block;
  font-size: 12px;
  color: #909399;
  margin-bottom: 4px;
}

.stat-value {
  display: block;
  font-size: 20px;
  font-weight: 600;
  color: #303133;
}

.notification-tabs {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.notification-list-section {
  padding: 20px;
}

.list-controls {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  flex-wrap: wrap;
  gap: 16px;
}

.filters {
  display: flex;
  align-items: center;
}

.notification-table {
  margin-bottom: 20px;
}

.notification-title {
  display: flex;
  align-items: center;
  gap: 8px;
}

.notification-title i {
  color: #409eff;
}

.target-count {
  font-weight: 500;
  color: #606266;
}

.success-rate-low {
  color: #f56c6c;
  font-weight: 600;
}

.pagination-container {
  display: flex;
  justify-content: center;
  padding: 16px;
}

.batch-send-container {
  padding: 16px 0;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .notification-center {
    padding: 12px;
  }
  
  .notification-header {
    flex-direction: column;
    gap: 16px;
    padding: 20px;
  }
  
  .header-stats {
    gap: 20px;
  }
  
  .list-controls {
    flex-direction: column;
    align-items: stretch;
  }
  
  .filters {
    flex-wrap: wrap;
    gap: 8px;
  }
}
</style>
