<!--
{{ConfigManagerName}}配置管理系统
企业级配置管理组件，支持分布式配置、版本控制、实时生效
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="config-manager">
    <!-- 配置管理工具栏 -->
    <div class="manager-toolbar">
      <div class="toolbar-left">
        <el-button type="primary" @click="createConfig">
          <i class="el-icon-plus" />
          新建配置
        </el-button>
        <el-button @click="importConfigs">
          <i class="el-icon-upload" />
          批量导入
        </el-button>
        <el-button @click="exportConfigs">
          <i class="el-icon-download" />
          批量导出
        </el-button>
      </div>
      
      <div class="toolbar-right">
        <el-select v-model="selectedEnvironment" placeholder="选择环境">
          <el-option
            v-for="env in environments"
            :key="env.value"
            :label="env.label"
            :value="env.value"
          />
        </el-select>
        <el-input
          v-model="searchKeyword"
          placeholder="搜索配置项"
          style="width: 200px"
          clearable
        >
          <template #prefix>
            <i class="el-icon-search" />
          </template>
        </el-input>
      </div>
    </div>

    <!-- 配置分类树 -->
    <div class="config-content">
      <div class="config-sidebar">
        <el-tree
          :data="configCategories"
          :props="{ children: 'children', label: 'label' }"
          node-key="key"
          default-expand-all
          @node-click="onCategorySelect"
        />
      </div>

      <div class="config-main">
        <!-- 配置表格 -->
        <el-table
          :data="filteredConfigs"
          stripe
          @selection-change="onSelectionChange"
        >
          <el-table-column type="selection" width="55" />
          <el-table-column prop="key" label="配置键" width="200" sortable>
            <template #default="{ row }">
              <el-tag size="small" type="info">{{ row.category }}</el-tag>
              <div>{{ row.key }}</div>
            </template>
          </el-table-column>
          <el-table-column prop="value" label="配置值" min-width="200">
            <template #default="{ row }">
              <div v-if="row.type === 'json'" class="json-value">
                <pre>{{ JSON.stringify(row.value, null, 2) }}</pre>
              </div>
              <el-tag v-else-if="row.type === 'boolean'" :type="row.value ? 'success' : 'danger'">
                {{ row.value ? 'true' : 'false' }}
              </el-tag>
              <span v-else>{{ row.value }}</span>
            </template>
          </el-table-column>
          <el-table-column prop="type" label="类型" width="100">
            <template #default="{ row }">
              <el-tag size="small" :type="getTypeTagColor(row.type)">
                {{ row.type }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="environment" label="环境" width="100">
            <template #default="{ row }">
              <el-tag size="small" :type="getEnvTagColor(row.environment)">
                {{ row.environment }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="lastModified" label="修改时间" width="160">
            <template #default="{ row }">
              {{ formatTime(row.lastModified) }}
            </template>
          </el-table-column>
          <el-table-column label="操作" width="180" fixed="right">
            <template #default="{ row }">
              <el-button size="small" @click="editConfig(row)">编辑</el-button>
              <el-button size="small" @click="viewHistory(row)">历史</el-button>
              <el-button
                size="small"
                type="danger"
                @click="deleteConfig(row)"
              >
                删除
              </el-button>
            </template>
          </el-table-column>
        </el-table>

        <!-- 分页 -->
        <el-pagination
          v-model:current-page="currentPage"
          v-model:page-size="pageSize"
          :total="totalConfigs"
          :page-sizes="[10, 20, 50, 100]"
          layout="total, sizes, prev, pager, next, jumper"
          @size-change="onPageSizeChange"
          @current-change="onPageChange"
        />
      </div>
    </div>

    <!-- 配置编辑对话框 -->
    <el-dialog
      v-model="editDialogVisible"
      :title="isEdit ? '编辑配置' : '新建配置'"
      width="700px"
      @close="resetForm"
    >
      <el-form
        ref="configForm"
        :model="configForm"
        :rules="formRules"
        label-width="100px"
      >
        <el-form-item label="配置分类" prop="category">
          <el-select v-model="configForm.category" placeholder="选择分类">
            <el-option
              v-for="cat in flatCategories"
              :key="cat.key"
              :label="cat.label"
              :value="cat.key"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="配置键" prop="key">
          <el-input v-model="configForm.key" placeholder="输入配置键" />
        </el-form-item>

        <el-form-item label="数据类型" prop="type">
          <el-select v-model="configForm.type" @change="onTypeChange">
            <el-option label="字符串" value="string" />
            <el-option label="数字" value="number" />
            <el-option label="布尔值" value="boolean" />
            <el-option label="JSON对象" value="json" />
          </el-select>
        </el-form-item>

        <el-form-item label="配置值" prop="value">
          <el-input
            v-if="configForm.type === 'string'"
            v-model="configForm.value"
            type="textarea"
            :rows="4"
            placeholder="输入字符串值"
          />
          <el-input-number
            v-else-if="configForm.type === 'number'"
            v-model="configForm.value"
            style="width: 100%"
          />
          <el-switch
            v-else-if="configForm.type === 'boolean'"
            v-model="configForm.value"
          />
          <el-input
            v-else-if="configForm.type === 'json'"
            v-model="configForm.jsonValue"
            type="textarea"
            :rows="6"
            placeholder="输入JSON对象"
          />
        </el-form-item>

        <el-form-item label="环境" prop="environment">
          <el-select v-model="configForm.environment" placeholder="选择环境">
            <el-option
              v-for="env in environments"
              :key="env.value"
              :label="env.label"
              :value="env.value"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="描述" prop="description">
          <el-input
            v-model="configForm.description"
            type="textarea"
            :rows="3"
            placeholder="输入配置描述"
          />
        </el-form-item>
      </el-form>

      <template #footer>
        <span class="dialog-footer">
          <el-button @click="editDialogVisible = false">取消</el-button>
          <el-button type="primary" @click="saveConfig">确定</el-button>
        </span>
      </template>
    </el-dialog>

    <!-- 历史版本对话框 -->
    <el-dialog
      v-model="historyDialogVisible"
      title="配置历史"
      width="800px"
    >
      <el-table :data="configHistory" stripe>
        <el-table-column prop="version" label="版本" width="80" />
        <el-table-column prop="value" label="配置值" min-width="200">
          <template #default="{ row }">
            <pre v-if="row.type === 'json'">{{ JSON.stringify(row.value, null, 2) }}</pre>
            <span v-else>{{ row.value }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="modifiedBy" label="修改人" width="120" />
        <el-table-column prop="modifiedTime" label="修改时间" width="160">
          <template #default="{ row }">
            {{ formatTime(row.modifiedTime) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="100">
          <template #default="{ row }">
            <el-button size="small" @click="rollbackConfig(row)">
              回滚
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

// 响应式数据
const selectedEnvironment = ref('dev')
const searchKeyword = ref('')
const currentPage = ref(1)
const pageSize = ref(20)
const selectedConfigs = ref([])
const editDialogVisible = ref(false)
const historyDialogVisible = ref(false)
const isEdit = ref(false)

const environments = [
  { label: '开发环境', value: 'dev' },
  { label: '测试环境', value: 'test' },
  { label: '预发环境', value: 'staging' },
  { label: '生产环境', value: 'prod' }
]

const configCategories = ref([
  {
    label: '系统配置',
    key: 'system',
    children: [
      { label: '数据库', key: 'system.database' },
      { label: '缓存', key: 'system.cache' },
      { label: '消息队列', key: 'system.mq' }
    ]
  },
  {
    label: '业务配置',
    key: 'business',
    children: [
      { label: '用户管理', key: 'business.user' },
      { label: '权限管理', key: 'business.permission' },
      { label: '订单管理', key: 'business.order' }
    ]
  }
])

const configs = ref([
  {
    id: 1,
    key: 'database.connection.timeout',
    value: 30000,
    type: 'number',
    category: 'system.database',
    environment: 'dev',
    description: '数据库连接超时时间',
    lastModified: new Date()
  },
  {
    id: 2,
    key: 'cache.redis.enabled',
    value: true,
    type: 'boolean',
    category: 'system.cache',
    environment: 'dev',
    description: '是否启用Redis缓存',
    lastModified: new Date()
  }
])

const configHistory = ref([])

// 表单数据
const configForm = reactive({
  category: '',
  key: '',
  value: '',
  jsonValue: '',
  type: 'string',
  environment: 'dev',
  description: ''
})

const formRules = {
  category: [{ required: true, message: '请选择配置分类', trigger: 'change' }],
  key: [{ required: true, message: '请输入配置键', trigger: 'blur' }],
  type: [{ required: true, message: '请选择数据类型', trigger: 'change' }],
  environment: [{ required: true, message: '请选择环境', trigger: 'change' }]
}

// 计算属性
const filteredConfigs = computed(() => {
  let result = configs.value

  if (selectedEnvironment.value) {
    result = result.filter(config => config.environment === selectedEnvironment.value)
  }

  if (searchKeyword.value) {
    const keyword = searchKeyword.value.toLowerCase()
    result = result.filter(config =>
      config.key.toLowerCase().includes(keyword) ||
      config.description.toLowerCase().includes(keyword)
    )
  }

  return result
})

const totalConfigs = computed(() => filteredConfigs.value.length)

const flatCategories = computed(() => {
  const result = []
  const flatten = (items) => {
    items.forEach(item => {
      result.push({ key: item.key, label: item.label })
      if (item.children) {
        flatten(item.children)
      }
    })
  }
  flatten(configCategories.value)
  return result
})

// 方法
const formatTime = (time: Date) => {
  return time.toLocaleString('zh-CN')
}

const getTypeTagColor = (type: string) => {
  const colorMap = {
    string: '',
    number: 'success',
    boolean: 'warning',
    json: 'info'
  }
  return colorMap[type] || ''
}

const getEnvTagColor = (env: string) => {
  const colorMap = {
    dev: 'info',
    test: 'warning',
    staging: 'danger',
    prod: 'success'
  }
  return colorMap[env] || ''
}

const onCategorySelect = (data: any) => {
  // 按分类过滤配置
}

const onSelectionChange = (selection: any[]) => {
  selectedConfigs.value = selection
}

const onPageSizeChange = (size: number) => {
  pageSize.value = size
}

const onPageChange = (page: number) => {
  currentPage.value = page
}

const createConfig = () => {
  isEdit.value = false
  resetForm()
  editDialogVisible.value = true
}

const editConfig = (config: any) => {
  isEdit.value = true
  Object.assign(configForm, config)
  if (config.type === 'json') {
    configForm.jsonValue = JSON.stringify(config.value, null, 2)
  }
  editDialogVisible.value = true
}

const deleteConfig = async (config: any) => {
  try {
    await ElMessageBox.confirm('确定要删除这个配置项吗？', '警告', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    
    // 执行删除逻辑
    ElMessage.success('配置删除成功')
  } catch {
    // 用户取消
  }
}

const viewHistory = (config: any) => {
  // 获取配置历史
  configHistory.value = [
    {
      version: 'v1.0.2',
      value: config.value,
      modifiedBy: '张三',
      modifiedTime: new Date()
    }
  ]
  historyDialogVisible.value = true
}

const rollbackConfig = (historyItem: any) => {
  ElMessage.success('配置回滚成功')
  historyDialogVisible.value = false
}

const onTypeChange = () => {
  configForm.value = ''
  configForm.jsonValue = ''
}

const saveConfig = () => {
  // 保存配置逻辑
  if (configForm.type === 'json') {
    try {
      configForm.value = JSON.parse(configForm.jsonValue)
    } catch {
      ElMessage.error('JSON格式不正确')
      return
    }
  }

  ElMessage.success('配置保存成功')
  editDialogVisible.value = false
}

const resetForm = () => {
  Object.assign(configForm, {
    category: '',
    key: '',
    value: '',
    jsonValue: '',
    type: 'string',
    environment: 'dev',
    description: ''
  })
}

const importConfigs = () => {
  ElMessage.info('批量导入功能开发中...')
}

const exportConfigs = () => {
  ElMessage.info('批量导出功能开发中...')
}

// 生命周期
onMounted(() => {
  // 初始化数据
})
</script>

<style scoped>
.config-manager {
  padding: 20px;
}

.manager-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding: 16px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.toolbar-left {
  display: flex;
  gap: 12px;
}

.toolbar-right {
  display: flex;
  gap: 12px;
  align-items: center;
}

.config-content {
  display: flex;
  gap: 20px;
}

.config-sidebar {
  width: 250px;
  background: white;
  border-radius: 8px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.config-main {
  flex: 1;
  background: white;
  border-radius: 8px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.json-value pre {
  margin: 0;
  font-size: 12px;
  max-height: 100px;
  overflow: auto;
  background: #f5f7fa;
  padding: 8px;
  border-radius: 4px;
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}
</style>
