<!--
{{SystemMonitorName}}系统监控面板
企业级系统监控组件，支持实时性能监控、告警管理、日志查看
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="system-monitor">
    <!-- 监控概览 -->
    <div class="monitor-overview">
      <div class="overview-cards">
        <div class="metric-card cpu">
          <div class="metric-icon">
            <i class="el-icon-cpu" />
          </div>
          <div class="metric-info">
            <div class="metric-value">{{ systemMetrics.cpu }}%</div>
            <div class="metric-label">CPU使用率</div>
          </div>
        </div>

        <div class="metric-card memory">
          <div class="metric-icon">
            <i class="el-icon-s-data" />
          </div>
          <div class="metric-info">
            <div class="metric-value">{{ systemMetrics.memory }}%</div>
            <div class="metric-label">内存使用率</div>
          </div>
        </div>

        <div class="metric-card disk">
          <div class="metric-icon">
            <i class="el-icon-folder" />
          </div>
          <div class="metric-info">
            <div class="metric-value">{{ systemMetrics.disk }}%</div>
            <div class="metric-label">磁盘使用率</div>
          </div>
        </div>

        <div class="metric-card network">
          <div class="metric-icon">
            <i class="el-icon-connection" />
          </div>
          <div class="metric-info">
            <div class="metric-value">{{ systemMetrics.network }}</div>
            <div class="metric-label">网络连接</div>
          </div>
        </div>
      </div>
    </div>

    <el-tabs v-model="activeTab" type="card">
      <!-- 性能监控 -->
      <el-tab-pane label="性能监控" name="performance">
        <div class="performance-charts">
          <el-row :gutter="20">
            <el-col :span="12">
              <el-card title="CPU使用率">
                <div id="cpuChart" style="height: 300px"></div>
              </el-card>
            </el-col>
            <el-col :span="12">
              <el-card title="内存使用率">
                <div id="memoryChart" style="height: 300px"></div>
              </el-card>
            </el-col>
          </el-row>
        </div>
      </el-tab-pane>

      <!-- 服务状态 -->
      <el-tab-pane label="服务状态" name="services">
        <el-table :data="services" stripe>
          <el-table-column prop="name" label="服务名称" />
          <el-table-column prop="status" label="状态">
            <template #default="{ row }">
              <el-tag :type="row.status === 'running' ? 'success' : 'danger'">
                {{ row.status === 'running' ? '运行中' : '已停止' }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="cpu" label="CPU%" />
          <el-table-column prop="memory" label="内存%" />
          <el-table-column label="操作" width="120">
            <template #default="{ row }">
              <el-button size="small" @click="toggleService(row)">
                {{ row.status === 'running' ? '停止' : '启动' }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <!-- 告警日志 -->
      <el-tab-pane label="告警日志" name="alerts">
        <div class="alert-controls">
          <el-select v-model="alertFilter" placeholder="告警级别">
            <el-option label="全部" value="" />
            <el-option label="严重" value="critical" />
            <el-option label="警告" value="warning" />
            <el-option label="信息" value="info" />
          </el-select>
          <el-button @click="clearAlerts">清空告警</el-button>
        </div>
        
        <div class="alerts-list">
          <div
            v-for="alert in filteredAlerts"
            :key="alert.id"
            class="alert-item"
            :class="`alert-${alert.level}`"
          >
            <div class="alert-time">{{ formatTime(alert.time) }}</div>
            <div class="alert-message">{{ alert.message }}</div>
            <div class="alert-level">{{ alert.level }}</div>
          </div>
        </div>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { ElMessage } from 'element-plus'

// 响应式数据
const activeTab = ref('performance')
const alertFilter = ref('')

const systemMetrics = ref({
  cpu: 45,
  memory: 68,
  disk: 32,
  network: 1250
})

const services = ref([
  { name: 'Web服务', status: 'running', cpu: 15, memory: 25 },
  { name: '数据库', status: 'running', cpu: 30, memory: 45 },
  { name: '缓存服务', status: 'stopped', cpu: 0, memory: 0 }
])

const alerts = ref([
  {
    id: 1,
    time: new Date(Date.now() - 5 * 60000),
    message: 'CPU使用率超过80%',
    level: 'critical'
  },
  {
    id: 2,
    time: new Date(Date.now() - 15 * 60000),
    message: '磁盘空间不足',
    level: 'warning'
  }
])

// 计算属性
const filteredAlerts = computed(() => {
  if (!alertFilter.value) return alerts.value
  return alerts.value.filter(alert => alert.level === alertFilter.value)
})

// 方法
const formatTime = (time: Date) => {
  return time.toLocaleString('zh-CN')
}

const toggleService = (service: any) => {
  service.status = service.status === 'running' ? 'stopped' : 'running'
  ElMessage.success(`服务已${service.status === 'running' ? '启动' : '停止'}`)
}

const clearAlerts = () => {
  alerts.value = []
  ElMessage.success('告警日志已清空')
}

// 生命周期
onMounted(() => {
  // 初始化监控数据
})

onBeforeUnmount(() => {
  // 清理定时器
})
</script>

<style scoped>
.system-monitor {
  padding: 20px;
}

.monitor-overview {
  margin-bottom: 24px;
}

.overview-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
}

.metric-card {
  display: flex;
  align-items: center;
  padding: 24px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  transition: transform 0.3s;
}

.metric-card:hover {
  transform: translateY(-4px);
}

.metric-icon {
  width: 64px;
  height: 64px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  margin-right: 20px;
  font-size: 28px;
  color: white;
}

.cpu .metric-icon { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
.memory .metric-icon { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
.disk .metric-icon { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }
.network .metric-icon { background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); }

.metric-info {
  flex: 1;
}

.metric-value {
  font-size: 32px;
  font-weight: 700;
  color: #303133;
  margin-bottom: 4px;
}

.metric-label {
  font-size: 14px;
  color: #909399;
}

.performance-charts {
  margin-top: 20px;
}

.alert-controls {
  display: flex;
  gap: 16px;
  margin-bottom: 20px;
}

.alerts-list {
  max-height: 400px;
  overflow-y: auto;
}

.alert-item {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 12px 16px;
  margin-bottom: 8px;
  border-radius: 8px;
  background: white;
  border-left: 4px solid;
}

.alert-critical { border-left-color: #f56c6c; }
.alert-warning { border-left-color: #e6a23c; }
.alert-info { border-left-color: #409eff; }

.alert-time {
  flex-shrink: 0;
  font-size: 12px;
  color: #909399;
}

.alert-message {
  flex: 1;
  font-size: 14px;
  color: #303133;
}

.alert-level {
  flex-shrink: 0;
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
}
</style>
