// <auto-generated />
using System;
using Volo.Abp.Application.Dtos;

namespace TenantManagement.SmartTenant.Dtos
{
    /// <summary>
    /// 租户管理 DTO
    /// </summary>
    public class SmartTenantDto : EntityDto<Guid>
    {
        public Guid? Id { get; set; }
        public Guid? TenantId { get; set; }
        public string? Code { get; set; }
        public Guid? ParentId { get; set; }
        public bool? IsActive { get; set; }
        public string? Description { get; set; }
        public Guid? SubscriptionPlanId { get; set; }
        public DateTime? StartTime { get; set; }
        public int? MaxUserCount { get; set; }
        public int? MaxStorageSize { get; set; }
        public int? MaxApiCallsPerDay { get; set; }
        public string? ConnectionString { get; set; }
        public bool? IsIsolatedDatabase { get; set; }
        public string? FeatureConfig { get; set; }
        public string? CustomSettings { get; set; }
        public string? ExtraProperties { get; set; }
        public string? ConcurrencyStamp { get; set; }
        public DateTime? CreationTime { get; set; }
        public Guid? CreatorId { get; set; }
        public DateTime? LastModificationTime { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? DeletionTime { get; set; }
    }
}