// 设备 AppService
// Generated by SmartAbp DevKit

using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace .Application.Services
{
    public interface IEquipmentAppService : ICrudAppService<
        EquipmentDto,
        Guid,
        PagedAndSortedResultRequestDto,
        CreateEquipmentDto,
        UpdateEquipmentDto>
    {
    }

    public class EquipmentAppService : CrudAppService<
        Equipment,
        EquipmentDto,
        Guid,
        PagedAndSortedResultRequestDto,
        CreateEquipmentDto,
        UpdateEquipmentDto>, IEquipmentAppService
    {
        public EquipmentAppService(IEquipmentRepository repository)
            : base(repository)
        {
        }
    }
}