// 生产线 AppService
// Generated by SmartAbp DevKit

using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace .Application.Services
{
    public interface IProductionLineAppService : ICrudAppService<
        ProductionLineDto,
        Guid,
        PagedAndSortedResultRequestDto,
        CreateProductionLineDto,
        UpdateProductionLineDto>
    {
    }

    public class ProductionLineAppService : CrudAppService<
        ProductionLine,
        ProductionLineDto,
        Guid,
        PagedAndSortedResultRequestDto,
        CreateProductionLineDto,
        UpdateProductionLineDto>, IProductionLineAppService
    {
        public ProductionLineAppService(IProductionLineRepository repository)
            : base(repository)
        {
        }
    }
}