// 传感器数据 AppService
// Generated by SmartAbp DevKit

using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace .Application.Services
{
    public interface ISensorDataAppService : ICrudAppService<
        SensorDataDto,
        Guid,
        PagedAndSortedResultRequestDto,
        CreateSensorDataDto,
        UpdateSensorDataDto>
    {
    }

    public class SensorDataAppService : CrudAppService<
        SensorData,
        SensorDataDto,
        Guid,
        PagedAndSortedResultRequestDto,
        CreateSensorDataDto,
        UpdateSensorDataDto>, ISensorDataAppService
    {
        public SensorDataAppService(ISensorDataRepository repository)
            : base(repository)
        {
        }
    }
}