<!--
{{FormName}}高级表单组件
企业级表单组件，支持动态字段、条件显示、多步骤、自动保存
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="advanced-form">
    <el-form
      ref="formRef"
      :model="formData"
      :rules="formRules"
      :label-width="labelWidth"
      :disabled="readonly"
    >
      <!-- 多步骤表单头部 -->
      <div v-if="isMultiStep" class="form-steps">
        <el-steps :active="currentStep" finish-status="success">
          <el-step
            v-for="(step, index) in steps"
            :key="index"
            :title="step.title"
            :description="step.description"
          />
        </el-steps>
      </div>

      <!-- 表单字段 -->
      <div class="form-content">
        <template v-for="field in visibleFields" :key="field.name">
          <!-- 文本输入 -->
          <el-form-item
            v-if="field.type === 'input'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-input
              v-model="formData[field.name]"
              :placeholder="field.placeholder"
              :disabled="field.disabled"
              :maxlength="field.maxlength"
              :show-word-limit="field.showWordLimit"
              @blur="handleFieldBlur(field)"
              @change="handleFieldChange(field)"
            />
          </el-form-item>

          <!-- 数字输入 -->
          <el-form-item
            v-else-if="field.type === 'number'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-input-number
              v-model="formData[field.name]"
              :min="field.min"
              :max="field.max"
              :step="field.step"
              :precision="field.precision"
              :disabled="field.disabled"
              @change="handleFieldChange(field)"
            />
          </el-form-item>

          <!-- 选择器 -->
          <el-form-item
            v-else-if="field.type === 'select'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-select
              v-model="formData[field.name]"
              :placeholder="field.placeholder"
              :multiple="field.multiple"
              :filterable="field.filterable"
              :disabled="field.disabled"
              :loading="field.loading"
              @change="handleFieldChange(field)"
            >
              <el-option
                v-for="option in field.options"
                :key="option.value"
                :label="option.label"
                :value="option.value"
              />
            </el-select>
          </el-form-item>

          <!-- 日期选择器 -->
          <el-form-item
            v-else-if="field.type === 'date'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-date-picker
              v-model="formData[field.name]"
              :type="field.dateType || 'date'"
              :placeholder="field.placeholder"
              :disabled="field.disabled"
              :format="field.format"
              :value-format="field.valueFormat"
              @change="handleFieldChange(field)"
            />
          </el-form-item>

          <!-- 多行文本 -->
          <el-form-item
            v-else-if="field.type === 'textarea'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-input
              v-model="formData[field.name]"
              type="textarea"
              :rows="field.rows || 4"
              :placeholder="field.placeholder"
              :disabled="field.disabled"
              :maxlength="field.maxlength"
              :show-word-limit="field.showWordLimit"
              @change="handleFieldChange(field)"
            />
          </el-form-item>

          <!-- 开关 -->
          <el-form-item
            v-else-if="field.type === 'switch'"
            :prop="field.name"
            :label="field.label"
          >
            <el-switch
              v-model="formData[field.name]"
              :disabled="field.disabled"
              :active-text="field.activeText"
              :inactive-text="field.inactiveText"
              @change="handleFieldChange(field)"
            />
          </el-form-item>

          <!-- 复选框组 -->
          <el-form-item
            v-else-if="field.type === 'checkbox'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-checkbox-group
              v-model="formData[field.name]"
              :disabled="field.disabled"
              @change="handleFieldChange(field)"
            >
              <el-checkbox
                v-for="option in field.options"
                :key="option.value"
                :label="option.value"
              >
                {{ option.label }}
              </el-checkbox>
            </el-checkbox-group>
          </el-form-item>

          <!-- 单选框组 -->
          <el-form-item
            v-else-if="field.type === 'radio'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-radio-group
              v-model="formData[field.name]"
              :disabled="field.disabled"
              @change="handleFieldChange(field)"
            >
              <el-radio
                v-for="option in field.options"
                :key="option.value"
                :label="option.value"
              >
                {{ option.label }}
              </el-radio>
            </el-radio-group>
          </el-form-item>

          <!-- 文件上传 -->
          <el-form-item
            v-else-if="field.type === 'upload'"
            :prop="field.name"
            :label="field.label"
            :required="field.required"
          >
            <el-upload
              v-model:file-list="formData[field.name]"
              :action="field.action"
              :headers="field.headers"
              :multiple="field.multiple"
              :limit="field.limit"
              :accept="field.accept"
              :disabled="field.disabled"
              @success="(response, file, fileList) => handleUploadSuccess(field, response, file, fileList)"
              @error="(error, file, fileList) => handleUploadError(field, error, file, fileList)"
            >
              <el-button type="primary">点击上传</el-button>
              <template #tip>
                <div class="el-upload__tip">{{ field.tip }}</div>
              </template>
            </el-upload>
          </el-form-item>
        </template>
      </div>

      <!-- 表单操作按钮 -->
      <div class="form-actions">
        <template v-if="isMultiStep">
          <el-button v-if="currentStep > 0" @click="prevStep">上一步</el-button>
          <el-button v-if="currentStep < steps.length - 1" type="primary" @click="nextStep">
            下一步
          </el-button>
          <el-button v-else type="success" :loading="submitting" @click="handleSubmit">
            提交
          </el-button>
        </template>
        <template v-else>
          <slot name="actions">
            <el-button @click="handleReset">重置</el-button>
            <el-button v-if="showSave" @click="handleSave">保存</el-button>
            <el-button type="primary" :loading="submitting" @click="handleSubmit">
              {{ submitText }}
            </el-button>
          </slot>
        </template>
      </div>
    </el-form>

    <!-- 自动保存提示 -->
    <div v-if="autoSave && lastSaveTime" class="auto-save-info">
      <el-icon><DocumentCopy /></el-icon>
      <span>自动保存于 {{ formatTime(lastSaveTime) }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import { ElMessage } from 'element-plus'
import { DocumentCopy } from '@element-plus/icons-vue'

// 接口定义
interface FormField {
  name: string
  label: string
  type: string
  required?: boolean
  disabled?: boolean
  placeholder?: string
  options?: Array<{ label: string; value: any }>
  // ... 其他字段属性
  visibleWhen?: (formData: any) => boolean
  onChange?: (value: any, formData: any) => void
}

interface FormStep {
  title: string
  description?: string
  fields: string[]
}

// 组件属性
interface Props {
  fields: FormField[]
  initialData?: any
  rules?: any
  labelWidth?: string
  readonly?: boolean
  isMultiStep?: boolean
  steps?: FormStep[]
  autoSave?: boolean
  autoSaveInterval?: number
  showSave?: boolean
  submitText?: string
}

const props = withDefaults(defineProps<Props>(), {
  labelWidth: '120px',
  readonly: false,
  isMultiStep: false,
  autoSave: false,
  autoSaveInterval: 30000, // 30秒
  showSave: true,
  submitText: '提交'
})

// 组件事件
const emit = defineEmits<{
  submit: [data: any]
  save: [data: any]
  reset: []
  fieldChange: [field: FormField, value: any]
  stepChange: [step: number]
}>()

// 响应式数据
const formRef = ref()
const formData = ref<any>({})
const formRules = ref(props.rules || {})
const submitting = ref(false)
const currentStep = ref(0)
const lastSaveTime = ref<Date | null>(null)
const autoSaveTimer = ref<number | null>(null)

// 计算属性
const visibleFields = computed(() => {
  let fields = props.fields
  
  // 多步骤表单时，只显示当前步骤的字段
  if (props.isMultiStep && props.steps) {
    const currentStepFields = props.steps[currentStep.value]?.fields || []
    fields = fields.filter(field => currentStepFields.includes(field.name))
  }
  
  // 根据条件显示/隐藏字段
  return fields.filter(field => {
    if (field.visibleWhen) {
      return field.visibleWhen(formData.value)
    }
    return true
  })
})

// 初始化表单数据
const initFormData = () => {
  const data: any = {}
  props.fields.forEach(field => {
    data[field.name] = props.initialData?.[field.name] || getDefaultValue(field)
  })
  formData.value = data
}

const getDefaultValue = (field: FormField) => {
  switch (field.type) {
    case 'checkbox':
      return []
    case 'switch':
      return false
    case 'number':
      return 0
    default:
      return ''
  }
}

// 字段变更处理
const handleFieldChange = (field: FormField) => {
  const value = formData.value[field.name]
  
  // 触发字段变更回调
  if (field.onChange) {
    field.onChange(value, formData.value)
  }
  
  emit('fieldChange', field, value)
  
  // 触发自动保存
  if (props.autoSave) {
    scheduleAutoSave()
  }
}

const handleFieldBlur = (field: FormField) => {
  // 字段失焦处理
}

// 文件上传处理
const handleUploadSuccess = (field: FormField, response: any, file: any, fileList: any[]) => {
  ElMessage.success('文件上传成功')
  handleFieldChange(field)
}

const handleUploadError = (field: FormField, error: any, file: any, fileList: any[]) => {
  ElMessage.error('文件上传失败')
}

// 多步骤表单
const nextStep = async () => {
  if (await validateCurrentStep()) {
    if (currentStep.value < (props.steps?.length || 1) - 1) {
      currentStep.value++
      emit('stepChange', currentStep.value)
    }
  }
}

const prevStep = () => {
  if (currentStep.value > 0) {
    currentStep.value--
    emit('stepChange', currentStep.value)
  }
}

const validateCurrentStep = async () => {
  if (!formRef.value) return true
  
  try {
    // 只验证当前步骤的字段
    const currentStepFields = props.steps?.[currentStep.value]?.fields || []
    await formRef.value.validateField(currentStepFields)
    return true
  } catch {
    return false
  }
}

// 表单操作
const handleSubmit = async () => {
  if (!formRef.value) return
  
  try {
    await formRef.value.validate()
    submitting.value = true
    emit('submit', formData.value)
  } catch (error) {
    ElMessage.error('请检查表单输入')
  } finally {
    submitting.value = false
  }
}

const handleSave = () => {
  emit('save', formData.value)
  lastSaveTime.value = new Date()
}

const handleReset = () => {
  formRef.value?.resetFields()
  initFormData()
  currentStep.value = 0
  emit('reset')
}

// 自动保存
const scheduleAutoSave = () => {
  if (autoSaveTimer.value) {
    clearTimeout(autoSaveTimer.value)
  }
  
  autoSaveTimer.value = window.setTimeout(() => {
    handleSave()
  }, props.autoSaveInterval)
}

const formatTime = (time: Date) => {
  return time.toLocaleTimeString('zh-CN')
}

// 监听初始数据变化
watch(() => props.initialData, (newData) => {
  if (newData) {
    Object.assign(formData.value, newData)
  }
}, { deep: true, immediate: true })

// 生命周期
onMounted(() => {
  initFormData()
})

onBeforeUnmount(() => {
  if (autoSaveTimer.value) {
    clearTimeout(autoSaveTimer.value)
  }
})
</script>

<style scoped>
.advanced-form {
  background: white;
  border-radius: 8px;
  padding: 24px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.form-steps {
  margin-bottom: 32px;
}

.form-content {
  margin-bottom: 24px;
}

.form-actions {
  text-align: center;
  padding-top: 24px;
  border-top: 1px solid #ebeef5;
}

.form-actions .el-button {
  margin: 0 8px;
}

.auto-save-info {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 16px;
  padding: 8px 16px;
  background: #f0f9ff;
  border-radius: 4px;
  font-size: 12px;
  color: #409eff;
}
</style>
