<!--
{{ApiConnectorName}}API连接器
企业级API集成管理，支持多协议、认证方式、错误重试、监控告警
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="api-connector">
    <!-- API连接器头部 -->
    <div class="connector-header">
      <div class="header-info">
        <h2>{{ connectorConfig.name }}</h2>
        <div class="connection-status">
          <el-tag 
            :type="getConnectionStatusType(connectionStatus)" 
            size="large"
            effect="dark"
          >
            <i :class="getConnectionStatusIcon(connectionStatus)" />
            {{ getConnectionStatusText(connectionStatus) }}
          </el-tag>
          <span class="last-test">最后测试: {{ formatDateTime(lastTestTime) }}</span>
        </div>
        
        <div class="api-stats">
          <div class="stat-item">
            <span class="stat-label">今日请求</span>
            <span class="stat-value">{{ statistics.todayRequests }}</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">成功率</span>
            <span class="stat-value success-rate">{{ statistics.successRate }}%</span>
          </div>
          <div class="stat-item">
            <span class="stat-label">平均响应</span>
            <span class="stat-value">{{ statistics.averageResponse }}ms</span>
          </div>
        </div>
      </div>
      
      <div class="header-actions">
        <el-button-group>
          <el-button 
            :type="connectionStatus === 'connected' ? 'success' : 'primary'"
            :loading="testing"
            icon="el-icon-connection"
            @click="testConnection"
          >
            测试连接
          </el-button>
          <el-button 
            icon="el-icon-view"
            @click="showApiTester = true"
          >
            API测试器
          </el-button>
          <el-button 
            icon="el-icon-s-data"
            @click="showMonitoring = true"
          >
            监控面板
          </el-button>
          <el-button 
            icon="el-icon-setting"
            @click="showSettings = true"
          >
            连接设置
          </el-button>
        </el-button-group>
      </div>
    </div>

    <!-- 主要内容区域 -->
    <el-tabs v-model="activeTab" type="card" class="connector-tabs">
      <!-- API端点管理 -->
      <el-tab-pane label="API端点" name="endpoints">
        <div class="endpoints-section">
          <div class="endpoints-toolbar">
            <div class="toolbar-left">
              <el-input
                v-model="endpointSearch"
                placeholder="搜索API端点..."
                style="width: 300px"
                @input="searchEndpoints"
              >
                <template #prefix>
                  <el-icon><Search /></el-icon>
                </template>
              </el-input>
              <el-select 
                v-model="endpointFilters.method" 
                placeholder="请求方法" 
                clearable
                style="width: 120px; margin-left: 12px"
                @change="filterEndpoints"
              >
                <el-option label="GET" value="GET" />
                <el-option label="POST" value="POST" />
                <el-option label="PUT" value="PUT" />
                <el-option label="DELETE" value="DELETE" />
                <el-option label="PATCH" value="PATCH" />
              </el-select>
            </div>
            
            <div class="toolbar-right">
              <el-button 
                type="primary" 
                icon="el-icon-plus"
                @click="showEndpointEditor = true"
              >
                新增端点
              </el-button>
              <el-button 
                icon="el-icon-download"
                @click="importFromSwagger"
              >
                导入Swagger
              </el-button>
            </div>
          </div>

          <!-- API端点列表 -->
          <div class="endpoints-list">
            <div 
              v-for="endpoint in filteredEndpoints"
              :key="endpoint.id"
              class="endpoint-item"
              :class="{ 'endpoint-disabled': !endpoint.enabled }"
            >
              <div class="endpoint-header">
                <div class="endpoint-method">
                  <el-tag 
                    :type="getMethodTagType(endpoint.method)" 
                    size="small"
                  >
                    {{ endpoint.method }}
                  </el-tag>
                </div>
                <div class="endpoint-path">
                  <span class="path">{{ endpoint.path }}</span>
                  <span class="description">{{ endpoint.description }}</span>
                </div>
                <div class="endpoint-status">
                  <el-tag 
                    v-if="endpoint.lastTestResult"
                    :type="endpoint.lastTestResult.success ? 'success' : 'danger'"
                    size="small"
                  >
                    {{ endpoint.lastTestResult.success ? '正常' : '异常' }}
                  </el-tag>
                  <span v-if="endpoint.lastTestResult" class="response-time">
                    {{ endpoint.lastTestResult.responseTime }}ms
                  </span>
                </div>
                <div class="endpoint-actions">
                  <el-button-group size="small">
                    <el-button 
                      :loading="endpoint.testing"
                      @click="testEndpoint(endpoint)"
                    >
                      测试
                    </el-button>
                    <el-button @click="editEndpoint(endpoint)">编辑</el-button>
                    <el-dropdown @command="handleEndpointAction">
                      <el-button>
                        更多<el-icon><arrow-down /></el-icon>
                      </el-button>
                      <template #dropdown>
                        <el-dropdown-menu>
                          <el-dropdown-item :command="`copy-${endpoint.id}`">
                            复制链接
                          </el-dropdown-item>
                          <el-dropdown-item :command="`docs-${endpoint.id}`">
                            生成文档
                          </el-dropdown-item>
                          <el-dropdown-item :command="`history-${endpoint.id}`">
                            调用历史
                          </el-dropdown-item>
                          <el-dropdown-item 
                            :command="`toggle-${endpoint.id}`"
                            :divided="true"
                          >
                            {{ endpoint.enabled ? '禁用' : '启用' }}
                          </el-dropdown-item>
                          <el-dropdown-item 
                            :command="`delete-${endpoint.id}`"
                            class="danger-item"
                          >
                            删除
                          </el-dropdown-item>
                        </el-dropdown-menu>
                      </template>
                    </el-dropdown>
                  </el-button-group>
                </div>
              </div>
              
              <!-- 端点详细信息 -->
              <div v-if="endpoint.expanded" class="endpoint-details">
                <el-tabs type="border-card">
                  <el-tab-pane label="参数" name="params">
                    <ApiParameterList :parameters="endpoint.parameters" />
                  </el-tab-pane>
                  <el-tab-pane label="请求头" name="headers">
                    <ApiHeaderList :headers="endpoint.headers" />
                  </el-tab-pane>
                  <el-tab-pane label="响应" name="response">
                    <ApiResponseExample :example="endpoint.responseExample" />
                  </el-tab-pane>
                  <el-tab-pane label="错误码" name="errors">
                    <ApiErrorCodeList :error-codes="endpoint.errorCodes" />
                  </el-tab-pane>
                </el-tabs>
              </div>
            </div>
          </div>
        </div>
      </el-tab-pane>

      <!-- 请求日志 -->
      <el-tab-pane label="请求日志" name="logs">
        <div class="logs-section">
          <div class="logs-toolbar">
            <div class="toolbar-filters">
              <el-select 
                v-model="logFilters.level" 
                placeholder="日志级别" 
                clearable
                style="width: 120px"
                @change="filterLogs"
              >
                <el-option label="成功" value="success" />
                <el-option label="错误" value="error" />
                <el-option label="警告" value="warning" />
                <el-option label="信息" value="info" />
              </el-select>
              <el-date-picker
                v-model="logFilters.dateRange"
                type="datetimerange"
                range-separator="至"
                start-placeholder="开始时间"
                end-placeholder="结束时间"
                style="margin-left: 12px"
                @change="filterLogs"
              />
            </div>
            
            <div class="toolbar-actions">
              <el-button 
                icon="el-icon-refresh"
                @click="loadLogs"
              >
                刷新
              </el-button>
              <el-button 
                icon="el-icon-delete"
                @click="clearLogs"
              >
                清空日志
              </el-button>
              <el-button 
                icon="el-icon-download"
                @click="exportLogs"
              >
                导出日志
              </el-button>
            </div>
          </div>

          <!-- 日志列表 -->
          <div class="logs-list">
            <el-table 
              :data="requestLogs" 
              :loading="logsLoading"
              stripe
              height="400"
            >
              <el-table-column prop="timestamp" label="时间" width="180">
                <template #default="{ row }">
                  {{ formatDateTime(row.timestamp) }}
                </template>
              </el-table-column>
              <el-table-column prop="method" label="方法" width="80">
                <template #default="{ row }">
                  <el-tag :type="getMethodTagType(row.method)" size="small">
                    {{ row.method }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column prop="url" label="URL" min-width="300" show-overflow-tooltip />
              <el-table-column prop="statusCode" label="状态码" width="80">
                <template #default="{ row }">
                  <el-tag 
                    :type="getStatusCodeTagType(row.statusCode)" 
                    size="small"
                  >
                    {{ row.statusCode }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column prop="responseTime" label="响应时间" width="100" align="center">
                <template #default="{ row }">
                  {{ row.responseTime }}ms
                </template>
              </el-table-column>
              <el-table-column prop="level" label="级别" width="80">
                <template #default="{ row }">
                  <el-tag :type="getLogLevelTagType(row.level)" size="small">
                    {{ getLogLevelText(row.level) }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column label="操作" width="120" fixed="right">
                <template #default="{ row }">
                  <el-button size="small" @click="viewLogDetail(row)">
                    详情
                  </el-button>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>

      <!-- 性能监控 -->
      <el-tab-pane label="性能监控" name="performance">
        <ApiPerformanceMonitor 
          :endpoint-stats="endpointStats"
          :performance-metrics="performanceMetrics"
          @refresh="loadPerformanceData"
        />
      </el-tab-pane>

      <!-- 集成配置 -->
      <el-tab-pane label="集成配置" name="integration">
        <ApiIntegrationConfig 
          :config="integrationConfig"
          @config-updated="handleIntegrationConfigUpdate"
        />
      </el-tab-pane>
    </el-tabs>

    <!-- API测试器对话框 -->
    <el-dialog
      v-model="showApiTester"
      title="API测试器"
      width="900px"
      top="5vh"
    >
      <ApiTester
        :endpoints="apiEndpoints"
        :base-url="connectorConfig.baseUrl"
        :auth-config="connectorConfig.authentication"
        @test-completed="handleTestCompleted"
      />
    </el-dialog>

    <!-- 连接设置对话框 -->
    <el-dialog
      v-model="showSettings"
      title="连接设置"
      width="700px"
    >
      <ApiConnectionSettings
        :config="connectorConfig"
        @config-saved="handleConfigSaved"
      />
    </el-dialog>

    <!-- 端点编辑器对话框 -->
    <el-dialog
      v-model="showEndpointEditor"
      :title="editingEndpoint ? '编辑API端点' : '新增API端点'"
      width="800px"
      :close-on-click-modal="false"
    >
      <ApiEndpointEditor
        :endpoint="editingEndpoint"
        @endpoint-saved="handleEndpointSaved"
        @dialog-close="showEndpointEditor = false"
      />
    </el-dialog>

    <!-- 监控面板对话框 -->
    <el-dialog
      v-model="showMonitoring"
      title="API监控面板"
      width="1200px"
      top="5vh"
    >
      <ApiMonitoringDashboard
        :connector-id="connectorConfig.id"
        :real-time-data="realTimeMonitoringData"
      />
    </el-dialog>

    <!-- 日志详情对话框 -->
    <el-dialog
      v-model="showLogDetail"
      title="请求日志详情"
      width="800px"
    >
      <ApiLogDetail
        v-if="selectedLog"
        :log="selectedLog"
      />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search, ArrowDown } from '@element-plus/icons-vue'
import ApiTester from './components/ApiTester.vue'
import ApiConnectionSettings from './components/ApiConnectionSettings.vue'
import ApiEndpointEditor from './components/ApiEndpointEditor.vue'
import ApiMonitoringDashboard from './components/ApiMonitoringDashboard.vue'
import ApiPerformanceMonitor from './components/ApiPerformanceMonitor.vue'
import ApiIntegrationConfig from './components/ApiIntegrationConfig.vue'
import ApiParameterList from './components/ApiParameterList.vue'
import ApiHeaderList from './components/ApiHeaderList.vue'
import ApiResponseExample from './components/ApiResponseExample.vue'
import ApiErrorCodeList from './components/ApiErrorCodeList.vue'
import ApiLogDetail from './components/ApiLogDetail.vue'

// 接口定义
interface ApiEndpoint {
  id: string
  method: string
  path: string
  description: string
  enabled: boolean
  parameters: any[]
  headers: any[]
  responseExample: any
  errorCodes: any[]
  lastTestResult?: {
    success: boolean
    responseTime: number
    statusCode: number
  }
  testing?: boolean
  expanded?: boolean
}

interface RequestLog {
  id: string
  timestamp: Date
  method: string
  url: string
  statusCode: number
  responseTime: number
  level: 'success' | 'error' | 'warning' | 'info'
  requestHeaders: any
  requestBody: any
  responseHeaders: any
  responseBody: any
  errorMessage?: string
}

interface ConnectorConfig {
  id: string
  name: string
  baseUrl: string
  authentication: {
    type: 'none' | 'basic' | 'bearer' | 'oauth2' | 'api-key'
    config: any
  }
  timeout: number
  retryPolicy: {
    enabled: boolean
    maxRetries: number
    backoffStrategy: 'linear' | 'exponential'
  }
  rateLimiting: {
    enabled: boolean
    requestsPerSecond: number
  }
}

// 组件属性
interface Props {
  connectorId?: string
  config?: Partial<ConnectorConfig>
}

const props = withDefaults(defineProps<Props>(), {})

// 组件事件
const emit = defineEmits<{
  connectionStatusChanged: [status: string]
  configUpdated: [config: ConnectorConfig]
  endpointTested: [endpoint: ApiEndpoint, result: any]
}>()

// 响应式数据
const connectorConfig = ref<ConnectorConfig>({
  id: props.connectorId || '{{ApiConnectorId}}',
  name: '{{ApiConnectorName}}',
  baseUrl: 'https://api.example.com',
  authentication: {
    type: 'bearer',
    config: { token: '' }
  },
  timeout: 30000,
  retryPolicy: {
    enabled: true,
    maxRetries: 3,
    backoffStrategy: 'exponential'
  },
  rateLimiting: {
    enabled: false,
    requestsPerSecond: 100
  }
})

const activeTab = ref('endpoints')
const connectionStatus = ref<'connected' | 'disconnected' | 'connecting' | 'error'>('disconnected')
const lastTestTime = ref(new Date())
const testing = ref(false)
const logsLoading = ref(false)

// 对话框状态
const showApiTester = ref(false)
const showSettings = ref(false)
const showEndpointEditor = ref(false)
const showMonitoring = ref(false)
const showLogDetail = ref(false)

// 筛选和搜索
const endpointSearch = ref('')
const endpointFilters = ref({ method: '' })
const logFilters = ref({
  level: '',
  dateRange: []
})

// 数据列表
const apiEndpoints = ref<ApiEndpoint[]>([
  {
    id: '1',
    method: 'GET',
    path: '/api/users',
    description: '获取用户列表',
    enabled: true,
    parameters: [
      { name: 'page', type: 'int', required: false, description: '页码' },
      { name: 'size', type: 'int', required: false, description: '页面大小' }
    ],
    headers: [
      { name: 'Authorization', required: true, description: '认证令牌' }
    ],
    responseExample: {
      code: 200,
      data: { users: [], total: 0 },
      message: 'success'
    },
    errorCodes: [
      { code: 401, message: '未认证' },
      { code: 403, message: '无权限' }
    ],
    lastTestResult: {
      success: true,
      responseTime: 245,
      statusCode: 200
    }
  },
  {
    id: '2',
    method: 'POST',
    path: '/api/users',
    description: '创建用户',
    enabled: true,
    parameters: [],
    headers: [],
    responseExample: {},
    errorCodes: [],
    lastTestResult: {
      success: false,
      responseTime: 5000,
      statusCode: 500
    }
  }
])

const requestLogs = ref<RequestLog[]>([])
const selectedLog = ref<RequestLog | null>(null)
const editingEndpoint = ref<ApiEndpoint | null>(null)

// 统计数据
const statistics = ref({
  todayRequests: 1247,
  successRate: 98.2,
  averageResponse: 268
})

const endpointStats = ref({})
const performanceMetrics = ref({})
const integrationConfig = ref({})
const realTimeMonitoringData = ref({})

// 计算属性
const filteredEndpoints = computed(() => {
  let filtered = [...apiEndpoints.value]
  
  if (endpointSearch.value) {
    const search = endpointSearch.value.toLowerCase()
    filtered = filtered.filter(ep => 
      ep.path.toLowerCase().includes(search) ||
      ep.description.toLowerCase().includes(search)
    )
  }
  
  if (endpointFilters.value.method) {
    filtered = filtered.filter(ep => ep.method === endpointFilters.value.method)
  }
  
  return filtered
})

// 方法
const formatDateTime = (date: Date) => {
  return date.toLocaleString('zh-CN')
}

const getConnectionStatusType = (status: string) => {
  const types: Record<string, string> = {
    'connected': 'success',
    'disconnected': 'info',
    'connecting': 'warning',
    'error': 'danger'
  }
  return types[status] || 'info'
}

const getConnectionStatusIcon = (status: string) => {
  const icons: Record<string, string> = {
    'connected': 'el-icon-success',
    'disconnected': 'el-icon-warning',
    'connecting': 'el-icon-loading',
    'error': 'el-icon-error'
  }
  return icons[status] || 'el-icon-info'
}

const getConnectionStatusText = (status: string) => {
  const texts: Record<string, string> = {
    'connected': '已连接',
    'disconnected': '未连接',
    'connecting': '连接中',
    'error': '连接异常'
  }
  return texts[status] || status
}

const getMethodTagType = (method: string) => {
  const types: Record<string, string> = {
    'GET': 'success',
    'POST': 'primary',
    'PUT': 'warning',
    'DELETE': 'danger',
    'PATCH': 'info'
  }
  return types[method] || 'default'
}

const getStatusCodeTagType = (statusCode: number) => {
  if (statusCode >= 200 && statusCode < 300) return 'success'
  if (statusCode >= 300 && statusCode < 400) return 'info'
  if (statusCode >= 400 && statusCode < 500) return 'warning'
  return 'danger'
}

const getLogLevelTagType = (level: string) => {
  const types: Record<string, string> = {
    'success': 'success',
    'error': 'danger',
    'warning': 'warning',
    'info': 'info'
  }
  return types[level] || 'default'
}

const getLogLevelText = (level: string) => {
  const texts: Record<string, string> = {
    'success': '成功',
    'error': '错误',
    'warning': '警告',
    'info': '信息'
  }
  return texts[level] || level
}

const testConnection = async () => {
  testing.value = true
  connectionStatus.value = 'connecting'
  
  try {
    // 模拟连接测试
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    const success = Math.random() > 0.2 // 80%成功率
    if (success) {
      connectionStatus.value = 'connected'
      ElMessage.success('连接测试成功')
    } else {
      connectionStatus.value = 'error'
      ElMessage.error('连接测试失败')
    }
    
    lastTestTime.value = new Date()
    emit('connectionStatusChanged', connectionStatus.value)
    
  } catch (error) {
    connectionStatus.value = 'error'
    ElMessage.error('连接测试异常')
  } finally {
    testing.value = false
  }
}

const testEndpoint = async (endpoint: ApiEndpoint) => {
  endpoint.testing = true
  
  try {
    // 模拟端点测试
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    const success = Math.random() > 0.1 // 90%成功率
    const responseTime = Math.floor(Math.random() * 1000) + 100
    const statusCode = success ? 200 : 500
    
    endpoint.lastTestResult = {
      success,
      responseTime,
      statusCode
    }
    
    // 记录日志
    requestLogs.value.unshift({
      id: Date.now().toString(),
      timestamp: new Date(),
      method: endpoint.method,
      url: `${connectorConfig.value.baseUrl}${endpoint.path}`,
      statusCode,
      responseTime,
      level: success ? 'success' : 'error',
      requestHeaders: {},
      requestBody: {},
      responseHeaders: {},
      responseBody: {}
    })
    
    ElMessage.success(`端点测试${success ? '成功' : '失败'}`)
    emit('endpointTested', endpoint, endpoint.lastTestResult)
    
  } catch (error) {
    ElMessage.error('端点测试异常')
  } finally {
    endpoint.testing = false
  }
}

const editEndpoint = (endpoint: ApiEndpoint) => {
  editingEndpoint.value = endpoint
  showEndpointEditor.value = true
}

const handleEndpointAction = (command: string) => {
  const [action, endpointId] = command.split('-')
  const endpoint = apiEndpoints.value.find(ep => ep.id === endpointId)
  
  if (!endpoint) return
  
  switch (action) {
    case 'copy':
      navigator.clipboard.writeText(`${connectorConfig.value.baseUrl}${endpoint.path}`)
      ElMessage.success('链接已复制到剪贴板')
      break
    case 'docs':
      // 生成API文档
      ElMessage.info('生成文档功能开发中')
      break
    case 'history':
      // 查看调用历史
      ElMessage.info('调用历史功能开发中')
      break
    case 'toggle':
      endpoint.enabled = !endpoint.enabled
      ElMessage.success(`端点已${endpoint.enabled ? '启用' : '禁用'}`)
      break
    case 'delete':
      deleteEndpoint(endpoint)
      break
  }
}

const deleteEndpoint = async (endpoint: ApiEndpoint) => {
  try {
    await ElMessageBox.confirm('确认删除此API端点？', '删除确认', {
      type: 'danger'
    })
    
    const index = apiEndpoints.value.findIndex(ep => ep.id === endpoint.id)
    if (index > -1) {
      apiEndpoints.value.splice(index, 1)
    }
    
    ElMessage.success('端点删除成功')
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('端点删除失败')
    }
  }
}

const searchEndpoints = () => {
  // 搜索逻辑已在computed中实现
}

const filterEndpoints = () => {
  // 筛选逻辑已在computed中实现
}

const importFromSwagger = async () => {
  try {
    const { value } = await ElMessageBox.prompt('请输入Swagger/OpenAPI文档URL', '导入API', {
      inputPlaceholder: 'https://api.example.com/swagger.json'
    })
    
    if (value) {
      // 模拟导入过程
      ElMessage.info('开始导入API端点...')
      await new Promise(resolve => setTimeout(resolve, 2000))
      ElMessage.success('API端点导入成功')
      
      // 刷新端点列表
      loadEndpoints()
    }
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('导入失败')
    }
  }
}

const loadLogs = async () => {
  logsLoading.value = true
  try {
    // 模拟加载日志
    await new Promise(resolve => setTimeout(resolve, 800))
  } finally {
    logsLoading.value = false
  }
}

const filterLogs = () => {
  loadLogs()
}

const clearLogs = async () => {
  try {
    await ElMessageBox.confirm('确认清空所有日志？', '清空确认', {
      type: 'warning'
    })
    
    requestLogs.value = []
    ElMessage.success('日志已清空')
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('清空失败')
    }
  }
}

const exportLogs = () => {
  // 导出日志功能
  const data = JSON.stringify(requestLogs.value, null, 2)
  const blob = new Blob([data], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `api-logs-${Date.now()}.json`
  a.click()
  URL.revokeObjectURL(url)
  
  ElMessage.success('日志导出成功')
}

const viewLogDetail = (log: RequestLog) => {
  selectedLog.value = log
  showLogDetail.value = true
}

const loadEndpoints = async () => {
  // 模拟加载端点
  await new Promise(resolve => setTimeout(resolve, 500))
}

const loadPerformanceData = async () => {
  // 模拟加载性能数据
  performanceMetrics.value = {
    avgResponseTime: 268,
    successRate: 98.2,
    errorRate: 1.8,
    throughput: 1247
  }
}

const handleTestCompleted = (result: any) => {
  // 处理测试完成
  console.log('API测试完成:', result)
}

const handleConfigSaved = (config: ConnectorConfig) => {
  connectorConfig.value = { ...config }
  emit('configUpdated', config)
  showSettings.value = false
  ElMessage.success('配置保存成功')
}

const handleEndpointSaved = (endpoint: ApiEndpoint) => {
  const index = apiEndpoints.value.findIndex(ep => ep.id === endpoint.id)
  if (index > -1) {
    apiEndpoints.value[index] = endpoint
  } else {
    apiEndpoints.value.push(endpoint)
  }
  
  editingEndpoint.value = null
  showEndpointEditor.value = false
  ElMessage.success('端点保存成功')
}

const handleIntegrationConfigUpdate = (config: any) => {
  integrationConfig.value = config
  ElMessage.success('集成配置更新成功')
}

// 生命周期
onMounted(() => {
  loadEndpoints()
  loadLogs()
  loadPerformanceData()
  testConnection()
})

onBeforeUnmount(() => {
  // 清理资源
})
</script>

<style scoped>
.api-connector {
  padding: 20px;
  background: #f5f5f5;
  min-height: 100vh;
}

.connector-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
  padding: 24px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
}

.header-info h2 {
  margin: 0 0 16px 0;
  font-size: 28px;
  color: #303133;
}

.connection-status {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 20px;
}

.last-test {
  font-size: 14px;
  color: #909399;
}

.api-stats {
  display: flex;
  gap: 32px;
}

.stat-item {
  text-align: center;
}

.stat-label {
  display: block;
  font-size: 12px;
  color: #909399;
  margin-bottom: 4px;
}

.stat-value {
  display: block;
  font-size: 20px;
  font-weight: 600;
  color: #303133;
}

.success-rate {
  color: #67c23a;
}

.connector-tabs {
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
}

.endpoints-section {
  padding: 24px;
}

.endpoints-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
  flex-wrap: wrap;
  gap: 16px;
}

.toolbar-left {
  display: flex;
  align-items: center;
}

.endpoint-item {
  border: 1px solid #ebeef5;
  border-radius: 8px;
  margin-bottom: 16px;
  transition: all 0.3s;
}

.endpoint-item:hover {
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.endpoint-disabled {
  opacity: 0.6;
  background: #f5f7fa;
}

.endpoint-header {
  display: flex;
  align-items: center;
  padding: 16px 20px;
  cursor: pointer;
}

.endpoint-method {
  flex-shrink: 0;
  margin-right: 16px;
}

.endpoint-path {
  flex: 1;
  margin-right: 16px;
}

.path {
  font-family: 'Monaco', 'Consolas', monospace;
  font-size: 14px;
  font-weight: 600;
  color: #303133;
}

.description {
  display: block;
  font-size: 12px;
  color: #909399;
  margin-top: 4px;
}

.endpoint-status {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-right: 16px;
}

.response-time {
  font-size: 12px;
  color: #909399;
}

.endpoint-details {
  padding: 0 20px 20px 20px;
  border-top: 1px solid #ebeef5;
}

.logs-section {
  padding: 24px;
}

.logs-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  flex-wrap: wrap;
  gap: 16px;
}

.toolbar-filters {
  display: flex;
  align-items: center;
}

.toolbar-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.danger-item {
  color: #f56c6c;
}

/* 响应式设计 */
@media (max-width: 1200px) {
  .connector-header {
    flex-direction: column;
    gap: 20px;
  }
  
  .api-stats {
    gap: 20px;
  }
}

@media (max-width: 768px) {
  .api-connector {
    padding: 12px;
  }
  
  .connector-header {
    padding: 20px;
  }
  
  .api-stats {
    gap: 16px;
    flex-wrap: wrap;
  }
  
  .endpoints-toolbar {
    flex-direction: column;
    align-items: stretch;
  }
  
  .toolbar-left {
    flex-direction: column;
    gap: 8px;
  }
  
  .endpoint-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }
  
  .logs-toolbar {
    flex-direction: column;
    align-items: stretch;
  }
}
</style>
