<!--
{{WorkflowName}}审批工作流组件
企业级审批流程管理，支持多级审批、条件分支、超时处理
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="approval-workflow">
    <!-- 工作流头部信息 -->
    <div class="workflow-header">
      <div class="workflow-info">
        <h3>{{ workflowConfig.title }}</h3>
        <div class="workflow-meta">
          <el-tag :type="getStatusType(currentStatus)">{{ getStatusText(currentStatus) }}</el-tag>
          <span class="workflow-id">流程ID: {{ workflowInstance.id }}</span>
          <span class="create-time">创建时间: {{ formatDate(workflowInstance.createdTime) }}</span>
        </div>
      </div>
      <div class="workflow-actions">
        <el-button-group>
          <el-button 
            v-if="canApprove" 
            type="success" 
            icon="el-icon-check"
            @click="showApprovalDialog = true"
          >
            批准
          </el-button>
          <el-button 
            v-if="canReject" 
            type="danger" 
            icon="el-icon-close"
            @click="showRejectionDialog = true"
          >
            拒绝
          </el-button>
          <el-button 
            v-if="canWithdraw" 
            type="warning" 
            icon="el-icon-refresh-left"
            @click="handleWithdraw"
          >
            撤回
          </el-button>
          <el-button 
            icon="el-icon-view"
            @click="showWorkflowDiagram = true"
          >
            查看流程图
          </el-button>
        </el-button-group>
      </div>
    </div>

    <!-- 业务数据展示 -->
    <div class="business-data-section">
      <el-card title="业务信息">
        <div class="business-form">
          <!-- 动态渲染业务表单字段 -->
          <div 
            v-for="field in businessFields"
            :key="field.name"
            class="business-field"
          >
            <label class="field-label">{{ field.label }}:</label>
            <div class="field-value">
              <!-- 文本类型 -->
              <span v-if="field.type === 'text'">{{ businessData[field.name] }}</span>
              <!-- 金额类型 -->
              <span v-else-if="field.type === 'amount'" class="amount-value">
                ¥{{ formatAmount(businessData[field.name]) }}
              </span>
              <!-- 日期类型 -->
              <span v-else-if="field.type === 'date'">
                {{ formatDate(businessData[field.name]) }}
              </span>
              <!-- 附件类型 -->
              <div v-else-if="field.type === 'attachments'" class="attachments">
                <el-tag 
                  v-for="file in businessData[field.name]"
                  :key="file.id"
                  class="attachment-tag"
                  @click="downloadFile(file)"
                >
                  <el-icon><Document /></el-icon>
                  {{ file.name }}
                </el-tag>
              </div>
              <!-- 其他类型 -->
              <span v-else>{{ businessData[field.name] }}</span>
            </div>
          </div>
        </div>
      </el-card>
    </div>

    <!-- 审批流程时间线 -->
    <div class="approval-timeline-section">
      <el-card title="审批记录">
        <el-timeline>
          <el-timeline-item
            v-for="(step, index) in approvalHistory"
            :key="index"
            :type="getTimelineType(step.result)"
            :timestamp="formatDateTime(step.processTime)"
          >
            <div class="timeline-content">
              <div class="step-header">
                <strong>{{ step.stepName }}</strong>
                <el-tag :type="getResultType(step.result)" size="small">
                  {{ step.result }}
                </el-tag>
              </div>
              <div class="step-details">
                <p><strong>处理人:</strong> {{ step.approverName }}</p>
                <p v-if="step.comment"><strong>意见:</strong> {{ step.comment }}</p>
                <p v-if="step.duration"><strong>处理时长:</strong> {{ formatDuration(step.duration) }}</p>
              </div>
            </div>
          </el-timeline-item>
        </el-timeline>
      </el-card>
    </div>

    <!-- 审批对话框 -->
    <el-dialog
      v-model="showApprovalDialog"
      title="审批确认"
      width="500px"
    >
      <el-form ref="approvalForm" :model="approvalData" label-width="80px">
        <el-form-item label="审批意见" prop="comment">
          <el-input
            v-model="approvalData.comment"
            type="textarea"
            :rows="4"
            placeholder="请输入审批意见（可选）"
          />
        </el-form-item>
        <el-form-item v-if="needNextApprover" label="下一审批人" prop="nextApprover">
          <el-select
            v-model="approvalData.nextApprover"
            placeholder="请选择下一审批人"
            style="width: 100%"
          >
            <el-option
              v-for="user in availableApprovers"
              :key="user.id"
              :label="user.name"
              :value="user.id"
            />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showApprovalDialog = false">取消</el-button>
        <el-button type="success" :loading="processing" @click="handleApproval">
          确认批准
        </el-button>
      </template>
    </el-dialog>

    <!-- 拒绝对话框 -->
    <el-dialog
      v-model="showRejectionDialog"
      title="拒绝确认"
      width="500px"
    >
      <el-form ref="rejectionForm" :model="rejectionData" label-width="80px">
        <el-form-item label="拒绝原因" prop="reason" required>
          <el-input
            v-model="rejectionData.reason"
            type="textarea"
            :rows="4"
            placeholder="请说明拒绝原因"
          />
        </el-form-item>
        <el-form-item label="拒绝类型" prop="type">
          <el-radio-group v-model="rejectionData.type">
            <el-radio label="terminate">终止流程</el-radio>
            <el-radio label="return">退回上一步</el-radio>
            <el-radio label="return-start">退回起始步骤</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showRejectionDialog = false">取消</el-button>
        <el-button type="danger" :loading="processing" @click="handleRejection">
          确认拒绝
        </el-button>
      </template>
    </el-dialog>

    <!-- 流程图查看对话框 -->
    <el-dialog
      v-model="showWorkflowDiagram"
      title="工作流程图"
      width="80%"
      top="5vh"
    >
      <div class="workflow-diagram-container">
        <WorkflowDiagram
          :workflow-config="workflowConfig"
          :current-step="currentStep"
          :completed-steps="completedSteps"
        />
      </div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Document } from '@element-plus/icons-vue'
import WorkflowDiagram from './components/WorkflowDiagram.vue'

// 接口定义
interface WorkflowInstance {
  id: string
  workflowId: string
  businessId: string
  businessType: string
  status: string
  currentStep: string
  createdTime: Date
  createdBy: string
}

interface BusinessField {
  name: string
  label: string
  type: 'text' | 'amount' | 'date' | 'attachments'
  required?: boolean
}

interface ApprovalStep {
  stepName: string
  approverName: string
  result: 'approved' | 'rejected' | 'pending' | 'timeout'
  comment?: string
  processTime?: Date
  duration?: number
}

interface WorkflowConfig {
  title: string
  steps: Array<{
    id: string
    name: string
    type: 'approval' | 'condition' | 'notification'
    approvers?: string[]
    conditions?: any[]
  }>
}

// 组件属性
interface Props {
  workflowInstanceId: string
  readonly?: boolean
  showDiagram?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  readonly: false,
  showDiagram: true
})

// 组件事件
const emit = defineEmits<{
  approved: [instanceId: string, comment?: string]
  rejected: [instanceId: string, reason: string, type: string]
  withdrawn: [instanceId: string]
}>()

// 响应式数据
const workflowInstance = ref<WorkflowInstance>({
  id: props.workflowInstanceId,
  workflowId: '{{workflowId}}',
  businessId: '',
  businessType: '{{BusinessType}}',
  status: 'pending',
  currentStep: 'step_1',
  createdTime: new Date(),
  createdBy: ''
})

const workflowConfig = ref<WorkflowConfig>({
  title: '{{WorkflowName}}',
  steps: [
    { id: 'step_1', name: '部门主管审批', type: 'approval' },
    { id: 'step_2', name: '财务审核', type: 'approval' },
    { id: 'step_3', name: '总经理审批', type: 'approval' }
  ]
})

const businessData = ref<Record<string, any>>({})
const businessFields = ref<BusinessField[]>([
  { name: 'title', label: '申请标题', type: 'text', required: true },
  { name: 'amount', label: '申请金额', type: 'amount', required: true },
  { name: 'deadline', label: '期望日期', type: 'date' },
  { name: 'attachments', label: '相关附件', type: 'attachments' }
])

const approvalHistory = ref<ApprovalStep[]>([])
const availableApprovers = ref([])

// 对话框状态
const showApprovalDialog = ref(false)
const showRejectionDialog = ref(false)
const showWorkflowDiagram = ref(false)
const processing = ref(false)

// 表单数据
const approvalData = ref({
  comment: '',
  nextApprover: ''
})

const rejectionData = ref({
  reason: '',
  type: 'terminate'
})

// 计算属性
const currentStatus = computed(() => workflowInstance.value.status)
const currentStep = computed(() => workflowInstance.value.currentStep)

const canApprove = computed(() => {
  return !props.readonly && 
         currentStatus.value === 'pending' && 
         hasPermission('approve')
})

const canReject = computed(() => {
  return !props.readonly && 
         currentStatus.value === 'pending' && 
         hasPermission('reject')
})

const canWithdraw = computed(() => {
  return !props.readonly && 
         currentStatus.value === 'pending' && 
         isCreator()
})

const needNextApprover = computed(() => {
  return availableApprovers.value.length > 1
})

const completedSteps = computed(() => {
  return approvalHistory.value
    .filter(step => step.result === 'approved')
    .map(step => step.stepName)
})

// 方法
const getStatusType = (status: string) => {
  const types: Record<string, string> = {
    'pending': 'warning',
    'approved': 'success',
    'rejected': 'danger',
    'withdrawn': 'info',
    'timeout': 'danger'
  }
  return types[status] || 'info'
}

const getStatusText = (status: string) => {
  const texts: Record<string, string> = {
    'pending': '审批中',
    'approved': '已通过',
    'rejected': '已拒绝',
    'withdrawn': '已撤回',
    'timeout': '已超时'
  }
  return texts[status] || '未知状态'
}

const getTimelineType = (result: string) => {
  const types: Record<string, string> = {
    'approved': 'success',
    'rejected': 'danger',
    'pending': 'warning',
    'timeout': 'danger'
  }
  return types[result] || 'info'
}

const getResultType = (result: string) => {
  const types: Record<string, string> = {
    'approved': 'success',
    'rejected': 'danger',
    'pending': 'warning',
    'timeout': 'danger'
  }
  return types[result] || 'info'
}

const formatDate = (date: Date | string) => {
  if (!date) return '-'
  return new Date(date).toLocaleDateString('zh-CN')
}

const formatDateTime = (date: Date | string) => {
  if (!date) return '-'
  return new Date(date).toLocaleString('zh-CN')
}

const formatAmount = (amount: number) => {
  return new Intl.NumberFormat('zh-CN').format(amount)
}

const formatDuration = (duration: number) => {
  const hours = Math.floor(duration / 3600000)
  const minutes = Math.floor((duration % 3600000) / 60000)
  return hours > 0 ? `${hours}小时${minutes}分钟` : `${minutes}分钟`
}

const hasPermission = (action: string): boolean => {
  // 实际项目中应该调用权限检查API
  return true
}

const isCreator = (): boolean => {
  // 实际项目中应该检查是否为流程创建者
  return true
}

const downloadFile = (file: any) => {
  // 实现文件下载逻辑
  window.open(file.url, '_blank')
}

const handleApproval = async () => {
  try {
    processing.value = true
    
    // 调用审批API
    await approveWorkflow({
      instanceId: workflowInstance.value.id,
      comment: approvalData.value.comment,
      nextApprover: approvalData.value.nextApprover
    })
    
    ElMessage.success('审批成功')
    showApprovalDialog.value = false
    emit('approved', workflowInstance.value.id, approvalData.value.comment)
    
    // 刷新数据
    await loadWorkflowData()
    
  } catch (error) {
    ElMessage.error('审批失败')
    console.error('审批错误:', error)
  } finally {
    processing.value = false
  }
}

const handleRejection = async () => {
  try {
    processing.value = true
    
    // 调用拒绝API
    await rejectWorkflow({
      instanceId: workflowInstance.value.id,
      reason: rejectionData.value.reason,
      type: rejectionData.value.type
    })
    
    ElMessage.success('已拒绝申请')
    showRejectionDialog.value = false
    emit('rejected', workflowInstance.value.id, rejectionData.value.reason, rejectionData.value.type)
    
    // 刷新数据
    await loadWorkflowData()
    
  } catch (error) {
    ElMessage.error('拒绝失败')
    console.error('拒绝错误:', error)
  } finally {
    processing.value = false
  }
}

const handleWithdraw = async () => {
  try {
    await ElMessageBox.confirm('确认要撤回此申请吗？', '撤回确认', {
      type: 'warning'
    })
    
    processing.value = true
    
    // 调用撤回API
    await withdrawWorkflow(workflowInstance.value.id)
    
    ElMessage.success('已撤回申请')
    emit('withdrawn', workflowInstance.value.id)
    
    // 刷新数据
    await loadWorkflowData()
    
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('撤回失败')
      console.error('撤回错误:', error)
    }
  } finally {
    processing.value = false
  }
}

// API调用模拟函数（实际项目中应该调用真实API）
const approveWorkflow = async (params: any) => {
  // 模拟API调用
  return new Promise(resolve => setTimeout(resolve, 1000))
}

const rejectWorkflow = async (params: any) => {
  // 模拟API调用
  return new Promise(resolve => setTimeout(resolve, 1000))
}

const withdrawWorkflow = async (instanceId: string) => {
  // 模拟API调用
  return new Promise(resolve => setTimeout(resolve, 1000))
}

const loadWorkflowData = async () => {
  try {
    // 加载工作流实例数据
    // const instance = await workflowApi.getInstance(props.workflowInstanceId)
    // workflowInstance.value = instance
    
    // 加载业务数据
    // const business = await businessApi.getData(instance.businessId)
    // businessData.value = business
    
    // 加载审批历史
    // const history = await workflowApi.getApprovalHistory(props.workflowInstanceId)
    // approvalHistory.value = history
    
    // 加载可用审批人
    // const approvers = await workflowApi.getAvailableApprovers(props.workflowInstanceId)
    // availableApprovers.value = approvers
    
  } catch (error) {
    console.error('加载工作流数据失败:', error)
    ElMessage.error('加载数据失败')
  }
}

// 生命周期
onMounted(() => {
  loadWorkflowData()
})
</script>

<style scoped>
.approval-workflow {
  padding: 20px;
}

.workflow-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 20px;
  padding: 16px;
  background: #f8f9fa;
  border-radius: 8px;
}

.workflow-info h3 {
  margin: 0 0 8px 0;
  color: #303133;
}

.workflow-meta {
  display: flex;
  align-items: center;
  gap: 16px;
  font-size: 14px;
  color: #606266;
}

.business-data-section,
.approval-timeline-section {
  margin-bottom: 20px;
}

.business-form {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 16px;
}

.business-field {
  display: flex;
  align-items: flex-start;
  gap: 8px;
}

.field-label {
  font-weight: 500;
  color: #606266;
  min-width: 80px;
  flex-shrink: 0;
}

.field-value {
  flex: 1;
}

.amount-value {
  font-weight: 600;
  color: #e6a23c;
}

.attachments {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.attachment-tag {
  cursor: pointer;
}

.attachment-tag:hover {
  background-color: #ecf5ff;
}

.timeline-content {
  padding-left: 8px;
}

.step-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}

.step-details {
  font-size: 14px;
  color: #606266;
}

.step-details p {
  margin: 4px 0;
}

.workflow-diagram-container {
  height: 500px;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .workflow-header {
    flex-direction: column;
    gap: 12px;
  }
  
  .workflow-actions {
    width: 100%;
  }
  
  .business-form {
    grid-template-columns: 1fr;
  }
  
  .business-field {
    flex-direction: column;
    gap: 4px;
  }
  
  .field-label {
    min-width: auto;
  }
}
</style>
