using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace .Domain.Entities
{
    /// <summary>
    /// 设备 - 生产线设备管理
    /// </summary>
    public class Equipment : FullAuditedAggregateRoot<Guid>
    {
        /// <summary>设备名称</summary>
        public string Name { get; set; }

        /// <summary>设备编码</summary>
        public string Code { get; set; }

        /// <summary>设备类型</summary>
        public enum Type { get; set; }

        /// <summary>所属生产线</summary>
        public Guid ProductionLineId { get; set; }

        /// <summary>是否在线</summary>
        public bool? IsOnline { get; set; }

        /// <summary>运行时长(小时)</summary>
        public decimal? OperatingHours { get; set; }

        /// <summary>最后维护日期</summary>
        public DateTime? LastMaintenanceDate { get; set; }

        /// <summary>下次维护日期</summary>
        public DateTime? NextMaintenanceDate { get; set; }

        protected Equipment() { }

        public Equipment(
            Guid id
            string name,
            string code,
            enum type,
            Guid productionLineI
        ) : base(id)
        {
            Name = name;
            Code = code;
            Type = type;
            ProductionLineId = productionLineId;
        }
    }
}

// Generated by SmartAbp DevKit Low-Code Engine
// Date: 2025-10-22 10:28:32
// Architecture: ABP vNext + DDD
// Quality: Enterprise-Grade
