using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace .Domain.Entities
{
    /// <summary>
    /// 生产线 - 工厂生产线管理
    /// </summary>
    public class ProductionLine : FullAuditedAggregateRoot<Guid>
    {
        /// <summary>生产线名称</summary>
        public string Name { get; set; }

        /// <summary>生产线编码</summary>
        public string Code { get; set; }

        /// <summary>运行状态</summary>
        public enum Status { get; set; }

        /// <summary>位置</summary>
        public string? Location { get; set; }

        /// <summary>设计产能</summary>
        public int? Capacity { get; set; }

        /// <summary>当前产量</summary>
        public int? CurrentOutput { get; set; }

        /// <summary>利用率(%)</summary>
        public decimal? UtilizationRate { get; set; }

        /// <summary>是否在线</summary>
        public bool? IsOnline { get; set; }

        protected ProductionLine() { }

        public ProductionLine(
            Guid id
            string name,
            string code,
            enum statu
        ) : base(id)
        {
            Name = name;
            Code = code;
            Status = status;
        }
    }
}

// Generated by SmartAbp DevKit Low-Code Engine
// Date: 2025-10-22 10:28:31
// Architecture: ABP vNext + DDD
// Quality: Enterprise-Grade
