using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace .Domain.Entities
{
    /// <summary>
    /// 传感器数据 - 设备传感器实时数据
    /// </summary>
    public class SensorData : FullAuditedAggregateRoot<Guid>
    {
        /// <summary>所属设备</summary>
        public Guid EquipmentId { get; set; }

        /// <summary>传感器类型</summary>
        public string SensorType { get; set; }

        /// <summary>温度(℃)</summary>
        public decimal? Temperature { get; set; }

        /// <summary>压力(MPa)</summary>
        public decimal? Pressure { get; set; }

        /// <summary>湿度(%)</summary>
        public decimal? Humidity { get; set; }

        /// <summary>振动(mm/s)</summary>
        public decimal? Vibration { get; set; }

        /// <summary>功率(kW)</summary>
        public decimal? Power { get; set; }

        /// <summary>采集时间</summary>
        public DateTime Timestamp { get; set; }

        /// <summary>是否告警</summary>
        public bool? IsAlarm { get; set; }

        protected SensorData() { }

        public SensorData(
            Guid id
            Guid equipmentId,
            string sensorType,
            DateTime timestam
        ) : base(id)
        {
            EquipmentId = equipmentId;
            SensorType = sensorType;
            Timestamp = timestamp;
        }
    }
}

// Generated by SmartAbp DevKit Low-Code Engine
// Date: 2025-10-22 10:28:32
// Architecture: ABP vNext + DDD
// Quality: Enterprise-Grade
