/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthExample: typeof import('./src/components/auth/AuthExample.vue')['default']
    DashboardView: typeof import('./src/components/common/DashboardView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LogSearchFilter: typeof import('./src/components/log/LogSearchFilter.vue')['default']
    LogViewer: typeof import('./src/components/log/LogViewer.vue')['default']
    PlaceholderView: typeof import('./src/components/PlaceholderView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandboxPreview: typeof import('./src/components/lowcode/SandboxPreview.vue')['default']
    SimpleThemeSwitcher: typeof import('./src/components/theme/SimpleThemeSwitcher.vue')['default']
    SmartAbp: typeof import('./src/components/common/SmartAbp.vue')['default']
    SmartAbpLayout: typeof import('./src/components/layout/SmartAbpLayout.vue')['default']
    StateMachineEditor: typeof import('./src/components/lowcode/StateMachineEditor.vue')['default']
    TemplateSelector: typeof import('./src/components/lowcode/TemplateSelector.vue')['default']
    ThemeEditor: typeof import('./src/components/lowcode/ThemeEditor.vue')['default']
    ThemeSwitcher: typeof import('./src/components/theme/ThemeSwitcher.vue')['default']
  }
}
