/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthExample: typeof import('./src/components/auth/AuthExample.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    DashboardIcon: typeof import('./src/components/icons/enterprise/DashboardIcon.vue')['default']
    EnhancedStateMachine: typeof import('./src/components/lowcode/EnhancedStateMachine.vue')['default']
    EnterpriseIconSystem: typeof import('./src/components/icons/EnterpriseIconSystem.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconGallerySimple: typeof import('./src/components/icons/IconGallerySimple.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LazyImage: typeof import('./src/components/performance/LazyImage.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LogoutConfirmDialog: typeof import('./src/components/common/LogoutConfirmDialog.vue')['default']
    LogSearchFilter: typeof import('./src/components/log/LogSearchFilter.vue')['default']
    LogViewer: typeof import('./src/components/log/LogViewer.vue')['default']
    LowCodeIcon: typeof import('./src/components/icons/enterprise/LowCodeIcon.vue')['default']
    MDIContainer: typeof import('./src/components/ui/MDIContainer.vue')['default']
    ModuleLoadingState: typeof import('./src/components/common/ModuleLoadingState.vue')['default']
    OptimizedDataTable: typeof import('./src/components/performance/OptimizedDataTable.vue')['default']
    PermissionMatrix: typeof import('./src/components/permissions/PermissionMatrix.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleThemeSwitcher: typeof import('./src/components/theme/SimpleThemeSwitcher.vue')['default']
    SmartAbp: typeof import('./src/components/common/SmartAbp.vue')['default']
    SmartAbpLayout: typeof import('./src/components/layout/SmartAbpLayout.vue')['default']
    StudioFooter: typeof import('./src/components/layout/StudioFooter.vue')['default']
    StudioHeader: typeof import('./src/components/layout/StudioHeader.vue')['default']
    StudioPropertyPanel: typeof import('./src/components/layout/StudioPropertyPanel.vue')['default']
    StudioSidebar: typeof import('./src/components/layout/StudioSidebar.vue')['default']
    TabsContainer: typeof import('./src/components/ui/TabsContainer.vue')['default']
    ThemeSwitcher: typeof import('./src/components/theme/ThemeSwitcher.vue')['default']
    UserIcon: typeof import('./src/components/icons/enterprise/UserIcon.vue')['default']
  }
}
