$adrPath = "docs\架构设计\adr"
Rename-Item "$adrPath\0001-technology-stack-selection.md" "0001-技术栈选择.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0002-frontend-architecture-decisions.md" "0002-前端架构决策.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0002-ultimate-development-plan-execution-strategy.md" "0002-终极开发计划执行策略.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0003-backend-architecture-decisions.md" "0003-后端架构决策.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0003-technical-debt-assessment-and-prioritization.md" "0003-技术债务评估优先级.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0004-development-workflow-decisions.md" "0004-开发流程决策.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0005-lowcode-engine-architecture.md" "0005-低代码引擎架构.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0006-code-generation-output-isolation.md" "0006-代码生成输出隔离.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0006-incremental-code-generation.md" "0006-增量代码生成.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0007-typescript-project-references.md" "0007-TS项目引用.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0009-incremental-code-generation.md" "0009-增量代码生成.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0009-performance-optimization.md" "0009-性能优化.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0010-design-patterns.md" "0010-设计模式.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0011-ai-code-quality-assurance.md" "0011-AI代码质量保障.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0012-p1-backend-code-generation-engine.md" "0012-后端代码生成引擎.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0013-pluggable-strategy-architecture.md" "0013-可插拔策略架构.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0014-enterprise-memory-monitoring.md" "0014-企业级内存监控.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0015-visual-designer-architecture.md" "0015-可视化设计器架构.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0016-lowcode-engine-monorepo-refactoring.md" "0016-低代码引擎Monorepo重构.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0021-user-experience-revolution.md" "0021-用户体验革命.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0022-enterprise-data-modeling-architecture.md" "0022-企业级数据建模架构.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0023-visual-page-designer-revolution.md" "0023-可视化页面设计器革命.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0024-intelligent-code-generator-evolution.md" "0024-智能代码生成器演进.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0025-pragmatic-refactoring-overall-strategy.md" "0025-务实重构总体策略.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0026-phase1-emergency-fixes.md" "0026-Phase1紧急修复.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0027-phase2-architecture-boundary-clarification.md" "0027-Phase2架构边界澄清.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0028-phase3-runtime-performance-revolution.md" "0028-Phase3运行时性能革命.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0029-phase4-intelligent-code-generation.md" "0029-Phase4智能代码生成.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0030-excellence-engineering-standards.md" "0030-卓越工程标准.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0031-aspire-microservice-orchestration.md" "0031-Aspire微服务编排.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0032-assembly-plugin-management-system.md" "0032-组件插件管理系统.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0033-architecture-health-monitoring.md" "0033-架构健康监控.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\0034-dependency-automation-and-evolution.md" "0034-依赖自动化与演进.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\README.md" "ADR说明.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\template.md" "ADR模板.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\templates\adr-template.md" "ADR模板.md" -ErrorAction SilentlyContinue
Rename-Item "$adrPath\templates\architecture-evolution-template.md" "架构演进模板.md" -ErrorAction SilentlyContinue

