<!--
{{DocumentManagerName}}文档管理系统
企业级文档管理组件，支持文档上传、版本控制、协作编辑、权限管理
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="document-manager">
    <!-- 文档管理工具栏 -->
    <div class="manager-toolbar">
      <div class="toolbar-left">
        <el-button type="primary" @click="uploadDocument">
          <i class="el-icon-upload" />
          上传文档
        </el-button>
        <el-button @click="createFolder">
          <i class="el-icon-folder-add" />
          新建文件夹
        </el-button>
        <el-button @click="batchDownload" :disabled="selectedItems.length === 0">
          <i class="el-icon-download" />
          批量下载
        </el-button>
        <el-button @click="batchDelete" :disabled="selectedItems.length === 0" type="danger">
          <i class="el-icon-delete" />
          批量删除
        </el-button>
      </div>

      <div class="toolbar-center">
        <el-breadcrumb separator="/">
          <el-breadcrumb-item
            v-for="(item, index) in breadcrumbs"
            :key="index"
            @click="navigateToFolder(item)"
          >
            {{ item.name }}
          </el-breadcrumb-item>
        </el-breadcrumb>
      </div>

      <div class="toolbar-right">
        <el-button-group>
          <el-button :type="viewMode === 'list' ? 'primary' : ''" @click="viewMode = 'list'">
            <i class="el-icon-menu" />
          </el-button>
          <el-button :type="viewMode === 'grid' ? 'primary' : ''" @click="viewMode = 'grid'">
            <i class="el-icon-s-grid" />
          </el-button>
        </el-button-group>

        <el-input
          v-model="searchKeyword"
          placeholder="搜索文档"
          style="width: 200px; margin-left: 12px"
          clearable
        >
          <template #prefix>
            <i class="el-icon-search" />
          </template>
        </el-input>
      </div>
    </div>

    <div class="document-content">
      <!-- 左侧文件夹树 -->
      <div class="folder-sidebar">
        <div class="sidebar-header">
          <h3>文件夹</h3>
          <el-button size="small" text @click="refreshFolders">
            <i class="el-icon-refresh" />
          </el-button>
        </div>

        <el-tree
          :data="folderTree"
          :props="{ children: 'children', label: 'name' }"
          node-key="id"
          default-expand-all
          @node-click="onFolderSelect"
        >
          <template #default="{ node, data }">
            <span class="tree-node">
              <i class="el-icon-folder" />
              <span>{{ node.label }}</span>
              <span v-if="data.count" class="folder-count">({{ data.count }})</span>
            </span>
          </template>
        </el-tree>
      </div>

      <!-- 右侧文档列表 -->
      <div class="document-main">
        <!-- 文档过滤器 -->
        <div class="document-filters">
          <el-select v-model="typeFilter" placeholder="文档类型" clearable>
            <el-option label="全部" value="" />
            <el-option label="文档" value="document" />
            <el-option label="表格" value="spreadsheet" />
            <el-option label="演示" value="presentation" />
            <el-option label="图片" value="image" />
            <el-option label="视频" value="video" />
            <el-option label="其他" value="other" />
          </el-select>

          <el-select v-model="sortBy" placeholder="排序方式">
            <el-option label="名称" value="name" />
            <el-option label="修改时间" value="modifiedTime" />
            <el-option label="创建时间" value="createdTime" />
            <el-option label="大小" value="size" />
          </el-select>

          <el-select v-model="sortOrder" placeholder="排序顺序">
            <el-option label="升序" value="asc" />
            <el-option label="降序" value="desc" />
          </el-select>
        </div>

        <!-- 列表视图 -->
        <div v-if="viewMode === 'list'" class="list-view">
          <el-table
            :data="filteredDocuments"
            @selection-change="onSelectionChange"
            @row-dblclick="openDocument"
          >
            <el-table-column type="selection" width="55" />
            <el-table-column prop="name" label="文档名称" min-width="250">
              <template #default="{ row }">
                <div class="document-item">
                  <i :class="getDocumentIcon(row.type)" class="document-icon" />
                  <div class="document-info">
                    <div class="document-name">{{ row.name }}</div>
                    <div class="document-meta">{{ row.description }}</div>
                  </div>
                </div>
              </template>
            </el-table-column>

            <el-table-column prop="type" label="类型" width="100">
              <template #default="{ row }">
                <el-tag size="small" :type="getTypeTagColor(row.type)">
                  {{ getTypeLabel(row.type) }}
                </el-tag>
              </template>
            </el-table-column>

            <el-table-column prop="size" label="大小" width="100">
              <template #default="{ row }">
                {{ formatFileSize(row.size) }}
              </template>
            </el-table-column>

            <el-table-column prop="owner" label="所有者" width="120" />

            <el-table-column prop="modifiedTime" label="修改时间" width="160">
              <template #default="{ row }">
                {{ formatTime(row.modifiedTime) }}
              </template>
            </el-table-column>

            <el-table-column prop="status" label="状态" width="100">
              <template #default="{ row }">
                <el-tag size="small" :type="getStatusTagColor(row.status)">
                  {{ getStatusLabel(row.status) }}
                </el-tag>
              </template>
            </el-table-column>

            <el-table-column label="操作" width="200" fixed="right">
              <template #default="{ row }">
                <el-button size="small" @click="previewDocument(row)">预览</el-button>
                <el-button size="small" @click="downloadDocument(row)">下载</el-button>
                <el-dropdown>
                  <el-button size="small">
                    更多<i class="el-icon-arrow-down el-icon--right" />
                  </el-button>
                  <template #dropdown>
                    <el-dropdown-menu>
                      <el-dropdown-item @click="shareDocument(row)">
                        分享文档
                      </el-dropdown-item>
                      <el-dropdown-item @click="viewVersions(row)">
                        版本历史
                      </el-dropdown-item>
                      <el-dropdown-item @click="setPermissions(row)">
                        权限设置
                      </el-dropdown-item>
                      <el-dropdown-item divided @click="renameDocument(row)">
                        重命名
                      </el-dropdown-item>
                      <el-dropdown-item @click="moveDocument(row)">
                        移动文档
                      </el-dropdown-item>
                      <el-dropdown-item
                        @click="deleteDocument(row)"
                        style="color: #f56c6c"
                      >
                        删除文档
                      </el-dropdown-item>
                    </el-dropdown-menu>
                  </template>
                </el-dropdown>
              </template>
            </el-table-column>
          </el-table>
        </div>

        <!-- 网格视图 -->
        <div v-else class="grid-view">
          <div class="document-grid">
            <div
              v-for="doc in filteredDocuments"
              :key="doc.id"
              class="document-card"
              :class="{ selected: selectedItems.includes(doc.id) }"
              @click="toggleSelection(doc)"
              @dblclick="openDocument(doc)"
            >
              <div class="card-header">
                <i :class="getDocumentIcon(doc.type)" class="document-icon large" />
                <el-checkbox
                  :model-value="selectedItems.includes(doc.id)"
                  @change="toggleSelection(doc)"
                  @click.stop
                />
              </div>

              <div class="card-content">
                <div class="document-name" :title="doc.name">{{ doc.name }}</div>
                <div class="document-meta">
                  <span class="file-size">{{ formatFileSize(doc.size) }}</span>
                  <span class="modified-time">{{ formatTime(doc.modifiedTime) }}</span>
                </div>
              </div>

              <div class="card-actions">
                <el-button size="small" @click.stop="previewDocument(doc)">
                  预览
                </el-button>
                <el-button size="small" @click.stop="downloadDocument(doc)">
                  下载
                </el-button>
              </div>
            </div>
          </div>
        </div>

        <!-- 分页 -->
        <el-pagination
          v-model:current-page="currentPage"
          v-model:page-size="pageSize"
          :total="totalDocuments"
          :page-sizes="[20, 50, 100, 200]"
          layout="total, sizes, prev, pager, next, jumper"
        />
      </div>
    </div>

    <!-- 文档预览对话框 -->
    <el-dialog
      v-model="previewDialogVisible"
      title="文档预览"
      width="900px"
      append-to-body
    >
      <div class="document-preview">
        <div v-if="previewDocument" class="preview-content">
          <div v-if="previewDocument.type === 'image'" class="image-preview">
            <img :src="previewDocument.url" :alt="previewDocument.name" />
          </div>
          <div v-else-if="previewDocument.type === 'document'" class="document-preview-content">
            <iframe
              :src="previewDocument.previewUrl"
              width="100%"
              height="500px"
              frameborder="0"
            />
          </div>
          <div v-else class="unsupported-preview">
            <i class="el-icon-document" style="font-size: 64px; color: #c0c4cc" />
            <p>该文件类型不支持在线预览</p>
            <el-button @click="downloadDocument(previewDocument)">
              下载查看
            </el-button>
          </div>
        </div>
      </div>
    </el-dialog>

    <!-- 版本历史对话框 -->
    <el-dialog
      v-model="versionDialogVisible"
      title="版本历史"
      width="700px"
    >
      <el-table :data="documentVersions" stripe>
        <el-table-column prop="version" label="版本" width="80" />
        <el-table-column prop="size" label="大小" width="100">
          <template #default="{ row }">
            {{ formatFileSize(row.size) }}
          </template>
        </el-table-column>
        <el-table-column prop="modifier" label="修改人" width="120" />
        <el-table-column prop="modifiedTime" label="修改时间" width="160">
          <template #default="{ row }">
            {{ formatTime(row.modifiedTime) }}
          </template>
        </el-table-column>
        <el-table-column prop="comment" label="修改说明" min-width="200" />
        <el-table-column label="操作" width="150">
          <template #default="{ row }">
            <el-button size="small" @click="downloadVersion(row)">
              下载
            </el-button>
            <el-button size="small" @click="restoreVersion(row)">
              恢复
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-dialog>

    <!-- 上传对话框 -->
    <el-dialog
      v-model="uploadDialogVisible"
      title="上传文档"
      width="600px"
    >
      <el-upload
        class="upload-demo"
        drag
        multiple
        :auto-upload="false"
        :file-list="uploadFileList"
        @change="handleFileChange"
      >
        <i class="el-icon-upload" />
        <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
        <template #tip>
          <div class="el-upload__tip">
            支持 doc/docx/pdf/xls/xlsx/ppt/pptx/jpg/png 等格式，单个文件不超过100MB
          </div>
        </template>
      </el-upload>

      <template #footer>
        <span class="dialog-footer">
          <el-button @click="uploadDialogVisible = false">取消</el-button>
          <el-button type="primary" @click="confirmUpload">开始上传</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

// 响应式数据
const viewMode = ref('list')
const searchKeyword = ref('')
const typeFilter = ref('')
const sortBy = ref('modifiedTime')
const sortOrder = ref('desc')
const currentPage = ref(1)
const pageSize = ref(20)
const selectedItems = ref([])
const previewDialogVisible = ref(false)
const versionDialogVisible = ref(false)
const uploadDialogVisible = ref(false)
const uploadFileList = ref([])
const currentFolder = ref({ id: 1, name: '根目录' })

const breadcrumbs = ref([
  { id: 1, name: '根目录', path: '/' }
])

const folderTree = ref([
  {
    id: 1,
    name: '根目录',
    count: 15,
    children: [
      {
        id: 2,
        name: '项目文档',
        count: 8,
        children: [
          { id: 3, name: '需求分析', count: 3 },
          { id: 4, name: '设计文档', count: 5 }
        ]
      },
      {
        id: 5,
        name: '合同文件',
        count: 7,
        children: [
          { id: 6, name: '采购合同', count: 4 },
          { id: 7, name: '服务合同', count: 3 }
        ]
      }
    ]
  }
])

const documents = ref([
  {
    id: 1,
    name: '项目需求说明书v2.1.docx',
    description: '详细的项目需求分析和功能说明',
    type: 'document',
    size: 2048576,
    owner: '张三',
    modifiedTime: new Date('2024-12-20 14:30:00'),
    status: 'published',
    folderId: 3,
    url: '/documents/1/preview',
    previewUrl: '/documents/1/preview'
  },
  {
    id: 2,
    name: '系统架构图.png',
    description: '系统整体架构设计图',
    type: 'image',
    size: 1024000,
    owner: '李四',
    modifiedTime: new Date('2024-12-19 16:45:00'),
    status: 'draft',
    folderId: 4,
    url: '/images/system-architecture.png'
  }
])

const documentVersions = ref([
  {
    version: 'v2.1',
    size: 2048576,
    modifier: '张三',
    modifiedTime: new Date('2024-12-20 14:30:00'),
    comment: '修复了用户权限相关的描述问题'
  },
  {
    version: 'v2.0',
    size: 2020000,
    modifier: '李四',
    modifiedTime: new Date('2024-12-18 10:15:00'),
    comment: '增加了新的业务流程说明'
  }
])

const previewDocument = ref(null)

// 计算属性
const filteredDocuments = computed(() => {
  let result = documents.value

  if (searchKeyword.value) {
    const keyword = searchKeyword.value.toLowerCase()
    result = result.filter(doc =>
      doc.name.toLowerCase().includes(keyword) ||
      doc.description.toLowerCase().includes(keyword)
    )
  }

  if (typeFilter.value) {
    result = result.filter(doc => doc.type === typeFilter.value)
  }

  // 排序
  result.sort((a, b) => {
    const aValue = a[sortBy.value]
    const bValue = b[sortBy.value]
    
    if (sortOrder.value === 'desc') {
      return bValue > aValue ? 1 : -1
    } else {
      return aValue > bValue ? 1 : -1
    }
  })

  return result
})

const totalDocuments = computed(() => filteredDocuments.value.length)

// 方法
const formatFileSize = (bytes: number) => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const formatTime = (time: Date) => {
  return time.toLocaleString('zh-CN')
}

const getDocumentIcon = (type: string) => {
  const iconMap = {
    document: 'el-icon-document',
    spreadsheet: 'el-icon-s-grid',
    presentation: 'el-icon-picture-outline',
    image: 'el-icon-picture',
    video: 'el-icon-video-camera',
    other: 'el-icon-document'
  }
  return iconMap[type] || 'el-icon-document'
}

const getTypeTagColor = (type: string) => {
  const colorMap = {
    document: 'primary',
    spreadsheet: 'success',
    presentation: 'warning',
    image: 'info',
    video: 'danger',
    other: ''
  }
  return colorMap[type] || ''
}

const getTypeLabel = (type: string) => {
  const labelMap = {
    document: '文档',
    spreadsheet: '表格',
    presentation: '演示',
    image: '图片',
    video: '视频',
    other: '其他'
  }
  return labelMap[type] || type
}

const getStatusTagColor = (status: string) => {
  const colorMap = {
    draft: 'info',
    published: 'success',
    archived: 'warning'
  }
  return colorMap[status] || ''
}

const getStatusLabel = (status: string) => {
  const labelMap = {
    draft: '草稿',
    published: '已发布',
    archived: '已归档'
  }
  return labelMap[status] || status
}

const onFolderSelect = (data: any) => {
  currentFolder.value = data
  // 更新面包屑和文档列表
}

const onSelectionChange = (selection: any[]) => {
  selectedItems.value = selection.map(item => item.id)
}

const toggleSelection = (doc: any) => {
  const index = selectedItems.value.indexOf(doc.id)
  if (index > -1) {
    selectedItems.value.splice(index, 1)
  } else {
    selectedItems.value.push(doc.id)
  }
}

const navigateToFolder = (folder: any) => {
  currentFolder.value = folder
  // 更新文档列表
}

const refreshFolders = () => {
  ElMessage.success('文件夹列表已刷新')
}

const uploadDocument = () => {
  uploadFileList.value = []
  uploadDialogVisible.value = true
}

const createFolder = () => {
  ElMessage.info('创建文件夹功能开发中...')
}

const batchDownload = () => {
  ElMessage.success(`开始下载${selectedItems.value.length}个文件`)
}

const batchDelete = async () => {
  try {
    await ElMessageBox.confirm(
      `确定要删除选中的${selectedItems.value.length}个文件吗？`,
      '批量删除',
      {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }
    )
    
    ElMessage.success('文档删除成功')
    selectedItems.value = []
  } catch {
    // 用户取消
  }
}

const openDocument = (doc: any) => {
  ElMessage.info(`正在打开文档: ${doc.name}`)
}

const previewDocument = (doc: any) => {
  previewDocument.value = doc
  previewDialogVisible.value = true
}

const downloadDocument = (doc: any) => {
  ElMessage.success(`开始下载: ${doc.name}`)
}

const shareDocument = (doc: any) => {
  ElMessage.info('分享功能开发中...')
}

const viewVersions = (doc: any) => {
  // 获取文档版本历史
  versionDialogVisible.value = true
}

const setPermissions = (doc: any) => {
  ElMessage.info('权限设置功能开发中...')
}

const renameDocument = (doc: any) => {
  ElMessage.info('重命名功能开发中...')
}

const moveDocument = (doc: any) => {
  ElMessage.info('移动文档功能开发中...')
}

const deleteDocument = async (doc: any) => {
  try {
    await ElMessageBox.confirm(`确定要删除文档"${doc.name}"吗？`, '删除确认', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    
    ElMessage.success('文档删除成功')
  } catch {
    // 用户取消
  }
}

const handleFileChange = (file: any, fileList: any[]) => {
  uploadFileList.value = fileList
}

const confirmUpload = () => {
  if (uploadFileList.value.length === 0) {
    ElMessage.warning('请选择要上传的文件')
    return
  }

  ElMessage.success(`开始上传${uploadFileList.value.length}个文件`)
  uploadDialogVisible.value = false
}

const downloadVersion = (version: any) => {
  ElMessage.success(`开始下载版本: ${version.version}`)
}

const restoreVersion = async (version: any) => {
  try {
    await ElMessageBox.confirm(`确定要恢复到版本${version.version}吗？`, '版本恢复', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    
    ElMessage.success('版本恢复成功')
    versionDialogVisible.value = false
  } catch {
    // 用户取消
  }
}

// 生命周期
onMounted(() => {
  // 初始化数据
})
</script>

<style scoped>
.document-manager {
  padding: 20px;
  height: 100vh;
  display: flex;
  flex-direction: column;
}

.manager-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
  margin-bottom: 20px;
}

.toolbar-left, .toolbar-right {
  display: flex;
  gap: 12px;
  align-items: center;
}

.toolbar-center {
  flex: 1;
  margin: 0 20px;
}

.document-content {
  flex: 1;
  display: flex;
  gap: 20px;
  overflow: hidden;
}

.folder-sidebar {
  width: 280px;
  background: white;
  border-radius: 8px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
  overflow-y: auto;
}

.sidebar-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid #ebeef5;
}

.sidebar-header h3 {
  margin: 0;
  color: #303133;
  font-size: 16px;
}

.tree-node {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
}

.folder-count {
  color: #909399;
  font-size: 12px;
}

.document-main {
  flex: 1;
  background: white;
  border-radius: 8px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.document-filters {
  display: flex;
  gap: 16px;
  margin-bottom: 20px;
  align-items: center;
}

.list-view {
  flex: 1;
  overflow: auto;
}

.document-item {
  display: flex;
  align-items: center;
  gap: 12px;
}

.document-icon {
  font-size: 20px;
  color: #409eff;
  flex-shrink: 0;
}

.document-icon.large {
  font-size: 48px;
}

.document-info {
  flex: 1;
  min-width: 0;
}

.document-name {
  font-weight: 500;
  color: #303133;
  margin-bottom: 4px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.document-meta {
  font-size: 12px;
  color: #909399;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.grid-view {
  flex: 1;
  overflow: auto;
}

.document-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 16px;
}

.document-card {
  border: 1px solid #ebeef5;
  border-radius: 8px;
  padding: 16px;
  cursor: pointer;
  transition: all 0.3s;
  background: white;
}

.document-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12);
  border-color: #409eff;
}

.document-card.selected {
  border-color: #409eff;
  background: #f0f9ff;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.card-content {
  margin-bottom: 12px;
}

.card-content .document-name {
  margin-bottom: 8px;
  font-size: 14px;
}

.card-content .document-meta {
  display: flex;
  justify-content: space-between;
  font-size: 11px;
}

.card-actions {
  display: flex;
  gap: 8px;
}

.document-preview {
  min-height: 400px;
}

.image-preview {
  text-align: center;
}

.image-preview img {
  max-width: 100%;
  max-height: 500px;
  object-fit: contain;
}

.unsupported-preview {
  text-align: center;
  padding: 60px 20px;
  color: #c0c4cc;
}

.upload-demo {
  margin-bottom: 20px;
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}
</style>
