<!--
{{ReportName}}数据分析报表组件
企业级数据分析和可视化报表，支持多维度分析、导出、实时刷新
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="data-analysis-report">
    <!-- 报表头部控制区 -->
    <div class="report-header">
      <div class="report-info">
        <h2>{{ reportConfig.title }}</h2>
        <div class="report-meta">
          <span class="update-time">最后更新: {{ formatDateTime(lastUpdateTime) }}</span>
          <el-tag :type="getDataStatusType(dataStatus)">{{ getDataStatusText(dataStatus) }}</el-tag>
        </div>
      </div>
      
      <div class="report-controls">
        <!-- 时间范围选择器 -->
        <div class="time-range-selector">
          <el-date-picker
            v-model="timeRange"
            type="datetimerange"
            range-separator="至"
            start-placeholder="开始时间"
            end-placeholder="结束时间"
            format="YYYY-MM-DD HH:mm"
            value-format="YYYY-MM-DD HH:mm:ss"
            @change="handleTimeRangeChange"
          />
        </div>
        
        <!-- 维度筛选器 -->
        <div class="dimension-filters">
          <el-select
            v-for="dimension in reportConfig.dimensions"
            :key="dimension.key"
            v-model="selectedDimensions[dimension.key]"
            :placeholder="dimension.label"
            style="width: 140px; margin-left: 8px"
            clearable
            @change="handleDimensionChange"
          >
            <el-option
              v-for="option in dimension.options"
              :key="option.value"
              :label="option.label"
              :value="option.value"
            />
          </el-select>
        </div>
        
        <!-- 操作按钮组 -->
        <div class="action-buttons">
          <el-button-group>
            <el-button 
              :loading="refreshing" 
              icon="el-icon-refresh" 
              @click="refreshData"
            >
              刷新
            </el-button>
            <el-button 
              icon="el-icon-download" 
              @click="showExportDialog = true"
            >
              导出
            </el-button>
            <el-button 
              icon="el-icon-s-operation" 
              @click="showConfigDialog = true"
            >
              配置
            </el-button>
            <el-button 
              :type="autoRefresh ? 'success' : 'info'"
              :icon="autoRefresh ? 'el-icon-video-pause' : 'el-icon-video-play'"
              @click="toggleAutoRefresh"
            >
              {{ autoRefresh ? '停止' : '自动' }}刷新
            </el-button>
          </el-button-group>
        </div>
      </div>
    </div>

    <!-- 关键指标卡片区 -->
    <div class="kpi-cards-section">
      <div class="kpi-cards">
        <div 
          v-for="kpi in kpiMetrics"
          :key="kpi.key"
          class="kpi-card"
          :class="{ 'trend-up': kpi.trend > 0, 'trend-down': kpi.trend < 0 }"
        >
          <div class="kpi-icon">
            <i :class="kpi.icon" />
          </div>
          <div class="kpi-content">
            <div class="kpi-label">{{ kpi.label }}</div>
            <div class="kpi-value">{{ formatKpiValue(kpi.value, kpi.format) }}</div>
            <div class="kpi-trend">
              <span class="trend-indicator">
                <i :class="getTrendIcon(kpi.trend)" />
                {{ Math.abs(kpi.trend).toFixed(1) }}%
              </span>
              <span class="trend-period">{{ kpi.period }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 图表展示区 -->
    <div class="charts-section">
      <el-row :gutter="20">
        <!-- 主要趋势图表 -->
        <el-col :xs="24" :sm="24" :md="16" :lg="16">
          <el-card class="chart-card">
            <template #header>
              <div class="chart-header">
                <span>{{ mainChart.title }}</span>
                <div class="chart-controls">
                  <el-radio-group v-model="mainChart.type" size="small" @change="updateMainChart">
                    <el-radio-button label="line">趋势线</el-radio-button>
                    <el-radio-button label="bar">柱状图</el-radio-button>
                    <el-radio-button label="area">区域图</el-radio-button>
                  </el-radio-group>
                </div>
              </div>
            </template>
            <div class="chart-container">
              <ECharts
                ref="mainChartRef"
                :option="mainChart.option"
                :height="300"
                :loading="chartsLoading"
              />
            </div>
          </el-card>
        </el-col>
        
        <!-- 分布饼图 -->
        <el-col :xs="24" :sm="24" :md="8" :lg="8">
          <el-card class="chart-card">
            <template #header>
              <span>{{ distributionChart.title }}</span>
            </template>
            <div class="chart-container">
              <ECharts
                ref="pieChartRef"
                :option="distributionChart.option"
                :height="300"
                :loading="chartsLoading"
              />
            </div>
          </el-card>
        </el-col>
      </el-row>
      
      <!-- 对比分析图表 -->
      <el-row :gutter="20" style="margin-top: 20px">
        <el-col :span="24">
          <el-card class="chart-card">
            <template #header>
              <div class="chart-header">
                <span>{{ comparisonChart.title }}</span>
                <div class="chart-controls">
                  <el-select 
                    v-model="comparisonChart.compareBy" 
                    size="small" 
                    style="width: 120px"
                    @change="updateComparisonChart"
                  >
                    <el-option label="同比" value="yoy" />
                    <el-option label="环比" value="mom" />
                    <el-option label="定基比" value="base" />
                  </el-select>
                </div>
              </div>
            </template>
            <div class="chart-container">
              <ECharts
                ref="comparisonChartRef"
                :option="comparisonChart.option"
                :height="400"
                :loading="chartsLoading"
              />
            </div>
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 详细数据表格 -->
    <div class="data-table-section">
      <el-card class="table-card">
        <template #header>
          <div class="table-header">
            <span>详细数据</span>
            <div class="table-controls">
              <el-input
                v-model="tableSearch"
                placeholder="搜索..."
                style="width: 200px"
                @input="handleTableSearch"
              >
                <template #prefix>
                  <el-icon><Search /></el-icon>
                </template>
              </el-input>
            </div>
          </div>
        </template>
        
        <el-table
          :data="tableData"
          :loading="tableLoading"
          stripe
          border
          height="400"
          @sort-change="handleSort"
        >
          <el-table-column
            v-for="column in tableColumns"
            :key="column.prop"
            :prop="column.prop"
            :label="column.label"
            :width="column.width"
            :sortable="column.sortable"
            :formatter="column.formatter"
            show-overflow-tooltip
          />
          <el-table-column label="操作" width="120" fixed="right">
            <template #default="{ row }">
              <el-button-group size="small">
                <el-button @click="handleRowDetail(row)">详情</el-button>
                <el-button @click="handleRowDrill(row)">钻取</el-button>
              </el-button-group>
            </template>
          </el-table-column>
        </el-table>
        
        <div class="table-pagination">
          <el-pagination
            v-model:current-page="pagination.page"
            v-model:page-size="pagination.size"
            :total="pagination.total"
            :page-sizes="[10, 20, 50, 100]"
            layout="total, sizes, prev, pager, next, jumper"
            @current-change="handlePageChange"
            @size-change="handleSizeChange"
          />
        </div>
      </el-card>
    </div>

    <!-- 导出对话框 -->
    <el-dialog
      v-model="showExportDialog"
      title="导出报表"
      width="500px"
    >
      <el-form :model="exportConfig" label-width="100px">
        <el-form-item label="导出格式">
          <el-radio-group v-model="exportConfig.format">
            <el-radio label="excel">Excel表格</el-radio>
            <el-radio label="pdf">PDF文档</el-radio>
            <el-radio label="csv">CSV文件</el-radio>
            <el-radio label="image">图表图片</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="导出内容">
          <el-checkbox-group v-model="exportConfig.content">
            <el-checkbox label="kpi">关键指标</el-checkbox>
            <el-checkbox label="charts">图表</el-checkbox>
            <el-checkbox label="data">详细数据</el-checkbox>
          </el-checkbox-group>
        </el-form-item>
        <el-form-item label="文件名称">
          <el-input v-model="exportConfig.fileName" placeholder="请输入文件名" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showExportDialog = false">取消</el-button>
        <el-button type="primary" :loading="exporting" @click="handleExport">
          确认导出
        </el-button>
      </template>
    </el-dialog>

    <!-- 报表配置对话框 -->
    <el-dialog
      v-model="showConfigDialog"
      title="报表配置"
      width="600px"
    >
      <el-tabs>
        <el-tab-pane label="数据源" name="datasource">
          <ReportDataSourceConfig v-model="reportConfig.datasource" />
        </el-tab-pane>
        <el-tab-pane label="图表设置" name="charts">
          <ReportChartConfig v-model="reportConfig.charts" />
        </el-tab-pane>
        <el-tab-pane label="指标配置" name="kpi">
          <ReportKpiConfig v-model="reportConfig.kpi" />
        </el-tab-pane>
        <el-tab-pane label="权限控制" name="permissions">
          <ReportPermissionConfig v-model="reportConfig.permissions" />
        </el-tab-pane>
      </el-tabs>
      <template #footer>
        <el-button @click="showConfigDialog = false">取消</el-button>
        <el-button type="primary" @click="saveReportConfig">保存配置</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { ElMessage } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import ECharts from '@/components/common/ECharts.vue'
import ReportDataSourceConfig from './components/ReportDataSourceConfig.vue'
import ReportChartConfig from './components/ReportChartConfig.vue'
import ReportKpiConfig from './components/ReportKpiConfig.vue'
import ReportPermissionConfig from './components/ReportPermissionConfig.vue'

// 接口定义
interface ReportConfig {
  title: string
  datasource: any
  dimensions: Array<{
    key: string
    label: string
    options: Array<{ label: string; value: any }>
  }>
  charts: any
  kpi: any
  permissions: any
}

interface KpiMetric {
  key: string
  label: string
  value: number
  format: string
  trend: number
  period: string
  icon: string
}

// 组件属性
interface Props {
  reportId: string
  config?: Partial<ReportConfig>
  readonly?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  readonly: false
})

// 组件事件
const emit = defineEmits<{
  configChanged: [config: ReportConfig]
  dataExported: [result: { format: string; fileName: string }]
}>()

// 响应式数据
const reportConfig = ref<ReportConfig>({
  title: '{{ReportName}}',
  datasource: {},
  dimensions: [
    {
      key: 'department',
      label: '部门',
      options: [
        { label: '销售部', value: 'sales' },
        { label: '技术部', value: 'tech' },
        { label: '市场部', value: 'marketing' }
      ]
    },
    {
      key: 'status',
      label: '状态',
      options: [
        { label: '进行中', value: 'active' },
        { label: '已完成', value: 'completed' },
        { label: '已暂停', value: 'paused' }
      ]
    }
  ],
  charts: {},
  kpi: {},
  permissions: {}
})

// 时间范围和筛选
const timeRange = ref<[string, string]>([
  new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 19).replace('T', ' '),
  new Date().toISOString().slice(0, 19).replace('T', ' ')
])
const selectedDimensions = ref<Record<string, any>>({})

// 数据状态
const dataStatus = ref('loaded')
const lastUpdateTime = ref(new Date())
const refreshing = ref(false)
const chartsLoading = ref(false)
const tableLoading = ref(false)
const exporting = ref(false)

// 自动刷新
const autoRefresh = ref(false)
const refreshInterval = ref<number | null>(null)

// 对话框状态
const showExportDialog = ref(false)
const showConfigDialog = ref(false)

// KPI指标数据
const kpiMetrics = ref<KpiMetric[]>([
  {
    key: 'total_revenue',
    label: '总收入',
    value: 1234567.89,
    format: 'currency',
    trend: 12.5,
    period: '较上月',
    icon: 'el-icon-money'
  },
  {
    key: 'order_count',
    label: '订单数量',
    value: 5678,
    format: 'number',
    trend: -3.2,
    period: '较上月',
    icon: 'el-icon-s-order'
  },
  {
    key: 'conversion_rate',
    label: '转化率',
    value: 0.235,
    format: 'percentage',
    trend: 8.7,
    period: '较上月',
    icon: 'el-icon-pie-chart'
  },
  {
    key: 'active_users',
    label: '活跃用户',
    value: 98765,
    format: 'number',
    trend: 15.3,
    period: '较上月',
    icon: 'el-icon-user'
  }
])

// 图表配置
const mainChart = ref({
  title: '{{MainChartTitle}}趋势分析',
  type: 'line',
  option: {
    tooltip: { trigger: 'axis' },
    legend: { data: ['收入', '订单数'] },
    xAxis: { type: 'category', data: ['1月', '2月', '3月', '4月', '5月', '6月'] },
    yAxis: [
      { type: 'value', name: '收入(万元)' },
      { type: 'value', name: '订单数', position: 'right' }
    ],
    series: [
      {
        name: '收入',
        type: 'line',
        data: [120, 132, 101, 134, 90, 230],
        yAxisIndex: 0,
        smooth: true,
        areaStyle: { opacity: 0.3 }
      },
      {
        name: '订单数',
        type: 'line',
        data: [220, 182, 191, 234, 290, 330],
        yAxisIndex: 1,
        smooth: true
      }
    ]
  }
})

const distributionChart = ref({
  title: '{{DistributionTitle}}分布',
  option: {
    tooltip: { trigger: 'item' },
    legend: { orient: 'vertical', left: 'left' },
    series: [
      {
        name: '分布',
        type: 'pie',
        radius: '50%',
        data: [
          { value: 1048, name: '销售部' },
          { value: 735, name: '技术部' },
          { value: 580, name: '市场部' },
          { value: 484, name: '客服部' },
          { value: 300, name: '行政部' }
        ],
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }
    ]
  }
})

const comparisonChart = ref({
  title: '{{ComparisonTitle}}对比分析',
  compareBy: 'yoy',
  option: {
    tooltip: { trigger: 'axis' },
    legend: { data: ['本期', '上期'] },
    xAxis: { type: 'category', data: ['Q1', 'Q2', 'Q3', 'Q4'] },
    yAxis: { type: 'value' },
    series: [
      {
        name: '本期',
        type: 'bar',
        data: [320, 332, 301, 334],
        itemStyle: { color: '#5470c6' }
      },
      {
        name: '上期',
        type: 'bar',
        data: [220, 182, 191, 234],
        itemStyle: { color: '#91cc75' }
      }
    ]
  }
})

// 表格数据
const tableData = ref([])
const tableSearch = ref('')
const tableColumns = ref([
  { prop: 'date', label: '日期', width: 120, sortable: true },
  { prop: 'department', label: '部门', width: 100 },
  { prop: 'revenue', label: '收入', width: 120, formatter: (row: any) => `¥${row.revenue.toLocaleString()}` },
  { prop: 'orders', label: '订单数', width: 100, sortable: true },
  { prop: 'conversion', label: '转化率', width: 100, formatter: (row: any) => `${(row.conversion * 100).toFixed(2)}%` },
  { prop: 'status', label: '状态', width: 80 }
])

const pagination = ref({
  page: 1,
  size: 20,
  total: 0
})

// 导出配置
const exportConfig = ref({
  format: 'excel',
  content: ['kpi', 'charts', 'data'],
  fileName: '{{ReportName}}_' + new Date().toISOString().slice(0, 10)
})

// 计算属性
const filteredTableData = computed(() => {
  if (!tableSearch.value) return tableData.value
  return tableData.value.filter((row: any) => 
    Object.values(row).some(val => 
      String(val).toLowerCase().includes(tableSearch.value.toLowerCase())
    )
  )
})

// 方法
const formatDateTime = (date: Date) => {
  return date.toLocaleString('zh-CN')
}

const getDataStatusType = (status: string) => {
  const types: Record<string, string> = {
    'loading': 'warning',
    'loaded': 'success',
    'error': 'danger',
    'empty': 'info'
  }
  return types[status] || 'info'
}

const getDataStatusText = (status: string) => {
  const texts: Record<string, string> = {
    'loading': '数据加载中',
    'loaded': '数据正常',
    'error': '数据异常',
    'empty': '暂无数据'
  }
  return texts[status] || '未知状态'
}

const formatKpiValue = (value: number, format: string) => {
  switch (format) {
    case 'currency':
      return `¥${value.toLocaleString()}`
    case 'percentage':
      return `${(value * 100).toFixed(2)}%`
    case 'number':
      return value.toLocaleString()
    default:
      return String(value)
  }
}

const getTrendIcon = (trend: number) => {
  return trend > 0 ? 'el-icon-top' : trend < 0 ? 'el-icon-bottom' : 'el-icon-minus'
}

const handleTimeRangeChange = (range: [string, string] | null) => {
  if (range) {
    timeRange.value = range
    refreshData()
  }
}

const handleDimensionChange = () => {
  refreshData()
}

const refreshData = async () => {
  if (refreshing.value) return
  
  refreshing.value = true
  chartsLoading.value = true
  tableLoading.value = true
  dataStatus.value = 'loading'
  
  try {
    // 模拟API调用
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    // 更新数据
    lastUpdateTime.value = new Date()
    dataStatus.value = 'loaded'
    
    // 重新生成图表数据
    updateMainChart()
    updateComparisonChart()
    
    ElMessage.success('数据刷新成功')
    
  } catch (error) {
    console.error('刷新数据失败:', error)
    dataStatus.value = 'error'
    ElMessage.error('数据刷新失败')
  } finally {
    refreshing.value = false
    chartsLoading.value = false
    tableLoading.value = false
  }
}

const toggleAutoRefresh = () => {
  autoRefresh.value = !autoRefresh.value
  
  if (autoRefresh.value) {
    refreshInterval.value = window.setInterval(() => {
      refreshData()
    }, 30000) // 30秒刷新一次
    ElMessage.info('已开启自动刷新 (30秒间隔)')
  } else {
    if (refreshInterval.value) {
      clearInterval(refreshInterval.value)
      refreshInterval.value = null
    }
    ElMessage.info('已关闭自动刷新')
  }
}

const updateMainChart = () => {
  // 根据选择的图表类型更新配置
  if (mainChart.value.type === 'bar') {
    mainChart.value.option.series.forEach((series: any) => {
      series.type = 'bar'
      delete series.smooth
      delete series.areaStyle
    })
  } else if (mainChart.value.type === 'area') {
    mainChart.value.option.series.forEach((series: any) => {
      series.type = 'line'
      series.smooth = true
      series.areaStyle = { opacity: 0.3 }
    })
  } else {
    mainChart.value.option.series.forEach((series: any) => {
      series.type = 'line'
      series.smooth = true
      delete series.areaStyle
    })
  }
}

const updateComparisonChart = () => {
  // 根据对比类型更新数据
  const mockData: Record<string, number[]> = {
    'yoy': [320, 332, 301, 334], // 同比数据
    'mom': [280, 312, 291, 314], // 环比数据
    'base': [300, 322, 281, 324]  // 定基比数据
  }
  
  comparisonChart.value.option.series[0].data = mockData[comparisonChart.value.compareBy]
}

const handleTableSearch = (value: string) => {
  // 实现表格搜索逻辑
  pagination.value.page = 1
}

const handleSort = (sort: any) => {
  // 实现表格排序逻辑
  console.log('排序:', sort)
}

const handlePageChange = (page: number) => {
  pagination.value.page = page
  // 重新加载数据
}

const handleSizeChange = (size: number) => {
  pagination.value.size = size
  pagination.value.page = 1
  // 重新加载数据
}

const handleRowDetail = (row: any) => {
  // 显示行详情
  ElMessage.info(`查看详情: ${row.id}`)
}

const handleRowDrill = (row: any) => {
  // 数据钻取
  ElMessage.info(`数据钻取: ${row.id}`)
}

const handleExport = async () => {
  exporting.value = true
  
  try {
    // 模拟导出过程
    await new Promise(resolve => setTimeout(resolve, 3000))
    
    const result = {
      format: exportConfig.value.format,
      fileName: exportConfig.value.fileName
    }
    
    emit('dataExported', result)
    ElMessage.success('报表导出成功')
    showExportDialog.value = false
    
  } catch (error) {
    console.error('导出失败:', error)
    ElMessage.error('报表导出失败')
  } finally {
    exporting.value = false
  }
}

const saveReportConfig = () => {
  emit('configChanged', reportConfig.value)
  ElMessage.success('配置保存成功')
  showConfigDialog.value = false
}

// 生命周期
onMounted(() => {
  refreshData()
})

onBeforeUnmount(() => {
  if (refreshInterval.value) {
    clearInterval(refreshInterval.value)
  }
})
</script>

<style scoped>
.data-analysis-report {
  padding: 20px;
  background: #f5f5f5;
}

.report-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 20px;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.report-info h2 {
  margin: 0 0 8px 0;
  color: #303133;
  font-size: 24px;
}

.report-meta {
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 14px;
  color: #606266;
}

.report-controls {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}

.kpi-cards-section {
  margin-bottom: 20px;
}

.kpi-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 20px;
}

.kpi-card {
  display: flex;
  align-items: center;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transition: transform 0.2s, box-shadow 0.2s;
}

.kpi-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
}

.kpi-card.trend-up {
  border-left: 4px solid #67c23a;
}

.kpi-card.trend-down {
  border-left: 4px solid #f56c6c;
}

.kpi-icon {
  flex-shrink: 0;
  width: 60px;
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f0f9ff;
  border-radius: 50%;
  margin-right: 16px;
}

.kpi-icon i {
  font-size: 24px;
  color: #409eff;
}

.kpi-content {
  flex: 1;
}

.kpi-label {
  font-size: 14px;
  color: #909399;
  margin-bottom: 4px;
}

.kpi-value {
  font-size: 28px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 4px;
}

.kpi-trend {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.trend-indicator {
  color: #67c23a;
}

.kpi-card.trend-down .trend-indicator {
  color: #f56c6c;
}

.trend-period {
  color: #909399;
}

.charts-section {
  margin-bottom: 20px;
}

.chart-card {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.chart-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.chart-container {
  width: 100%;
}

.data-table-section {
  margin-bottom: 20px;
}

.table-card {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.table-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.table-pagination {
  margin-top: 16px;
  text-align: center;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .report-header {
    flex-direction: column;
    gap: 16px;
  }
  
  .report-controls {
    width: 100%;
    justify-content: flex-start;
  }
  
  .kpi-cards {
    grid-template-columns: 1fr;
  }
  
  .chart-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 8px;
  }
  
  .table-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 8px;
  }
}

@media (max-width: 480px) {
  .data-analysis-report {
    padding: 10px;
  }
  
  .report-header {
    padding: 16px;
  }
  
  .kpi-card {
    padding: 16px;
  }
  
  .kpi-value {
    font-size: 24px;
  }
}
</style>
