// 设备 DTOs
// Generated by SmartAbp DevKit

namespace .Application.DTOs
{
    public class EquipmentDto
    {
        public Guid Id { get; set; }
        // Fields...
    }

    public class CreateEquipmentDto
    {
        // Fields...
    }

    public class UpdateEquipmentDto
    {
        // Fields...
    }
}