// 生产线 DTOs
// Generated by SmartAbp DevKit

namespace .Application.DTOs
{
    public class ProductionLineDto
    {
        public Guid Id { get; set; }
        // Fields...
    }

    public class CreateProductionLineDto
    {
        // Fields...
    }

    public class UpdateProductionLineDto
    {
        // Fields...
    }
}