// 传感器数据 DTOs
// Generated by SmartAbp DevKit

namespace .Application.DTOs
{
    public class SensorDataDto
    {
        public Guid Id { get; set; }
        // Fields...
    }

    public class CreateSensorDataDto
    {
        // Fields...
    }

    public class UpdateSensorDataDto
    {
        // Fields...
    }
}