<!--
{{DashboardName}}企业级仪表盘
高管决策支持仪表盘，实时展示关键业务指标和趋势分析
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="executive-dashboard">
    <!-- 仪表盘头部 -->
    <div class="dashboard-header">
      <div class="header-left">
        <h1>{{ dashboardConfig.title }}</h1>
        <div class="dashboard-meta">
          <el-tag type="success">{{ currentPeriod }}</el-tag>
          <span class="last-update">更新时间: {{ formatTime(lastUpdateTime) }}</span>
          <el-tag :type="getDataFreshnessType(dataFreshness)">
            {{ getDataFreshnessText(dataFreshness) }}
          </el-tag>
        </div>
      </div>
      
      <div class="header-actions">
        <el-dropdown @command="handleQuickFilter">
          <el-button icon="el-icon-s-operation">
            快速筛选 <el-icon><arrow-down /></el-icon>
          </el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item command="today">今日数据</el-dropdown-item>
              <el-dropdown-item command="week">本周数据</el-dropdown-item>
              <el-dropdown-item command="month">本月数据</el-dropdown-item>
              <el-dropdown-item command="quarter">本季数据</el-dropdown-item>
              <el-dropdown-item command="year">本年数据</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
        
        <el-button-group>
          <el-button 
            :type="viewMode === 'overview' ? 'primary' : 'default'"
            @click="viewMode = 'overview'"
          >
            总览
          </el-button>
          <el-button 
            :type="viewMode === 'detail' ? 'primary' : 'default'"
            @click="viewMode = 'detail'"
          >
            详细
          </el-button>
          <el-button 
            :type="viewMode === 'realtime' ? 'primary' : 'default'"
            @click="viewMode = 'realtime'"
          >
            实时
          </el-button>
        </el-button-group>
        
        <el-button 
          :loading="refreshing" 
          icon="el-icon-refresh" 
          @click="refreshAllData"
        >
          刷新
        </el-button>
        
        <el-button 
          icon="el-icon-setting" 
          @click="showDashboardSettings = true"
        >
          设置
        </el-button>
      </div>
    </div>

    <!-- 核心KPI指标区域 -->
    <div v-if="viewMode === 'overview'" class="overview-section">
      <!-- 关键绩效指标卡片 -->
      <div class="kpi-grid">
        <div 
          v-for="kpi in coreKPIs"
          :key="kpi.id"
          class="kpi-card-executive"
          :class="`kpi-${kpi.status}`"
        >
          <div class="kpi-header">
            <div class="kpi-title">
              <i :class="kpi.icon" />
              <span>{{ kpi.title }}</span>
            </div>
            <div class="kpi-period">{{ kpi.period }}</div>
          </div>
          
          <div class="kpi-main">
            <div class="kpi-value">{{ formatKpiValue(kpi.value, kpi.format) }}</div>
            <div class="kpi-change" :class="`change-${kpi.changeType}`">
              <i :class="getChangeIcon(kpi.changeType)" />
              <span>{{ Math.abs(kpi.change) }}{{ kpi.changeUnit }}</span>
              <span class="change-label">{{ kpi.changePeriod }}</span>
            </div>
          </div>
          
          <div class="kpi-sparkline">
            <MiniChart 
              :data="kpi.trendData" 
              :type="kpi.chartType"
              :color="kpi.color"
              height="40px"
            />
          </div>
          
          <div v-if="kpi.target" class="kpi-target">
            <div class="target-progress">
              <el-progress 
                :percentage="(kpi.value / kpi.target) * 100"
                :stroke-width="4"
                :show-text="false"
                :color="getProgressColor(kpi.value, kpi.target)"
              />
            </div>
            <span class="target-text">目标: {{ formatKpiValue(kpi.target, kpi.format) }}</span>
          </div>
        </div>
      </div>

      <!-- 趋势对比图表区域 -->
      <el-row :gutter="20" class="charts-row">
        <!-- 收入趋势 -->
        <el-col :xs="24" :sm="24" :md="12" :lg="8">
          <div class="dashboard-chart-card">
            <div class="chart-header">
              <h3>{{ revenueChart.title }}</h3>
              <div class="chart-controls">
                <el-select v-model="revenueChart.period" size="small" @change="updateRevenueChart">
                  <el-option label="日" value="daily" />
                  <el-option label="周" value="weekly" />
                  <el-option label="月" value="monthly" />
                </el-select>
              </div>
            </div>
            <div class="chart-content">
              <ECharts 
                :option="revenueChart.option" 
                :height="200" 
                :loading="revenueChart.loading"
              />
            </div>
          </div>
        </el-col>
        
        <!-- 用户增长 -->
        <el-col :xs="24" :sm="24" :md="12" :lg="8">
          <div class="dashboard-chart-card">
            <div class="chart-header">
              <h3>{{ userGrowthChart.title }}</h3>
              <div class="chart-summary">
                <span class="summary-value">+{{ userGrowthChart.growth }}%</span>
                <span class="summary-label">月增长</span>
              </div>
            </div>
            <div class="chart-content">
              <ECharts 
                :option="userGrowthChart.option" 
                :height="200"
                :loading="userGrowthChart.loading"
              />
            </div>
          </div>
        </el-col>
        
        <!-- 市场占有率 -->
        <el-col :xs="24" :sm="24" :md="12" :lg="8">
          <div class="dashboard-chart-card">
            <div class="chart-header">
              <h3>{{ marketShareChart.title }}</h3>
              <div class="chart-legend">
                <div 
                  v-for="item in marketShareChart.legend"
                  :key="item.name"
                  class="legend-item"
                >
                  <span 
                    class="legend-color" 
                    :style="{ backgroundColor: item.color }"
                  />
                  <span class="legend-name">{{ item.name }}</span>
                  <span class="legend-value">{{ item.value }}%</span>
                </div>
              </div>
            </div>
            <div class="chart-content">
              <ECharts 
                :option="marketShareChart.option" 
                :height="200"
                :loading="marketShareChart.loading"
              />
            </div>
          </div>
        </el-col>
      </el-row>

      <!-- 业务健康度雷达图 -->
      <div class="business-health-section">
        <div class="dashboard-chart-card large">
          <div class="chart-header">
            <h3>业务健康度评估</h3>
            <div class="health-score">
              <div class="score-circle" :class="`score-${getHealthLevel(overallHealthScore)}`">
                {{ overallHealthScore }}<small>/100</small>
              </div>
              <div class="score-label">综合评分</div>
            </div>
          </div>
          <div class="chart-content">
            <ECharts 
              :option="businessHealthChart.option" 
              :height="300"
              :loading="businessHealthChart.loading"
            />
          </div>
        </div>
      </div>
    </div>

    <!-- 详细数据视图 -->
    <div v-else-if="viewMode === 'detail'" class="detail-section">
      <el-tabs v-model="activeDetailTab" type="card">
        <el-tab-pane label="财务分析" name="financial">
          <FinancialAnalysisPanel :data="detailData.financial" />
        </el-tab-pane>
        <el-tab-pane label="运营数据" name="operations">
          <OperationsAnalysisPanel :data="detailData.operations" />
        </el-tab-pane>
        <el-tab-pane label="市场表现" name="marketing">
          <MarketingAnalysisPanel :data="detailData.marketing" />
        </el-tab-pane>
        <el-tab-pane label="风险监控" name="risk">
          <RiskMonitoringPanel :data="detailData.risk" />
        </el-tab-pane>
      </el-tabs>
    </div>

    <!-- 实时监控视图 -->
    <div v-else-if="viewMode === 'realtime'" class="realtime-section">
      <div class="realtime-alerts">
        <h3>实时警报</h3>
        <div class="alerts-list">
          <div 
            v-for="alert in realtimeAlerts"
            :key="alert.id"
            class="alert-item"
            :class="`alert-${alert.level}`"
          >
            <div class="alert-icon">
              <i :class="getAlertIcon(alert.level)" />
            </div>
            <div class="alert-content">
              <div class="alert-title">{{ alert.title }}</div>
              <div class="alert-description">{{ alert.description }}</div>
              <div class="alert-time">{{ formatTime(alert.timestamp) }}</div>
            </div>
            <div class="alert-actions">
              <el-button size="small" @click="handleAlert(alert)">处理</el-button>
            </div>
          </div>
        </div>
      </div>
      
      <div class="realtime-metrics">
        <h3>实时指标</h3>
        <div class="metrics-grid">
          <div 
            v-for="metric in realtimeMetrics"
            :key="metric.id"
            class="realtime-metric-card"
          >
            <div class="metric-title">{{ metric.title }}</div>
            <div class="metric-value">{{ metric.value }}</div>
            <div class="metric-chart">
              <MiniChart 
                :data="metric.realtimeData" 
                type="line"
                :color="metric.color"
                height="50px"
                :realtime="true"
              />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 仪表盘设置对话框 -->
    <el-dialog
      v-model="showDashboardSettings"
      title="仪表盘设置"
      width="800px"
    >
      <el-tabs>
        <el-tab-pane label="布局设置" name="layout">
          <DashboardLayoutConfig v-model="dashboardConfig.layout" />
        </el-tab-pane>
        <el-tab-pane label="数据源" name="datasource">
          <DashboardDataSourceConfig v-model="dashboardConfig.datasource" />
        </el-tab-pane>
        <el-tab-pane label="告警配置" name="alerts">
          <DashboardAlertConfig v-model="dashboardConfig.alerts" />
        </el-tab-pane>
        <el-tab-pane label="权限设置" name="permissions">
          <DashboardPermissionConfig v-model="dashboardConfig.permissions" />
        </el-tab-pane>
      </el-tabs>
      <template #footer>
        <el-button @click="showDashboardSettings = false">取消</el-button>
        <el-button type="primary" @click="saveDashboardConfig">保存配置</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowDown } from '@element-plus/icons-vue'
import ECharts from '@/components/common/ECharts.vue'
import MiniChart from '@/components/common/MiniChart.vue'
import FinancialAnalysisPanel from './panels/FinancialAnalysisPanel.vue'
import OperationsAnalysisPanel from './panels/OperationsAnalysisPanel.vue'
import MarketingAnalysisPanel from './panels/MarketingAnalysisPanel.vue'
import RiskMonitoringPanel from './panels/RiskMonitoringPanel.vue'
import DashboardLayoutConfig from './config/DashboardLayoutConfig.vue'
import DashboardDataSourceConfig from './config/DashboardDataSourceConfig.vue'
import DashboardAlertConfig from './config/DashboardAlertConfig.vue'
import DashboardPermissionConfig from './config/DashboardPermissionConfig.vue'

// 接口定义
interface KPI {
  id: string
  title: string
  value: number
  format: string
  change: number
  changeType: 'up' | 'down' | 'stable'
  changeUnit: string
  changePeriod: string
  target?: number
  period: string
  icon: string
  status: 'good' | 'warning' | 'danger'
  trendData: number[]
  chartType: string
  color: string
}

interface RealtimeAlert {
  id: string
  title: string
  description: string
  level: 'high' | 'medium' | 'low'
  timestamp: Date
}

// 组件属性
interface Props {
  dashboardId?: string
  config?: any
  refreshInterval?: number
}

const props = withDefaults(defineProps<Props>(), {
  refreshInterval: 30000 // 30秒刷新一次
})

// 组件事件
const emit = defineEmits<{
  configChanged: [config: any]
  alertHandled: [alert: RealtimeAlert]
}>()

// 响应式数据
const dashboardConfig = ref({
  title: '{{DashboardName}}',
  layout: {},
  datasource: {},
  alerts: {},
  permissions: {}
})

// 视图模式和状态
const viewMode = ref<'overview' | 'detail' | 'realtime'>('overview')
const currentPeriod = ref('2025年9月')
const lastUpdateTime = ref(new Date())
const dataFreshness = ref<'fresh' | 'stale' | 'error'>('fresh')
const refreshing = ref(false)
const showDashboardSettings = ref(false)
const activeDetailTab = ref('financial')

// 核心KPI数据
const coreKPIs = ref<KPI[]>([
  {
    id: 'revenue',
    title: '总收入',
    value: 12567890,
    format: 'currency',
    change: 12.5,
    changeType: 'up',
    changeUnit: '%',
    changePeriod: '较上月',
    target: 15000000,
    period: '本月',
    icon: 'el-icon-money',
    status: 'good',
    trendData: [8500000, 9200000, 10100000, 11300000, 12567890],
    chartType: 'line',
    color: '#409eff'
  },
  {
    id: 'profit',
    title: '净利润',
    value: 2134567,
    format: 'currency',
    change: -3.2,
    changeType: 'down',
    changeUnit: '%',
    changePeriod: '较上月',
    target: 2500000,
    period: '本月',
    icon: 'el-icon-s-finance',
    status: 'warning',
    trendData: [1800000, 2100000, 2200000, 2210000, 2134567],
    chartType: 'line',
    color: '#e6a23c'
  },
  {
    id: 'users',
    title: '活跃用户',
    value: 987654,
    format: 'number',
    change: 24.6,
    changeType: 'up',
    changeUnit: '%',
    changePeriod: '较上月',
    period: '本月',
    icon: 'el-icon-user',
    status: 'good',
    trendData: [650000, 720000, 780000, 845000, 987654],
    chartType: 'bar',
    color: '#67c23a'
  },
  {
    id: 'conversion',
    title: '转化率',
    value: 0.0523,
    format: 'percentage',
    change: 0.8,
    changeType: 'up',
    changeUnit: '个百分点',
    changePeriod: '较上月',
    target: 0.06,
    period: '本月',
    icon: 'el-icon-pie-chart',
    status: 'good',
    trendData: [0.045, 0.048, 0.051, 0.052, 0.0523],
    chartType: 'line',
    color: '#f56c6c'
  }
])

// 综合健康评分
const overallHealthScore = ref(78)

// 图表数据
const revenueChart = ref({
  title: '收入趋势',
  period: 'monthly',
  loading: false,
  option: {
    tooltip: { trigger: 'axis' },
    xAxis: { type: 'category', data: ['1月', '2月', '3月', '4月', '5月', '6月'] },
    yAxis: { type: 'value' },
    series: [{
      name: '收入',
      type: 'line',
      data: [850, 920, 1010, 1130, 1257, 1456],
      smooth: true,
      areaStyle: { opacity: 0.3 }
    }]
  }
})

const userGrowthChart = ref({
  title: '用户增长',
  growth: 24.6,
  loading: false,
  option: {
    tooltip: { trigger: 'axis' },
    xAxis: { type: 'category', data: ['1月', '2月', '3月', '4月', '5月', '6月'] },
    yAxis: { type: 'value' },
    series: [{
      name: '新增用户',
      type: 'bar',
      data: [65000, 72000, 78000, 84500, 98765, 115000],
      itemStyle: { color: '#67c23a' }
    }]
  }
})

const marketShareChart = ref({
  title: '市场份额',
  loading: false,
  legend: [
    { name: '我们', color: '#409eff', value: 35.2 },
    { name: '竞品A', color: '#67c23a', value: 28.5 },
    { name: '竞品B', color: '#e6a23c', value: 19.8 },
    { name: '其他', color: '#f56c6c', value: 16.5 }
  ],
  option: {
    tooltip: { trigger: 'item' },
    series: [{
      name: '市场份额',
      type: 'pie',
      radius: ['40%', '70%'],
      data: [
        { value: 35.2, name: '我们', itemStyle: { color: '#409eff' } },
        { value: 28.5, name: '竞品A', itemStyle: { color: '#67c23a' } },
        { value: 19.8, name: '竞品B', itemStyle: { color: '#e6a23c' } },
        { value: 16.5, name: '其他', itemStyle: { color: '#f56c6c' } }
      ],
      emphasis: {
        itemStyle: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: 'rgba(0, 0, 0, 0.5)'
        }
      }
    }]
  }
})

const businessHealthChart = ref({
  loading: false,
  option: {
    tooltip: {},
    legend: { data: ['当前', '目标'] },
    radar: {
      indicator: [
        { name: '收入增长', max: 100 },
        { name: '用户满意度', max: 100 },
        { name: '市场份额', max: 100 },
        { name: '运营效率', max: 100 },
        { name: '创新能力', max: 100 },
        { name: '风险控制', max: 100 }
      ]
    },
    series: [{
      name: '业务健康度',
      type: 'radar',
      data: [
        {
          value: [85, 72, 68, 78, 65, 82],
          name: '当前',
          itemStyle: { color: '#409eff' }
        },
        {
          value: [90, 85, 80, 85, 80, 90],
          name: '目标',
          itemStyle: { color: '#67c23a' },
          lineStyle: { type: 'dashed' }
        }
      ]
    }]
  }
})

// 实时数据
const realtimeAlerts = ref<RealtimeAlert[]>([
  {
    id: '1',
    title: '系统响应时间异常',
    description: 'API响应时间超过3秒，影响用户体验',
    level: 'high',
    timestamp: new Date(Date.now() - 5 * 60000) // 5分钟前
  },
  {
    id: '2',
    title: '订单量下降',
    description: '过去1小时订单量下降15%',
    level: 'medium',
    timestamp: new Date(Date.now() - 15 * 60000) // 15分钟前
  }
])

const realtimeMetrics = ref([
  {
    id: 'online_users',
    title: '在线用户数',
    value: '12,456',
    color: '#409eff',
    realtimeData: [12000, 12100, 12300, 12456, 12400, 12456]
  },
  {
    id: 'orders_per_minute',
    title: '每分钟订单数',
    value: '23',
    color: '#67c23a',
    realtimeData: [18, 21, 25, 23, 26, 23]
  }
])

// 详细数据
const detailData = ref({
  financial: {},
  operations: {},
  marketing: {},
  risk: {}
})

// 刷新定时器
const refreshTimer = ref<number | null>(null)

// 计算属性
const healthLevel = computed(() => getHealthLevel(overallHealthScore.value))

// 方法
const formatTime = (time: Date) => {
  return time.toLocaleString('zh-CN')
}

const formatKpiValue = (value: number, format: string) => {
  switch (format) {
    case 'currency':
      return `¥${(value / 10000).toFixed(1)}万`
    case 'percentage':
      return `${(value * 100).toFixed(2)}%`
    case 'number':
      return value.toLocaleString()
    default:
      return String(value)
  }
}

const getDataFreshnessType = (freshness: string) => {
  const types: Record<string, string> = {
    'fresh': 'success',
    'stale': 'warning',
    'error': 'danger'
  }
  return types[freshness] || 'info'
}

const getDataFreshnessText = (freshness: string) => {
  const texts: Record<string, string> = {
    'fresh': '数据最新',
    'stale': '数据延迟',
    'error': '数据异常'
  }
  return texts[freshness] || '未知状态'
}

const getChangeIcon = (changeType: string) => {
  const icons: Record<string, string> = {
    'up': 'el-icon-top',
    'down': 'el-icon-bottom',
    'stable': 'el-icon-minus'
  }
  return icons[changeType] || 'el-icon-minus'
}

const getProgressColor = (current: number, target: number) => {
  const ratio = current / target
  if (ratio >= 0.9) return '#67c23a'
  if (ratio >= 0.7) return '#e6a23c'
  return '#f56c6c'
}

const getHealthLevel = (score: number) => {
  if (score >= 80) return 'good'
  if (score >= 60) return 'warning'
  return 'danger'
}

const getAlertIcon = (level: string) => {
  const icons: Record<string, string> = {
    'high': 'el-icon-warning',
    'medium': 'el-icon-info',
    'low': 'el-icon-message'
  }
  return icons[level] || 'el-icon-info'
}

const handleQuickFilter = (command: string) => {
  // 处理快速筛选
  currentPeriod.value = {
    'today': '今日',
    'week': '本周',
    'month': '本月',
    'quarter': '本季',
    'year': '本年'
  }[command] || '本月'
  
  refreshAllData()
  ElMessage.info(`已切换到${currentPeriod.value}数据`)
}

const refreshAllData = async () => {
  if (refreshing.value) return
  
  refreshing.value = true
  
  try {
    // 模拟数据刷新
    await Promise.all([
      updateKPIData(),
      updateChartsData(),
      updateRealtimeData()
    ])
    
    lastUpdateTime.value = new Date()
    dataFreshness.value = 'fresh'
    ElMessage.success('数据刷新成功')
    
  } catch (error) {
    console.error('数据刷新失败:', error)
    dataFreshness.value = 'error'
    ElMessage.error('数据刷新失败')
  } finally {
    refreshing.value = false
  }
}

const updateKPIData = async () => {
  // 模拟KPI数据更新
  await new Promise(resolve => setTimeout(resolve, 1000))
  
  coreKPIs.value.forEach(kpi => {
    // 模拟数据变化
    const randomChange = (Math.random() - 0.5) * 0.1
    kpi.value = Math.round(kpi.value * (1 + randomChange))
  })
}

const updateChartsData = async () => {
  // 模拟图表数据更新
  await new Promise(resolve => setTimeout(resolve, 800))
  
  // 更新收入图表
  revenueChart.value.loading = true
  setTimeout(() => {
    revenueChart.value.loading = false
  }, 500)
}

const updateRealtimeData = async () => {
  // 模拟实时数据更新
  realtimeMetrics.value.forEach(metric => {
    const newValue = Math.floor(Math.random() * 100) + parseInt(metric.value.replace(',', ''))
    metric.value = newValue.toLocaleString()
    
    // 更新趋势数据
    metric.realtimeData.push(newValue)
    if (metric.realtimeData.length > 50) {
      metric.realtimeData.shift()
    }
  })
}

const updateRevenueChart = () => {
  // 根据时间周期更新收入图表
  revenueChart.value.loading = true
  setTimeout(() => {
    revenueChart.value.loading = false
  }, 800)
}

const handleAlert = (alert: RealtimeAlert) => {
  emit('alertHandled', alert)
  
  // 从列表中移除已处理的警报
  const index = realtimeAlerts.value.findIndex(a => a.id === alert.id)
  if (index > -1) {
    realtimeAlerts.value.splice(index, 1)
  }
  
  ElMessage.success('警报已处理')
}

const saveDashboardConfig = () => {
  emit('configChanged', dashboardConfig.value)
  ElMessage.success('配置保存成功')
  showDashboardSettings.value = false
}

const startAutoRefresh = () => {
  if (refreshTimer.value) {
    clearInterval(refreshTimer.value)
  }
  
  refreshTimer.value = window.setInterval(() => {
    if (viewMode.value === 'realtime') {
      updateRealtimeData()
    } else {
      refreshAllData()
    }
  }, props.refreshInterval)
}

// 生命周期
onMounted(() => {
  refreshAllData()
  startAutoRefresh()
})

onBeforeUnmount(() => {
  if (refreshTimer.value) {
    clearInterval(refreshTimer.value)
  }
})
</script>

<style scoped>
.executive-dashboard {
  min-height: 100vh;
  background: #f0f2f5;
  padding: 20px;
}

.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
  padding: 24px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.header-left h1 {
  margin: 0 0 12px 0;
  font-size: 28px;
  font-weight: 600;
  color: #1a1a1a;
}

.dashboard-meta {
  display: flex;
  align-items: center;
  gap: 16px;
  font-size: 14px;
  color: #666;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 12px;
}

.overview-section {
  space-y: 24px;
}

.kpi-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 24px;
  margin-bottom: 32px;
}

.kpi-card-executive {
  background: white;
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
  transition: all 0.3s ease;
  border-left: 4px solid #409eff;
}

.kpi-card-executive:hover {
  transform: translateY(-4px);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.12);
}

.kpi-card-executive.kpi-good {
  border-left-color: #67c23a;
}

.kpi-card-executive.kpi-warning {
  border-left-color: #e6a23c;
}

.kpi-card-executive.kpi-danger {
  border-left-color: #f56c6c;
}

.kpi-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.kpi-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 16px;
  font-weight: 500;
  color: #303133;
}

.kpi-title i {
  font-size: 18px;
  color: #409eff;
}

.kpi-period {
  font-size: 12px;
  color: #909399;
  background: #f5f7fa;
  padding: 4px 8px;
  border-radius: 12px;
}

.kpi-main {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  margin-bottom: 16px;
}

.kpi-value {
  font-size: 32px;
  font-weight: 700;
  color: #1a1a1a;
  line-height: 1;
}

.kpi-change {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 14px;
  font-weight: 500;
}

.kpi-change.change-up {
  color: #67c23a;
}

.kpi-change.change-down {
  color: #f56c6c;
}

.kpi-change.change-stable {
  color: #909399;
}

.change-label {
  font-size: 12px;
  color: #909399;
  margin-left: 4px;
}

.kpi-sparkline {
  margin-bottom: 16px;
}

.kpi-target {
  display: flex;
  align-items: center;
  gap: 12px;
}

.target-progress {
  flex: 1;
}

.target-text {
  font-size: 12px;
  color: #909399;
  white-space: nowrap;
}

.charts-row {
  margin-bottom: 32px;
}

.dashboard-chart-card {
  background: white;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  height: 100%;
}

.dashboard-chart-card.large {
  padding: 32px;
}

.chart-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.chart-header h3 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #303133;
}

.chart-summary {
  text-align: right;
}

.summary-value {
  font-size: 24px;
  font-weight: 600;
  color: #67c23a;
}

.summary-label {
  display: block;
  font-size: 12px;
  color: #909399;
  margin-top: 4px;
}

.chart-legend {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.legend-item {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.legend-color {
  width: 12px;
  height: 12px;
  border-radius: 2px;
}

.legend-name {
  flex: 1;
  color: #606266;
}

.legend-value {
  font-weight: 600;
  color: #303133;
}

.business-health-section {
  margin-bottom: 32px;
}

.health-score {
  text-align: center;
}

.score-circle {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  font-weight: 700;
  color: white;
  margin: 0 auto 8px;
}

.score-circle.score-good {
  background: linear-gradient(135deg, #67c23a, #85ce61);
}

.score-circle.score-warning {
  background: linear-gradient(135deg, #e6a23c, #ebb563);
}

.score-circle.score-danger {
  background: linear-gradient(135deg, #f56c6c, #f78989);
}

.score-circle small {
  font-size: 12px;
  opacity: 0.8;
}

.score-label {
  font-size: 12px;
  color: #909399;
}

.detail-section,
.realtime-section {
  background: white;
  border-radius: 12px;
  padding: 24px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
}

.realtime-alerts {
  margin-bottom: 32px;
}

.realtime-alerts h3 {
  margin: 0 0 20px 0;
  font-size: 18px;
  color: #303133;
}

.alerts-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.alert-item {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 16px;
  border-radius: 8px;
  background: #f5f7fa;
  border-left: 4px solid;
}

.alert-item.alert-high {
  border-left-color: #f56c6c;
  background: #fef0f0;
}

.alert-item.alert-medium {
  border-left-color: #e6a23c;
  background: #fdf6ec;
}

.alert-item.alert-low {
  border-left-color: #909399;
  background: #f5f7fa;
}

.alert-icon {
  flex-shrink: 0;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: white;
}

.alert-content {
  flex: 1;
}

.alert-title {
  font-size: 14px;
  font-weight: 500;
  color: #303133;
  margin-bottom: 4px;
}

.alert-description {
  font-size: 13px;
  color: #606266;
  margin-bottom: 4px;
}

.alert-time {
  font-size: 12px;
  color: #909399;
}

.realtime-metrics h3 {
  margin: 0 0 20px 0;
  font-size: 18px;
  color: #303133;
}

.metrics-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
}

.realtime-metric-card {
  background: white;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  padding: 20px;
}

.metric-title {
  font-size: 14px;
  color: #606266;
  margin-bottom: 8px;
}

.metric-value {
  font-size: 28px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 12px;
}

/* 响应式设计 */
@media (max-width: 1200px) {
  .kpi-grid {
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  }
}

@media (max-width: 768px) {
  .executive-dashboard {
    padding: 12px;
  }
  
  .dashboard-header {
    flex-direction: column;
    gap: 16px;
    padding: 20px;
  }
  
  .header-actions {
    width: 100%;
    justify-content: flex-start;
    flex-wrap: wrap;
  }
  
  .kpi-grid {
    grid-template-columns: 1fr;
  }
  
  .kpi-main {
    flex-direction: column;
    align-items: flex-start;
    gap: 8px;
  }
  
  .chart-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }
  
  .metrics-grid {
    grid-template-columns: 1fr;
  }
}
</style>
