{{- if and .Values.frontend.enabled (gt (int .Values.frontend.replicaCount) 1) }}
apiVersion: {{ include "smartabp.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "smartabp.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "smartabp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "smartabp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
---
{{- if and .Values.backend.enabled (gt (int .Values.backend.replicaCount) 1) }}
apiVersion: {{ include "smartabp.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "smartabp.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "smartabp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "smartabp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
