// <auto-generated />
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TenantManagement.SmartTenant.Services;

namespace TenantManagement.SmartTenant.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class SmartTenantController : ControllerBase
    {
        private readonly ISmartTenantAppService _smarttenantAppService;

        public SmartTenantController(ISmartTenantAppService smarttenantAppService)
        {
            _smarttenantAppService = smarttenantAppService;
        }

        [HttpGet]
        public async Task<ActionResult> GetListAsync()
        {
            var result = await _smarttenantAppService.GetListAsync();
            return Ok(result);
        }
    }
}