<!--
{{ProjectManagerName}}项目管理系统
企业级项目管理组件，支持甘特图、任务管理、资源分配、进度追踪
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="project-manager">
    <!-- 项目总览 -->
    <div class="project-overview">
      <div class="overview-stats">
        <div class="stat-card">
          <div class="stat-icon total-projects">
            <i class="el-icon-folder" />
          </div>
          <div class="stat-info">
            <div class="stat-value">{{ projectStats.total }}</div>
            <div class="stat-label">总项目数</div>
          </div>
        </div>

        <div class="stat-card">
          <div class="stat-icon active-projects">
            <i class="el-icon-loading" />
          </div>
          <div class="stat-info">
            <div class="stat-value">{{ projectStats.active }}</div>
            <div class="stat-label">进行中</div>
          </div>
        </div>

        <div class="stat-card">
          <div class="stat-icon completed-projects">
            <i class="el-icon-circle-check" />
          </div>
          <div class="stat-info">
            <div class="stat-value">{{ projectStats.completed }}</div>
            <div class="stat-label">已完成</div>
          </div>
        </div>

        <div class="stat-card">
          <div class="stat-icon delayed-projects">
            <i class="el-icon-warning" />
          </div>
          <div class="stat-info">
            <div class="stat-value">{{ projectStats.delayed }}</div>
            <div class="stat-label">延期项目</div>
          </div>
        </div>
      </div>

      <div class="overview-actions">
        <el-button type="primary" @click="createProject">
          <i class="el-icon-plus" />
          创建项目
        </el-button>
        <el-button @click="importProject">
          <i class="el-icon-upload" />
          导入项目
        </el-button>
        <el-button @click="exportProjects">
          <i class="el-icon-download" />
          导出报告
        </el-button>
      </div>
    </div>

    <el-tabs v-model="activeTab" type="card">
      <!-- 项目列表 -->
      <el-tab-pane label="项目列表" name="list">
        <div class="project-filters">
          <el-input
            v-model="searchKeyword"
            placeholder="搜索项目名称"
            style="width: 250px"
            clearable
          >
            <template #prefix>
              <i class="el-icon-search" />
            </template>
          </el-input>
          
          <el-select v-model="statusFilter" placeholder="项目状态" clearable>
            <el-option label="全部" value="" />
            <el-option label="未开始" value="not-started" />
            <el-option label="进行中" value="in-progress" />
            <el-option label="已完成" value="completed" />
            <el-option label="已暂停" value="paused" />
            <el-option label="已取消" value="cancelled" />
          </el-select>

          <el-select v-model="priorityFilter" placeholder="优先级" clearable>
            <el-option label="全部" value="" />
            <el-option label="低" value="low" />
            <el-option label="中" value="medium" />
            <el-option label="高" value="high" />
            <el-option label="紧急" value="urgent" />
          </el-select>
        </div>

        <el-table :data="filteredProjects" stripe>
          <el-table-column prop="name" label="项目名称" min-width="200">
            <template #default="{ row }">
              <div class="project-name">
                <strong>{{ row.name }}</strong>
                <div class="project-description">{{ row.description }}</div>
              </div>
            </template>
          </el-table-column>
          
          <el-table-column prop="status" label="状态" width="100">
            <template #default="{ row }">
              <el-tag :type="getStatusTagType(row.status)">
                {{ getStatusLabel(row.status) }}
              </el-tag>
            </template>
          </el-table-column>

          <el-table-column prop="priority" label="优先级" width="100">
            <template #default="{ row }">
              <el-tag :type="getPriorityTagType(row.priority)" size="small">
                {{ getPriorityLabel(row.priority) }}
              </el-tag>
            </template>
          </el-table-column>

          <el-table-column prop="progress" label="进度" width="150">
            <template #default="{ row }">
              <div class="progress-info">
                <el-progress :percentage="row.progress" :stroke-width="8" />
                <span class="progress-text">{{ row.progress }}%</span>
              </div>
            </template>
          </el-table-column>

          <el-table-column prop="manager" label="项目经理" width="120" />

          <el-table-column prop="team" label="团队成员" width="150">
            <template #default="{ row }">
              <el-avatar-group :max="3" size="small">
                <el-avatar
                  v-for="member in row.team"
                  :key="member.id"
                  :src="member.avatar"
                  :title="member.name"
                />
              </el-avatar-group>
              <span v-if="row.team.length > 3" class="team-count">
                +{{ row.team.length - 3 }}
              </span>
            </template>
          </el-table-column>

          <el-table-column prop="startDate" label="开始日期" width="120">
            <template #default="{ row }">
              {{ formatDate(row.startDate) }}
            </template>
          </el-table-column>

          <el-table-column prop="endDate" label="结束日期" width="120">
            <template #default="{ row }">
              {{ formatDate(row.endDate) }}
            </template>
          </el-table-column>

          <el-table-column label="操作" width="200" fixed="right">
            <template #default="{ row }">
              <el-button size="small" @click="viewProject(row)">查看</el-button>
              <el-button size="small" @click="editProject(row)">编辑</el-button>
              <el-dropdown>
                <el-button size="small">
                  更多<i class="el-icon-arrow-down el-icon--right" />
                </el-button>
                <template #dropdown>
                  <el-dropdown-menu>
                    <el-dropdown-item @click="duplicateProject(row)">
                      复制项目
                    </el-dropdown-item>
                    <el-dropdown-item @click="archiveProject(row)">
                      归档项目
                    </el-dropdown-item>
                    <el-dropdown-item
                      divided
                      @click="deleteProject(row)"
                      style="color: #f56c6c"
                    >
                      删除项目
                    </el-dropdown-item>
                  </el-dropdown-menu>
                </template>
              </el-dropdown>
            </template>
          </el-table-column>
        </el-table>

        <el-pagination
          v-model:current-page="currentPage"
          v-model:page-size="pageSize"
          :total="totalProjects"
          :page-sizes="[10, 20, 50, 100]"
          layout="total, sizes, prev, pager, next, jumper"
        />
      </el-tab-pane>

      <!-- 甘特图视图 -->
      <el-tab-pane label="甘特图" name="gantt">
        <div class="gantt-container">
          <div class="gantt-toolbar">
            <el-button-group>
              <el-button :type="ganttView === 'days' ? 'primary' : ''" @click="ganttView = 'days'">
                天
              </el-button>
              <el-button :type="ganttView === 'weeks' ? 'primary' : ''" @click="ganttView = 'weeks'">
                周
              </el-button>
              <el-button :type="ganttView === 'months' ? 'primary' : ''" @click="ganttView = 'months'">
                月
              </el-button>
            </el-button-group>
            
            <el-date-picker
              v-model="ganttDateRange"
              type="daterange"
              range-separator="至"
              start-placeholder="开始日期"
              end-placeholder="结束日期"
            />
          </div>

          <div class="gantt-chart">
            <!-- 甘特图实现 -->
            <div class="gantt-placeholder">
              <i class="el-icon-s-data" style="font-size: 64px; color: #c0c4cc" />
              <p>甘特图功能正在开发中...</p>
            </div>
          </div>
        </div>
      </el-tab-pane>

      <!-- 资源管理 -->
      <el-tab-pane label="资源管理" name="resources">
        <div class="resource-management">
          <div class="resource-overview">
            <el-row :gutter="20">
              <el-col :span="8">
                <el-card title="人力资源">
                  <div class="resource-stat">
                    <div class="stat-value">{{ resourceStats.totalMembers }}</div>
                    <div class="stat-label">总人数</div>
                  </div>
                  <div class="resource-chart">
                    <!-- 人力资源分布图表 -->
                  </div>
                </el-card>
              </el-col>
              <el-col :span="8">
                <el-card title="预算使用">
                  <div class="resource-stat">
                    <div class="stat-value">{{ resourceStats.budgetUsed }}%</div>
                    <div class="stat-label">预算使用率</div>
                  </div>
                  <el-progress
                    :percentage="resourceStats.budgetUsed"
                    :stroke-width="20"
                    :color="getBudgetColor(resourceStats.budgetUsed)"
                  />
                </el-card>
              </el-col>
              <el-col :span="8">
                <el-card title="设备资源">
                  <div class="resource-stat">
                    <div class="stat-value">{{ resourceStats.equipmentUsed }}</div>
                    <div class="stat-label">设备占用</div>
                  </div>
                  <div class="resource-chart">
                    <!-- 设备使用情况图表 -->
                  </div>
                </el-card>
              </el-col>
            </el-row>
          </div>

          <div class="resource-allocation">
            <h3>资源分配</h3>
            <el-table :data="resourceAllocations" stripe>
              <el-table-column prop="project" label="项目" />
              <el-table-column prop="members" label="人员数量" />
              <el-table-column prop="budget" label="预算分配" />
              <el-table-column prop="equipment" label="设备资源" />
              <el-table-column label="利用率">
                <template #default="{ row }">
                  <el-progress :percentage="row.utilization" />
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>
    </el-tabs>

    <!-- 项目创建/编辑对话框 -->
    <el-dialog
      v-model="projectDialogVisible"
      :title="isEditMode ? '编辑项目' : '创建项目'"
      width="700px"
      @close="resetProjectForm"
    >
      <el-form
        ref="projectForm"
        :model="projectForm"
        :rules="projectFormRules"
        label-width="100px"
      >
        <el-form-item label="项目名称" prop="name">
          <el-input v-model="projectForm.name" placeholder="输入项目名称" />
        </el-form-item>

        <el-form-item label="项目描述" prop="description">
          <el-input
            v-model="projectForm.description"
            type="textarea"
            :rows="3"
            placeholder="输入项目描述"
          />
        </el-form-item>

        <el-form-item label="优先级" prop="priority">
          <el-select v-model="projectForm.priority" placeholder="选择优先级">
            <el-option label="低" value="low" />
            <el-option label="中" value="medium" />
            <el-option label="高" value="high" />
            <el-option label="紧急" value="urgent" />
          </el-select>
        </el-form-item>

        <el-form-item label="项目经理" prop="manager">
          <el-select v-model="projectForm.manager" placeholder="选择项目经理">
            <el-option
              v-for="manager in managers"
              :key="manager.id"
              :label="manager.name"
              :value="manager.id"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="团队成员" prop="team">
          <el-select
            v-model="projectForm.team"
            multiple
            placeholder="选择团队成员"
            style="width: 100%"
          >
            <el-option
              v-for="member in teamMembers"
              :key="member.id"
              :label="member.name"
              :value="member.id"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="项目周期" prop="dateRange">
          <el-date-picker
            v-model="projectForm.dateRange"
            type="daterange"
            range-separator="至"
            start-placeholder="开始日期"
            end-placeholder="结束日期"
            style="width: 100%"
          />
        </el-form-item>

        <el-form-item label="预算" prop="budget">
          <el-input-number
            v-model="projectForm.budget"
            :min="0"
            :precision="2"
            style="width: 100%"
          >
            <template #append>万元</template>
          </el-input-number>
        </el-form-item>
      </el-form>

      <template #footer>
        <span class="dialog-footer">
          <el-button @click="projectDialogVisible = false">取消</el-button>
          <el-button type="primary" @click="saveProject">确定</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

// 响应式数据
const activeTab = ref('list')
const searchKeyword = ref('')
const statusFilter = ref('')
const priorityFilter = ref('')
const currentPage = ref(1)
const pageSize = ref(20)
const projectDialogVisible = ref(false)
const isEditMode = ref(false)
const ganttView = ref('weeks')
const ganttDateRange = ref([])

const projectStats = ref({
  total: 48,
  active: 12,
  completed: 28,
  delayed: 8
})

const resourceStats = ref({
  totalMembers: 156,
  budgetUsed: 68,
  equipmentUsed: 23
})

const projects = ref([
  {
    id: 1,
    name: '企业管理系统v2.0',
    description: '全新一代企业级管理系统开发',
    status: 'in-progress',
    priority: 'high',
    progress: 65,
    manager: '张经理',
    team: [
      { id: 1, name: '张三', avatar: '/avatars/1.jpg' },
      { id: 2, name: '李四', avatar: '/avatars/2.jpg' },
      { id: 3, name: '王五', avatar: '/avatars/3.jpg' }
    ],
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-06-30'),
    budget: 120.5
  }
])

const resourceAllocations = ref([
  {
    project: '企业管理系统v2.0',
    members: 8,
    budget: '120.5万',
    equipment: '服务器x3, 工作站x8',
    utilization: 85
  }
])

const managers = ref([
  { id: 1, name: '张经理' },
  { id: 2, name: '李经理' }
])

const teamMembers = ref([
  { id: 1, name: '张三' },
  { id: 2, name: '李四' },
  { id: 3, name: '王五' }
])

// 表单数据
const projectForm = reactive({
  name: '',
  description: '',
  priority: 'medium',
  manager: '',
  team: [],
  dateRange: [],
  budget: 0
})

const projectFormRules = {
  name: [{ required: true, message: '请输入项目名称', trigger: 'blur' }],
  description: [{ required: true, message: '请输入项目描述', trigger: 'blur' }],
  priority: [{ required: true, message: '请选择优先级', trigger: 'change' }],
  manager: [{ required: true, message: '请选择项目经理', trigger: 'change' }],
  dateRange: [{ required: true, message: '请选择项目周期', trigger: 'change' }]
}

// 计算属性
const filteredProjects = computed(() => {
  let result = projects.value

  if (searchKeyword.value) {
    const keyword = searchKeyword.value.toLowerCase()
    result = result.filter(project =>
      project.name.toLowerCase().includes(keyword) ||
      project.description.toLowerCase().includes(keyword)
    )
  }

  if (statusFilter.value) {
    result = result.filter(project => project.status === statusFilter.value)
  }

  if (priorityFilter.value) {
    result = result.filter(project => project.priority === priorityFilter.value)
  }

  return result
})

const totalProjects = computed(() => filteredProjects.value.length)

// 方法
const formatDate = (date: Date) => {
  return date.toLocaleDateString('zh-CN')
}

const getStatusTagType = (status: string) => {
  const typeMap = {
    'not-started': 'info',
    'in-progress': 'warning',
    'completed': 'success',
    'paused': 'danger',
    'cancelled': 'danger'
  }
  return typeMap[status] || ''
}

const getStatusLabel = (status: string) => {
  const labelMap = {
    'not-started': '未开始',
    'in-progress': '进行中',
    'completed': '已完成',
    'paused': '已暂停',
    'cancelled': '已取消'
  }
  return labelMap[status] || status
}

const getPriorityTagType = (priority: string) => {
  const typeMap = {
    low: 'info',
    medium: '',
    high: 'warning',
    urgent: 'danger'
  }
  return typeMap[priority] || ''
}

const getPriorityLabel = (priority: string) => {
  const labelMap = {
    low: '低',
    medium: '中',
    high: '高',
    urgent: '紧急'
  }
  return labelMap[priority] || priority
}

const getBudgetColor = (percentage: number) => {
  if (percentage < 50) return '#67c23a'
  if (percentage < 80) return '#e6a23c'
  return '#f56c6c'
}

const createProject = () => {
  isEditMode.value = false
  resetProjectForm()
  projectDialogVisible.value = true
}

const editProject = (project: any) => {
  isEditMode.value = true
  Object.assign(projectForm, {
    ...project,
    dateRange: [project.startDate, project.endDate],
    team: project.team.map((member: any) => member.id)
  })
  projectDialogVisible.value = true
}

const viewProject = (project: any) => {
  // 跳转到项目详情页
}

const duplicateProject = (project: any) => {
  ElMessage.success('项目复制成功')
}

const archiveProject = (project: any) => {
  ElMessage.success('项目已归档')
}

const deleteProject = async (project: any) => {
  try {
    await ElMessageBox.confirm('确定要删除这个项目吗？', '警告', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    
    ElMessage.success('项目删除成功')
  } catch {
    // 用户取消
  }
}

const saveProject = () => {
  // 保存项目逻辑
  ElMessage.success(isEditMode.value ? '项目更新成功' : '项目创建成功')
  projectDialogVisible.value = false
}

const resetProjectForm = () => {
  Object.assign(projectForm, {
    name: '',
    description: '',
    priority: 'medium',
    manager: '',
    team: [],
    dateRange: [],
    budget: 0
  })
}

const importProject = () => {
  ElMessage.info('导入功能开发中...')
}

const exportProjects = () => {
  ElMessage.info('导出功能开发中...')
}

// 生命周期
onMounted(() => {
  // 初始化数据
})
</script>

<style scoped>
.project-manager {
  padding: 20px;
}

.project-overview {
  margin-bottom: 24px;
  padding: 20px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
}

.overview-stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
  margin-bottom: 20px;
}

.stat-card {
  display: flex;
  align-items: center;
  gap: 16px;
}

.stat-icon {
  width: 56px;
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  font-size: 24px;
  color: white;
}

.total-projects { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
.active-projects { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
.completed-projects { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }
.delayed-projects { background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); }

.stat-info {
  flex: 1;
}

.stat-value {
  font-size: 28px;
  font-weight: 700;
  color: #303133;
  margin-bottom: 4px;
}

.stat-label {
  font-size: 14px;
  color: #909399;
}

.overview-actions {
  display: flex;
  gap: 12px;
}

.project-filters {
  display: flex;
  gap: 16px;
  margin-bottom: 20px;
  align-items: center;
}

.project-name strong {
  color: #303133;
  font-size: 16px;
}

.project-description {
  color: #909399;
  font-size: 12px;
  margin-top: 4px;
}

.progress-info {
  display: flex;
  align-items: center;
  gap: 8px;
}

.progress-text {
  font-size: 12px;
  color: #909399;
  min-width: 35px;
}

.team-count {
  font-size: 12px;
  color: #909399;
  margin-left: 8px;
}

.gantt-container {
  background: white;
  border-radius: 8px;
  padding: 20px;
}

.gantt-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.gantt-chart {
  height: 500px;
  border: 1px solid #ebeef5;
  border-radius: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.gantt-placeholder {
  text-align: center;
  color: #c0c4cc;
}

.resource-management {
  background: white;
  border-radius: 8px;
  padding: 20px;
}

.resource-overview {
  margin-bottom: 32px;
}

.resource-stat {
  text-align: center;
  margin-bottom: 16px;
}

.resource-stat .stat-value {
  font-size: 32px;
  font-weight: 700;
  color: #303133;
  margin-bottom: 8px;
}

.resource-stat .stat-label {
  font-size: 14px;
  color: #909399;
}

.resource-allocation h3 {
  margin-bottom: 16px;
  color: #303133;
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}
</style>
