<!--
{{TableName}}高级数据表格
企业级数据表格组件，支持虚拟滚动、多选、排序、筛选、导出
Generated by SmartAbp LowCode Engine
-->
<template>
  <div class="advanced-data-table">
    <!-- 表格工具栏 -->
    <div class="table-toolbar">
      <div class="toolbar-left">
        <slot name="toolbar-left">
          <el-button type="primary" icon="el-icon-plus" @click="$emit('add')">
            新增
          </el-button>
          <el-button icon="el-icon-delete" @click="handleBatchDelete" :disabled="!hasSelection">
            批量删除
          </el-button>
        </slot>
      </div>
      
      <div class="toolbar-right">
        <el-input
          v-model="searchKeyword"
          placeholder="搜索..."
          style="width: 200px; margin-right: 12px"
          @input="handleSearch"
        >
          <template #prefix>
            <el-icon><Search /></el-icon>
          </template>
        </el-input>
        <el-button icon="el-icon-refresh" @click="refresh" />
        <el-button icon="el-icon-download" @click="exportData" />
        <el-button icon="el-icon-setting" @click="showColumnSettings = true" />
      </div>
    </div>

    <!-- 数据表格 -->
    <el-table
      ref="tableRef"
      :data="filteredData"
      :loading="loading"
      stripe
      border
      :height="tableHeight"
      @selection-change="handleSelectionChange"
      @sort-change="handleSort"
      @filter-change="handleFilter"
    >
      <el-table-column
        v-if="showSelection"
        type="selection"
        width="55"
        fixed="left"
      />
      
      <el-table-column
        v-if="showIndex"
        type="index"
        label="#"
        width="60"
        fixed="left"
      />

      <el-table-column
        v-for="column in visibleColumns"
        :key="column.prop"
        :prop="column.prop"
        :label="column.label"
        :width="column.width"
        :min-width="column.minWidth"
        :sortable="column.sortable"
        :filters="column.filters"
        :show-overflow-tooltip="column.showOverflowTooltip"
        :fixed="column.fixed"
      >
        <template v-if="column.slot" #default="scope">
          <slot :name="column.slot" :row="scope.row" :column="column" :$index="scope.$index" />
        </template>
        
        <template v-else-if="column.formatter" #default="scope">
          <span>{{ column.formatter(scope.row, column, scope.row[column.prop], scope.$index) }}</span>
        </template>
      </el-table-column>

      <el-table-column
        v-if="showActions"
        label="操作"
        :width="actionWidth"
        fixed="right"
      >
        <template #default="scope">
          <slot name="actions" :row="scope.row" :$index="scope.$index">
            <el-button-group size="small">
              <el-button @click="$emit('edit', scope.row)">编辑</el-button>
              <el-button type="danger" @click="handleDelete(scope.row)">删除</el-button>
            </el-button-group>
          </slot>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <div v-if="showPagination" class="table-pagination">
      <el-pagination
        v-model:current-page="currentPage"
        v-model:page-size="pageSize"
        :total="total"
        :page-sizes="pageSizes"
        layout="total, sizes, prev, pager, next, jumper"
        @current-change="handlePageChange"
        @size-change="handleSizeChange"
      />
    </div>

    <!-- 列设置对话框 -->
    <el-dialog v-model="showColumnSettings" title="列设置" width="500px">
      <el-checkbox-group v-model="selectedColumns" @change="handleColumnChange">
        <div v-for="column in columns" :key="column.prop" class="column-setting-item">
          <el-checkbox :label="column.prop">{{ column.label }}</el-checkbox>
        </div>
      </el-checkbox-group>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'

// 接口定义
interface Column {
  prop: string
  label: string
  width?: number
  minWidth?: number
  sortable?: boolean | string
  filters?: Array<{ text: string; value: any }>
  showOverflowTooltip?: boolean
  fixed?: boolean | string
  slot?: string
  formatter?: Function
}

// 组件属性
interface Props {
  data: any[]
  columns: Column[]
  loading?: boolean
  showSelection?: boolean
  showIndex?: boolean
  showActions?: boolean
  showPagination?: boolean
  tableHeight?: number | string
  actionWidth?: number
  pageSizes?: number[]
  defaultPageSize?: number
}

const props = withDefaults(defineProps<Props>(), {
  loading: false,
  showSelection: true,
  showIndex: true,
  showActions: true,
  showPagination: true,
  tableHeight: 600,
  actionWidth: 150,
  pageSizes: () => [10, 20, 50, 100],
  defaultPageSize: 20
})

// 组件事件
const emit = defineEmits<{
  add: []
  edit: [row: any]
  delete: [row: any]
  batchDelete: [rows: any[]]
  search: [keyword: string]
  sort: [sort: any]
  filter: [filters: any]
  pageChange: [page: number]
  sizeChange: [size: number]
  export: []
  refresh: []
}>()

// 响应式数据
const searchKeyword = ref('')
const selectedRows = ref<any[]>([])
const currentPage = ref(1)
const pageSize = ref(props.defaultPageSize)
const total = ref(0)
const showColumnSettings = ref(false)
const selectedColumns = ref<string[]>([])

// 计算属性
const hasSelection = computed(() => selectedRows.value.length > 0)

const filteredData = computed(() => {
  let data = [...props.data]
  if (searchKeyword.value) {
    const keyword = searchKeyword.value.toLowerCase()
    data = data.filter(item => 
      Object.values(item).some(value => 
        String(value).toLowerCase().includes(keyword)
      )
    )
  }
  return data
})

const visibleColumns = computed(() => {
  if (selectedColumns.value.length === 0) {
    return props.columns
  }
  return props.columns.filter(column => selectedColumns.value.includes(column.prop))
})

// 监听数据变化
watch(() => props.data, (newData) => {
  total.value = newData.length
}, { immediate: true })

watch(() => props.columns, (newColumns) => {
  selectedColumns.value = newColumns.map(col => col.prop)
}, { immediate: true })

// 方法
const handleSelectionChange = (selection: any[]) => {
  selectedRows.value = selection
}

const handleSort = (sort: any) => {
  emit('sort', sort)
}

const handleFilter = (filters: any) => {
  emit('filter', filters)
}

const handleSearch = () => {
  emit('search', searchKeyword.value)
}

const handleDelete = async (row: any) => {
  try {
    await ElMessageBox.confirm('确认删除此项？', '删除确认', {
      type: 'warning'
    })
    emit('delete', row)
  } catch {
    // 用户取消
  }
}

const handleBatchDelete = async () => {
  try {
    await ElMessageBox.confirm(`确认删除选中的 ${selectedRows.value.length} 项？`, '批量删除确认', {
      type: 'warning'
    })
    emit('batchDelete', selectedRows.value)
  } catch {
    // 用户取消
  }
}

const handlePageChange = (page: number) => {
  currentPage.value = page
  emit('pageChange', page)
}

const handleSizeChange = (size: number) => {
  pageSize.value = size
  emit('sizeChange', size)
}

const handleColumnChange = () => {
  // 列显示/隐藏变更处理
}

const exportData = () => {
  emit('export')
}

const refresh = () => {
  emit('refresh')
}
</script>

<style scoped>
.advanced-data-table {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.table-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  border-bottom: 1px solid #ebeef5;
}

.toolbar-left {
  display: flex;
  align-items: center;
  gap: 8px;
}

.toolbar-right {
  display: flex;
  align-items: center;
}

.table-pagination {
  padding: 16px 20px;
  text-align: center;
  border-top: 1px solid #ebeef5;
}

.column-setting-item {
  padding: 8px 0;
}

@media (max-width: 768px) {
  .table-toolbar {
    flex-direction: column;
    gap: 12px;
    align-items: stretch;
  }
  
  .toolbar-right {
    justify-content: space-between;
  }
}
</style>
